// apps/web/src/ProjectEditor.tsx
import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ReactFlowProvider } from "@xyflow/react";
import { getMetaMap, writeProjectToDoc, type Project } from "@athanordb/shared";
import { validateProject, type ValidationIssue } from "@athanordb/dbml-engine";
import { useProjectDoc } from "./useProjectDoc.js";
import { useAwarenessStates } from "./useAwarenessStates.js";
import { hashColor } from "./awarenessColor.js";
import { CanvasArea } from "./CanvasArea.js";
import { ChevronRightIcon } from "./Icons.js";
import { DEFAULT_PALETTE } from "./ColorSwatchPicker.js";
import { loadHighlightLinks, saveHighlightLinks } from "./localPrefs.js";
import type { CanvasExportHandle, ProjectSummary } from "./types.js";
import { useCanvasNodes } from "./editor/useCanvasNodes.js";
import { useCanvasEdges } from "./editor/useCanvasEdges.js";
import { useCursorNodes } from "./editor/useCursorNodes.js";
import { useCanvasFontScale } from "./editor/useCanvasFontScale.js";
import { useProjectMutations } from "./editor/useProjectMutations.js";
import { useEditorKeyboardShortcuts } from "./editor/useEditorKeyboardShortcuts.js";
import { ProjectToolbar } from "./editor/ProjectToolbar.js";
import { useCanvasCommands } from "./plugins/usePlugins.js";
import { matchShortcut } from "./plugins/shortcuts.js";
import type { CanvasCommandResult } from "./plugins/types.js";

// Each of these is only needed once a specific panel/dialog is actually
// opened — Monaco (DbmlPanel) especially, which used to load eagerly for
// every visit including the project-list page that never touches it.
const DbmlPanel = lazy(() => import("./DbmlPanel.js"));
const ImportDialog = lazy(() => import("./ImportDialog.js"));
const ExportDialog = lazy(() => import("./ExportDialog.js"));
const HistoryPanel = lazy(() => import("./HistoryPanel.js"));
const ValidationPanel = lazy(() => import("./ValidationPanel.js"));
const PluginManagerDialog = lazy(() => import("./PluginManagerDialog.js"));

import { SettingsModal } from "./SettingsModal.js";
import type { Session } from "./types.js";

export function ProjectEditor(props: {
  project: ProjectSummary;
  session: Session;
  onDisplayNameChange: (name: string) => void;
  onLogout: () => void;
  onBack: () => void;
}) {
  const { project, session } = props;
  const user = session.displayName;
  const {
    project: liveProject,
    doc,
    undoManager,
    awareness,
    connection,
  } = useProjectDoc(project.id, project.name, user);
  const remoteAwareness = useAwarenessStates(awareness);
  const [showImport, setShowImport] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const [dbmlOpen, setDbmlOpen] = useState(true);
  const [showHistory, setShowHistory] = useState(false);
  const [showValidation, setShowValidation] = useState(false);
  const [showPlugins, setShowPlugins] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [pluginMessage, setPluginMessage] = useState<string | null>(null);

  const canvasCommands = useCanvasCommands(project.id);
  const { fontScale, adjustFontScale } = useCanvasFontScale();
  const [highlightLinks, setHighlightLinks] = useState(loadHighlightLinks);
  const [hoveredTableId, setHoveredTableId] = useState<string | null>(null);
  const [dbmlScrollRequest, setDbmlScrollRequest] = useState<{ tableName: string; requestId: number } | null>(null);
  const goToDbml = useCallback((tableName: string) => {
    setDbmlOpen(true);
    setDbmlScrollRequest((prev) => ({ tableName, requestId: (prev?.requestId ?? 0) + 1 }));
  }, []);

  /**
   * The canvas selection, held in a ref rather than passed as a dependency:
   * commands read it at the moment they run, and re-creating `runCanvasCommand`
   * on every selection change would re-render the whole canvas toolbar.
   */
  const selectedTableIdsRef = useRef<string[]>([]);

  /**
   * Runs a plugin canvas command and writes back whatever project it returns.
   * `writeProjectToDoc` diffs entity by entity, so a command that only renames
   * one table produces exactly one Yjs update — and the change lands in every
   * collaborator's canvas through the normal sync path.
   */
  const runCanvasCommand = useCallback(
    async (command: (typeof canvasCommands)[number]) => {
      if (!liveProject || !doc) return;
      const flash = (message: string) => {
        setPluginMessage(message);
        setTimeout(() => setPluginMessage(null), 4000);
      };
      try {
        const selection = selectedTableIdsRef.current;
        const result = (await command.run(liveProject, { selection })) as CanvasCommandResult;
        if (result?.project) doc.transact(() => writeProjectToDoc(doc, result.project as Project));
        flash(result?.message ?? `${command.contribution.label} applied`);
      } catch (err) {
        flash(`Plugin error: ${err instanceof Error ? err.message : String(err)}`);
      }
    },
    [liveProject, doc],
  );

  const handleHighlightLinksChange = (val: boolean) => {
    setHighlightLinks(val);
    saveHighlightLinks(val);
  };

  // Populated by CanvasArea (inside the ReactFlowProvider) so ExportDialog
  // (outside it) can still trigger a canvas screenshot.
  const canvasExportRef = useRef<CanvasExportHandle | null>(null);
  const captureCanvasImage = useCallback(
    (format: "png" | "svg") =>
      canvasExportRef.current?.capture(format) ?? Promise.reject(new Error("Canvas is not ready yet")),
    [],
  );

  const validationIssues: ValidationIssue[] = useMemo(
    () => (liveProject ? validateProject(liveProject) : []),
    [liveProject],
  );
  const hasValidationErrors = validationIssues.some((i) => i.severity === "error");

  const cursorNodes = useCursorNodes(remoteAwareness);

  // Fields that are some ref's endpoint for a given table — shown outside compact detail level even if not PK.
  const refFieldIdsByTable = useMemo(() => {
    const map = new Map<string, Set<string>>();
    if (!liveProject) return map;
    for (const table of liveProject.tables) map.set(table.id, new Set());
    for (const ref of liveProject.refs) {
      map.get(ref.from.tableId)?.add(ref.from.fieldId);
      map.get(ref.to.tableId)?.add(ref.to.fieldId);
    }
    return map;
  }, [liveProject]);

  const palette = liveProject?.paletteColors ?? DEFAULT_PALETTE;
  const onPaletteChange = useCallback(
    (next: string[]) => {
      if (doc) getMetaMap(doc).set("paletteColors", next);
    },
    [doc],
  );

  const { nodes, onNodesChange } = useCanvasNodes(liveProject, doc, refFieldIdsByTable, user, highlightLinks, goToDbml);

  const selectedTableIds = useMemo(
    () => nodes.filter((n) => n.type === "table" && n.selected).map((n) => n.id),
    [nodes],
  );
  useEffect(() => {
    selectedTableIdsRef.current = selectedTableIds;
  }, [selectedTableIds]);

  /**
   * Global bindings for plugin canvas commands. The app's own shortcuts are
   * bound elsewhere and run first; anything typed into a field or the DBML
   * editor is left alone.
   */
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target?.closest("input, textarea, select, .cm-editor, [contenteditable='true']")) return;
      const command = matchShortcut(
        canvasCommands.map((c) => ({ command: c, shortcut: c.contribution.shortcut })),
        event,
      )?.command;
      if (!command) return;
      event.preventDefault();
      void runCanvasCommand(command);
    };
    // Capture phase: a focused React Flow node stops keydown from bubbling to
    // the window (it handles arrows/delete itself), so a bubble-phase listener
    // never fires for the exact case these shortcuts are most useful in —
    // right after clicking a table.
    window.addEventListener("keydown", onKeyDown, true);
    return () => window.removeEventListener("keydown", onKeyDown, true);
  }, [canvasCommands, runCanvasCommand]);
  const edges = useCanvasEdges(liveProject, doc, nodes, highlightLinks, hoveredTableId, palette, onPaletteChange);

  const {
    addTable,
    addZone,
    addStickyNote,
    setAllDetailLevels,
    activeDetailLevel,
    autoLayout,
    setTablesColor,
    duplicateSelected,
    onEdgesDelete,
    onConnect,
  } = useProjectMutations(liveProject, doc, nodes);

  useEditorKeyboardShortcuts(undoManager, duplicateSelected);

  return (
    <div style={{ width: "100%", height: "100%", display: "flex", flexDirection: "column" }}>
      <ProjectToolbar
        projectName={project.name}
        viewOnly={project.permission === "view"}
        connection={connection}
        synced={Boolean(liveProject)}
        onBack={props.onBack}
        onUndo={() => undoManager?.undo()}
        onRedo={() => undoManager?.redo()}
        onAutoLayout={autoLayout}
        onShowImport={() => setShowImport(true)}
        onShowExport={() => setShowExport(true)}
        onShowHistory={() => setShowHistory(true)}
        onShowPlugins={() => setShowPlugins(true)}
        onShowValidation={() => setShowValidation(true)}
        onOpenSettings={() => setShowSettings(true)}
        validationCount={validationIssues.length}
        hasValidationErrors={hasValidationErrors}
        localUser={user}
        localColor={hashColor(user)}
        remoteAwareness={remoteAwareness}
        onDisplayNameChange={props.onDisplayNameChange}
      />
      {showSettings && (
        <SettingsModal
          session={session}
          onClose={() => setShowSettings(false)}
          onDisplayNameChange={props.onDisplayNameChange}
          onLogout={props.onLogout}
        />
      )}

      <div className="relative flex min-h-0 min-w-0 flex-1">
        {dbmlOpen && liveProject ? (
          <Suspense
            fallback={
              <div className="relative flex shrink-0 flex-col border-r border-border bg-surface" style={{ width: 440 }} />
            }
          >
            <DbmlPanel
              project={liveProject}
              projectId={project.id}
              onClose={() => setDbmlOpen(false)}
              scrollToTable={dbmlScrollRequest}
            />
          </Suspense>
        ) : (
          <button
            className="absolute left-2 top-2 z-[5] flex h-[26px] w-[26px] cursor-pointer items-center justify-center rounded-sm border border-border bg-surface-raised p-0 text-text-muted shadow-sm hover:bg-surface-hover hover:text-text"
            onClick={() => setDbmlOpen(true)}
            data-tooltip="Show DBML editor"
            data-tooltip-pos="bottom"
          >
            <ChevronRightIcon size={15} />
          </button>
        )}
        <ReactFlowProvider>
          <CanvasArea
            nodes={nodes}
            cursorNodes={cursorNodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesDelete={onEdgesDelete}
            onConnect={onConnect}
            awareness={awareness}
            onAddTable={addTable}
            onAddZone={addZone}
            onAddNote={addStickyNote}
            onSetTablesColor={setTablesColor}
            palette={palette}
            fontScale={fontScale}
            onAdjustFontScale={adjustFontScale}
            activeDetailLevel={activeDetailLevel}
            onSetDetailLevel={setAllDetailLevels}
            highlightLinks={highlightLinks}
            onHighlightLinksChange={handleHighlightLinksChange}
            onTableHoverChange={setHoveredTableId}
            projectId={project.id}
            viewportUserId={session.id}
            exportRef={canvasExportRef}
            canvasCommands={canvasCommands}
            onRunCanvasCommand={runCanvasCommand}
            onOpenPlugins={() => setShowPlugins(true)}
            statusMessage={pluginMessage}
          />
        </ReactFlowProvider>
      </div>
      <Suspense fallback={null}>
        {showImport && <ImportDialog projectId={project.id} onClose={() => setShowImport(false)} />}
        {showExport && liveProject && (
          <ExportDialog
            projectId={project.id}
            projectName={project.name}
            project={liveProject}
            captureCanvasImage={captureCanvasImage}
            onClose={() => setShowExport(false)}
          />
        )}
        {showHistory && liveProject && (
          <HistoryPanel projectId={project.id} currentProject={liveProject} onClose={() => setShowHistory(false)} />
        )}
        {showValidation && <ValidationPanel issues={validationIssues} onClose={() => setShowValidation(false)} />}
        {showPlugins && <PluginManagerDialog onClose={() => setShowPlugins(false)} />}
      </Suspense>
    </div>
  );
}

// apps/web/src/features/editor/ProjectEditor.svelte
<script lang="ts" module>
  /**
   * Above this many tables, every table renders at "compact" — a display
   * override only, never written to the doc (`liveProject` itself, and
   * everything derived from it, keeps each table's real setting; only
   * `renderProject`, fed to the two rendering passes, is touched). "Full"
   * detail means every field row plus its four handles, per table — measured
   * at 500 tables it was ~66% of a selection-drag's wall-clock time spent in
   * the flow's own hit-testing and the browser's layout/paint for that much
   * DOM, collapsing to a fraction of that at "compact". The threshold is a
   * guess at "more than a screenful even zoomed out", not a measured knee —
   * revisit with the bench harness if it turns out wrong in either direction.
   */
  const RENDER_LOD_TABLE_THRESHOLD = 150;

  function sameIds(a: string[], b: string[]): boolean {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
    return true;
  }
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import { SvelteFlowProvider } from "@xyflow/svelte";
  import { getMetaMap, type DatabaseConnectionSummary, type Project, type Table } from "@athanordb/shared";
  import { validateProject, type ValidationIssue } from "@athanordb/dbml-engine";
  import { listProjectConnections } from "@/services/connectionsApi";
  import { useProjectDoc } from "@/features/collaboration/projectDoc.svelte";
  import { useAwarenessStates, useRemoteSelections } from "@/features/collaboration/awarenessStates.svelte";
  import { hashColor } from "@/features/collaboration/awarenessColor";
  import CanvasArea from "@/features/editor/canvas/CanvasArea.svelte";
  import Icon from "@/components/icons/Icon.svelte";
  import { ChevronRightIcon } from "@/components/icons/Icons";
  import { DEFAULT_PALETTE } from "@/components/inputs/colorSwatches";
  import {
    loadHighlightLinks,
    loadShowValidationIssues,
    saveHighlightLinks,
    saveShowValidationIssues,
  } from "@/utils/preferences";
  import type { CanvasExportHandle, CanvasNavigateHandle, ProjectSummary, Session } from "@/types/index";
  import { CanvasNodesState } from "@/features/editor/hooks/useCanvasNodes/canvasNodes.svelte";
  import { CanvasEdgesState } from "@/features/editor/hooks/canvasEdges.svelte";
  import { useCanvasFontScale } from "@/features/editor/hooks/canvasFontScale.svelte";
  import { activeDetailLevelOf, createProjectMutations } from "@/features/editor/hooks/projectMutations";
  import { useEditorKeyboardShortcuts } from "@/features/editor/hooks/editorKeyboardShortcuts.svelte";
  import { useCanvasCommandRunner } from "@/features/editor/hooks/canvasCommandRunner.svelte";
  import ProjectToolbar from "@/features/editor/ProjectToolbar.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { useCanvasCommands } from "@/features/plugins/plugins.svelte";
  import McdCanvas from "@/features/editor/mcd/McdCanvas.svelte";
  import type { EditorViewMode } from "@/features/editor/mcd/ViewModeToggle.svelte";
  import DbmlPanel from "@/features/editor/dbml/DbmlPanel.svelte";
  import SettingsModal from "@/features/settings/SettingsModal.svelte";

  let props: {
    project: ProjectSummary;
    session: Session;
    onDisplayNameChange: (name: string) => Promise<void>;
    onLogout: () => void;
    onBack: () => void;
    /** Table (and optionally column) to centre on once the document has loaded — from a cross-project search hit. */
    initialFocus?: { tableName: string; fieldName?: string } | null;
  } = $props();

  const { t } = useTranslation();
  const project = $derived(props.project);
  const user = $derived(props.session.displayName);
  /**
   * A `view` grant is enforced by the server, which simply drops the Yjs
   * updates it receives from a read-only connection — silently, with no
   * rejection frame. So without a client-side gate the whole editor stayed
   * live: tables dragged, DBML typed, buttons worked, and every change
   * vanished on reload with nothing ever having said no. Everything that can
   * write to the document is gated on this.
   */
  const canWrite = $derived(project.permission !== "view");
  const docHandle = useProjectDoc(
    () => project.id,
    () => project.name,
    () => user,
  );
  const liveProject = $derived(docHandle.project);
  const doc = $derived(docHandle.doc);
  /** Handed to the write paths in place of `doc`: every mutator already early-returns on a null doc, so one substitution closes all of them at once. */
  const writeDoc = $derived(canWrite ? doc : null);
  const remoteAwareness = useAwarenessStates(() => docHandle.awareness);
  const remoteSelections = useRemoteSelections(() => docHandle.awareness);
  let showImport = $state(false);
  let showExport = $state(false);
  let showConvertTypes = $state(false);
  let dbmlOpen = $state(true);
  let showHistory = $state(false);
  let showPlugins = $state(false);
  let showSettings = $state(false);
  let showDeployment = $state(false);
  let viewMode = $state<EditorViewMode>("mld");
  // Connections themselves are managed from the admin console now — this
  // just needs to know which one to preselect when Deploy opens.
  let activeConnection = $state.raw<DatabaseConnectionSummary | null>(null);

  $effect(() => {
    listProjectConnections(project.id)
      .then((list) => {
        if (list.length > 0) activeConnection = list[0];
      })
      .catch(() => {});
  });

  const canvasCommands = useCanvasCommands(() => project.id);
  const fontScale = useCanvasFontScale();
  let highlightLinks = $state(loadHighlightLinks());
  let showValidationIssues = $state(loadShowValidationIssues());
  let hoveredFieldId = $state<string | null>(null);
  let hoveredTableId = $state<string | null>(null);
  let selectedFieldId = $state<string | null>(null);
  let selectedEdgeId = $state<string | null>(null);
  let dbmlScrollRequest = $state.raw<{ tableName: string; requestId: number } | null>(null);

  // Stable identities: the per-table node cache keys on the callback bundle,
  // so these must never be re-created.
  const goToDbml = (tableName: string) => {
    dbmlOpen = true;
    dbmlScrollRequest = { tableName, requestId: (dbmlScrollRequest?.requestId ?? 0) + 1 };
  };
  const setHoveredFieldId = (id: string | null) => (hoveredFieldId = id);
  const setHoveredTableId = (id: string | null) => (hoveredTableId = id);
  const setSelectedFieldId = (id: string | null) => (selectedFieldId = id);
  const setSelectedEdgeId = (id: string | null) => (selectedEdgeId = id);
  const openPlugins = () => (showPlugins = true);
  const clearFieldSelection = () => {
    selectedFieldId = null;
    selectedEdgeId = null;
  };

  function handleHighlightLinksChange(value: boolean) {
    highlightLinks = value;
    saveHighlightLinks(value);
  }

  function handleShowValidationIssuesChange(value: boolean) {
    showValidationIssues = value;
    saveShowValidationIssues(value);
  }

  // Recomputed on every doc update, like `refFieldIdsByTable` below — cheap
  // (a handful of O(tables+refs) passes) next to the Yjs->Project rebuild that
  // already happens on every change.
  const validationIssues = $derived(liveProject ? validateProject(liveProject) : []);
  const issuesByTable = $derived.by(() => {
    const map = new Map<string, ValidationIssue[]>();
    for (const issue of validationIssues) {
      if (!issue.tableId) continue;
      const list = map.get(issue.tableId);
      if (list) list.push(issue);
      else map.set(issue.tableId, [issue]);
    }
    return map;
  });
  const issuesByRef = $derived.by(() => {
    const map = new Map<string, ValidationIssue[]>();
    for (const issue of validationIssues) {
      if (!issue.refId) continue;
      const list = map.get(issue.refId);
      if (list) list.push(issue);
      else map.set(issue.refId, [issue]);
    }
    return map;
  });

  // Populated by CanvasArea so ExportDialog (outside the canvas) can still
  // trigger a canvas screenshot.
  const canvasExportRef: { current: CanvasExportHandle | null } = { current: null };
  const captureCanvasImage = (format: "png" | "svg") =>
    canvasExportRef.current?.capture(format) ?? Promise.reject(new Error(t("editor.canvasNotReady")));

  // Same shape as the export handle above — this one drives the DBML editor's
  // double-click-to-canvas navigation instead of a screenshot.
  const canvasNavigateRef: { current: CanvasNavigateHandle | null } = { current: null };
  /** Returns whether the canvas actually found the table — false while it hasn't rendered its nodes yet. */
  function onNavigateToCanvas(target: { tableName: string; fieldName?: string }): boolean {
    const table = liveProject?.tables.find((tbl) => tbl.name.toLowerCase() === target.tableName.toLowerCase());
    if (!table) return false;
    const found = canvasNavigateRef.current?.goToTable(table.id) ?? false;
    const field = target.fieldName
      ? table.fields.find((f) => f.name.toLowerCase() === target.fieldName!.toLowerCase())
      : undefined;
    selectedFieldId = field?.id ?? null;
    return found;
  }

  // One-shot: centre on the requested table once it exists in the doc *and*
  // the canvas can navigate. Both arrive later than mount, independently:
  // `liveProject` is non-null (but empty) before the first sync lands, and the
  // canvas only reports ready after Svelte Flow's own initial fit. So this
  // re-arms on every doc change until the target shows up, retries per frame
  // until the canvas accepts the jump, and only then marks itself done.
  let initialFocusDone = false;
  $effect(() => {
    const focus = props.initialFocus;
    const tables = liveProject?.tables;
    if (!focus || initialFocusDone || !tables) return;
    if (!tables.some((table) => table.name.toLowerCase() === focus.tableName.toLowerCase())) return;
    let attempts = 0;
    let frame = 0;
    const tryFocus = () => {
      if (canvasNavigateRef.current && onNavigateToCanvas(focus)) {
        initialFocusDone = true;
        return;
      }
      if (++attempts < 120) frame = requestAnimationFrame(tryFocus);
    };
    frame = requestAnimationFrame(tryFocus);
    return () => cancelAnimationFrame(frame);
  });

  // Fields that are some ref's endpoint for a given table — shown outside
  // compact detail level even if not PK. A fresh Map/Set per project change;
  // the node cache compares the per-table Sets by content, not reference.
  const refFieldIdsByTable = $derived.by(() => {
    const map = new Map<string, Set<string>>();
    if (!liveProject) return map;
    for (const table of liveProject.tables) map.set(table.id, new Set());
    for (const ref of liveProject.refs) {
      map.get(ref.from.tableId)?.add(ref.from.fieldId);
      map.get(ref.to.tableId)?.add(ref.to.fieldId);
    }
    return map;
  });

  const palette = $derived(liveProject?.paletteColors ?? DEFAULT_PALETTE);
  const onPaletteChange = (next: string[]) => {
    if (doc) getMetaMap(doc).set("paletteColors", next);
  };

  // Keyed by the real (Yjs-backed) table object, which `readProjectFromDoc`
  // already keeps reference-stable per id across doc updates that don't touch
  // that particular table. Without this cache, minting a compact copy fresh on
  // every recompute handed every *unchanged* table a new identity too —
  // defeating the per-table node cache's whole point.
  const compactOverrideCache = new WeakMap<Table, Table>();
  const renderProject = $derived.by((): Project | null => {
    if (!liveProject || liveProject.tables.length <= RENDER_LOD_TABLE_THRESHOLD) return liveProject;
    return {
      ...liveProject,
      tables: liveProject.tables.map((tbl) => {
        if (tbl.detailLevel === "compact") return tbl;
        let overridden = compactOverrideCache.get(tbl);
        if (!overridden) {
          overridden = { ...tbl, detailLevel: "compact" as const };
          compactOverrideCache.set(tbl, overridden);
        }
        return overridden;
      }),
    };
  });

  const nodesState = new CanvasNodesState({
    liveProject: () => renderProject,
    doc: () => doc,
    refFieldIdsByTable: () => refFieldIdsByTable,
    user: () => user,
    onGoToDbml: goToDbml,
    onFieldHoverChange: setHoveredFieldId,
    onTableHoverChange: setHoveredTableId,
    selectedFieldId: () => selectedFieldId,
    onSelectField: setSelectedFieldId,
    canWrite: () => canWrite,
    issuesByTable: () => issuesByTable,
    showValidationIssues: () => showValidationIssues,
  });

  // Same array back while the selected set is unchanged — a drag frame
  // replaces `nodes` without changing which tables are selected, and nothing
  // keyed on the selection should hear about it.
  let lastSelectedTableIds: string[] = [];
  const selectedTableIds = $derived.by(() => {
    const next = nodesState.nodes.filter((n) => n.type === "table" && n.selected).map((n) => n.id);
    if (sameIds(next, lastSelectedTableIds)) return lastSelectedTableIds;
    lastSelectedTableIds = next;
    return next;
  });

  const commandRunner = useCanvasCommandRunner({
    liveProject: () => liveProject,
    doc: () => doc,
    canWrite: () => canWrite,
    canvasCommands: () => canvasCommands.list,
    selectedTableIds: () => untrack(() => selectedTableIds),
  });

  const edgesState = new CanvasEdgesState({
    liveProject: () => renderProject,
    doc: () => doc,
    nodes: () => nodesState.nodes,
    highlightLinks: () => highlightLinks,
    hoveredFieldId: () => hoveredFieldId,
    hoveredTableId: () => hoveredTableId,
    selectedFieldId: () => selectedFieldId,
    selectedEdgeId: () => selectedEdgeId,
    onSelectEdge: setSelectedEdgeId,
    palette: () => palette,
    onPaletteChange,
    canWrite: () => canWrite,
    dragging: () => nodesState.dragging,
    issuesByRef: () => issuesByRef,
    showValidationIssues: () => showValidationIssues,
    selectedTableIds: () => selectedTableIds,
  });

  const mutations = createProjectMutations(
    () => liveProject,
    () => writeDoc,
    () => nodesState.nodes,
  );
  const activeDetailLevel = $derived(activeDetailLevelOf(liveProject));

  // Inert while viewing the MCD: nothing dragged there is ever written to the
  // project, so routing Ctrl+Z through the real Yjs history would either no-op
  // confusingly or undo an unrelated MLD edit. `McdCanvas` owns its own local
  // undo/redo for node dragging instead.
  useEditorKeyboardShortcuts(
    () => docHandle.undoManager,
    mutations.duplicateSelected,
    () => canWrite && viewMode === "mld",
  );
</script>

<div style="width: 100%; height: 100%; display: flex; flex-direction: column">
  <ProjectToolbar
    projectName={project.name}
    viewOnly={!canWrite}
    connection={docHandle.connection}
    synced={Boolean(liveProject)}
    onBack={props.onBack}
    onUndo={() => docHandle.undoManager?.undo()}
    onRedo={() => docHandle.undoManager?.redo()}
    onAutoLayout={commandRunner.onAutoLayout}
    onShowImport={() => (showImport = true)}
    onShowExport={() => (showExport = true)}
    onShowConvertTypes={canWrite ? () => (showConvertTypes = true) : undefined}
    onShowHistory={() => (showHistory = true)}
    onShowDeploy={() => (showDeployment = true)}
    isProjectAdmin={project.permission === "administrator"}
    onOpenSettings={() => (showSettings = true)}
    localUser={user}
    localColor={hashColor(user)}
    remoteAwareness={remoteAwareness.states}
  />
  {#if showSettings}
    <SettingsModal
      session={props.session}
      onClose={() => (showSettings = false)}
      onDisplayNameChange={props.onDisplayNameChange}
      onLogout={props.onLogout}
    />
  {/if}

  <div class="relative flex min-h-0 min-w-0 flex-1">
    {#if dbmlOpen && liveProject}
      <DbmlPanel
        project={liveProject}
        projectId={project.id}
        readOnly={!canWrite}
        onClose={() => (dbmlOpen = false)}
        scrollToTable={dbmlScrollRequest}
        {onNavigateToCanvas}
      />
    {:else}
      <button
        class="absolute left-2 top-2 z-[5] flex h-[26px] w-[26px] cursor-pointer items-center justify-center rounded-sm border border-border bg-surface-raised p-0 text-text-muted shadow-sm hover:bg-surface-hover hover:text-text"
        onclick={() => (dbmlOpen = true)}
        data-tooltip={t("editor.showDbmlEditor")}
        data-tooltip-pos="bottom"
        aria-label={t("editor.showDbmlEditor")}
      >
        <Icon icon={ChevronRightIcon} size={15} />
      </button>
    {/if}
    <SvelteFlowProvider>
      <!-- Keyed on the view mode: a fresh mount each switch (never a diff),
           which also replays this entrance animation every time — a quick
           fade+scale so the switch reads as a mode change instead of a jump cut. -->
      {#key viewMode}
        <div class="flex min-h-0 min-w-0 flex-1 animate-view-switch-in">
          {#if viewMode === "mld"}
            <CanvasArea
              {nodesState}
              edges={edgesState.edges}
              {selectedTableIds}
              remoteSelections={remoteSelections.selections}
              onDeleteEdges={mutations.deleteEdges}
              onConnect={mutations.onConnect}
              awareness={docHandle.awareness}
              onAddTable={mutations.addTable}
              onAddZone={mutations.addZone}
              onAddNote={mutations.addStickyNote}
              onAddEnum={mutations.addEnum}
              onGroupTables={commandRunner.onGroupTables}
              onSetTablesColor={mutations.setTablesColor}
              {palette}
              fontScale={fontScale.fontScale}
              {activeDetailLevel}
              onSetDetailLevel={mutations.setAllDetailLevels}
              {highlightLinks}
              onHighlightLinksChange={handleHighlightLinksChange}
              {showValidationIssues}
              onShowValidationIssuesChange={handleShowValidationIssuesChange}
              projectId={project.id}
              viewportUserId={props.session.id}
              exportRef={canvasExportRef}
              navigateRef={canvasNavigateRef}
              canvasCommands={canvasCommands.list}
              onRunCanvasCommand={commandRunner.runCanvasCommand}
              onOpenPlugins={openPlugins}
              statusMessage={commandRunner.pluginMessage}
              {selectedEdgeId}
              onSelectEdge={setSelectedEdgeId}
              onClearFieldSelection={clearFieldSelection}
              {canWrite}
              {viewMode}
              onSetViewMode={(mode) => (viewMode = mode)}
            />
          {:else if liveProject}
            <McdCanvas
              project={liveProject}
              projectId={project.id}
              viewportUserId={props.session.id}
              {viewMode}
              onSetViewMode={(mode) => (viewMode = mode)}
            />
          {/if}
        </div>
      {/key}
    </SvelteFlowProvider>
  </div>

  <!-- Dialogs are code-split: none of them is in the chunk a project view loads. -->
  {#if showImport && canWrite}
    {#await import("@/features/editor/io/ImportDialog.svelte") then { default: ImportDialog }}
      <ImportDialog projectId={project.id} onClose={() => (showImport = false)} />
    {/await}
  {/if}
  {#if showExport && liveProject}
    {#await import("@/features/editor/io/ExportDialog.svelte") then { default: ExportDialog }}
      <ExportDialog
        projectId={project.id}
        projectName={project.name}
        project={liveProject}
        {captureCanvasImage}
        onClose={() => (showExport = false)}
      />
    {/await}
  {/if}
  {#if showConvertTypes && liveProject && canWrite}
    {#await import("@/features/editor/ConvertTypesModal.svelte") then { default: ConvertTypesModal }}
      <ConvertTypesModal
        project={liveProject}
        onApply={mutations.convertFieldTypes}
        onClose={() => (showConvertTypes = false)}
      />
    {/await}
  {/if}
  {#if showHistory && liveProject}
    {#await import("@/features/editor/history/HistoryPanel.svelte") then { default: HistoryPanel }}
      <HistoryPanel projectId={project.id} currentProject={liveProject} onClose={() => (showHistory = false)} />
    {/await}
  {/if}
  {#if showPlugins}
    {#await import("@/features/plugins/PluginManagerDialog.svelte") then { default: PluginManagerDialog }}
      <PluginManagerDialog onClose={() => (showPlugins = false)} />
    {/await}
  {/if}
  {#if showDeployment}
    {#await import("@/features/connections/DeploymentModal.svelte") then { default: DeploymentModal }}
      <DeploymentModal
        projectId={project.id}
        onClose={() => (showDeployment = false)}
        initialConnectionId={activeConnection?.id}
      />
    {/await}
  {/if}
  <!-- Diagnostics overlay for editor stutter/freezes — hidden until Ctrl+Shift+P, see PerfHud. -->
  {#await import("@/components/dev/PerfHud.svelte") then { default: PerfHud }}
    <PerfHud />
  {/await}
</div>
