// apps/web/src/features/editor/edges/RefEdge.tsx
import { memo, useMemo, useState } from "react";
import { EdgeLabelRenderer, useStore, type Edge, type EdgeProps, type ReactFlowState } from "@xyflow/react";
import type { RefCardinality, RoutingPoint } from "@athanordb/shared";
import { useEdgeRouting } from "@/features/editor/edges/useEdgeRouting";
import { polylinePath, splitPolylineAtMidpoint } from "@/features/editor/edges/pathMath";
import { EdgeWaypoints } from "@/features/editor/edges/EdgeWaypoints";
import { CardinalityBadge } from "@/features/editor/edges/CardinalityBadge";
import { EdgeCardinalityLabels, ENDPOINT_CARDINALITY } from "@/features/editor/edges/EdgeCardinalityLabels";
import { EdgeContextMenu } from "@/features/editor/edges/EdgeContextMenu";

export interface RefEdgeData {
  cardinality: RefCardinality;
  /** Rank among the refs sharing this edge's source/target handle — shifts the cardinality chip so co-located refs don't stack on one spot. */
  sourceSlot?: number;
  targetSlot?: number;
  routingPoints?: RoutingPoint[];
  highlightLinks?: boolean;
  /** True when this edge touches the currently hovered or selected table — highlights it independently of the global `highlightLinks` toggle. */
  connectedHighlight?: boolean;
  /** Custom highlight color override — falls back to the cardinality's default color when unset. */
  color?: string;
  palette: string[];
  onPaletteChange: (palette: string[]) => void;
  onColorChange: (color: string | undefined) => void;
  onCardinalityChange?: (cardinality: RefCardinality) => void;
  onRoutingPointsChange: (points: RoutingPoint[] | undefined) => void;
  onDeleteRef?: () => void;
  onSelectEdge?: (id: string | null) => void;
  [key: string]: unknown;
}

export type RefEdgeType = Edge<RefEdgeData, "ref">;

export const CARDINALITY_STYLE: Record<RefCardinality, { stroke: string; label: string }> = {
  "one-to-one": { stroke: "#818cf8", label: "1–1" },
  "one-to-many": { stroke: "#34d399", label: "1–n" },
  "many-to-many": { stroke: "#fbbf24", label: "n–n" },
};

/** Colour of a relation nobody is looking at — deliberately low-contrast so a dense schema reads as structure rather than spaghetti. */
const DIMMED_STROKE = "#475569";
/** Arrowhead size in screen pixels, before the zoom counter-scale. */
const ARROW_LENGTH = 9;
const ARROW_HALF_WIDTH = 5;
/**
 * How finely the zoom-compensation re-renders track the actual zoom level —
 * 5% steps are visually indistinguishable in stroke width/arrow size, but
 * turn "re-render on every one of ~60 viewport frames/second" into
 * "re-render on the handful of frames that actually cross a step". See the
 * `useStore` call below for why this matters at all (a wide schema has a lot
 * of edges, and each one used to pay this on every pan and zoom tick).
 */
const ZOOM_STEP = 0.05;
const zoomSelector = (state: ReactFlowState) => Math.round(state.transform[2] / ZOOM_STEP) * ZOOM_STEP;

/**
 * Arrowhead drawn as part of the edge instead of an SVG `marker-end`.
 *
 * A marker is defined once, up front, with a fixed colour, and React Flow
 * sizes it in `strokeWidth` units — so it stayed the relation's bright colour
 * on a dimmed line and doubled in size the moment the edge was selected.
 * Drawing it here keeps colour, opacity and size in step with the stroke it
 * belongs to.
 */
function EdgeArrowhead(props: { points: { x: number; y: number }[]; color: string; opacity: number; scale: number }) {
  const { points, color, opacity, scale } = props;
  if (points.length < 2) return null;
  const tip = points[points.length - 1];
  const previous = points[points.length - 2];
  if (tip.x === previous.x && tip.y === previous.y) return null;

  const angle = (Math.atan2(tip.y - previous.y, tip.x - previous.x) * 180) / Math.PI;
  const length = ARROW_LENGTH * scale;
  const halfWidth = ARROW_HALF_WIDTH * scale;

  return (
    <polygon
      points={`0,0 ${-length},${-halfWidth} ${-length},${halfWidth}`}
      fill={color}
      opacity={opacity}
      transform={`translate(${tip.x} ${tip.y}) rotate(${angle})`}
      style={{ pointerEvents: "none" }}
    />
  );
}

// eslint-disable-next-line complexity -- edge rendering couples geometry (self-ref/many-to-many splitting), zoom-compensated styling and hover/selection state; a split would move shared derived values across files for no clarity gain
function RefEdgeImpl({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
  selected,
}: EdgeProps<RefEdgeType>) {
  const [isHovered, setIsHovered] = useState(false);
  const style = CARDINALITY_STYLE[data?.cardinality ?? "one-to-many"];
  const isManyToMany = data?.cardinality === "many-to-many";

  const routing = useEdgeRouting({
    edgeId: id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    routingPoints: data?.routingPoints,
    onRoutingPointsChange: (points) => data?.onRoutingPointsChange(points),
  });

  // Pure geometry, so it costs nothing for the edges that never use it and
  // never lands a frame behind the line the way measuring the rendered
  // `<path>` did.
  const split = useMemo(() => splitPolylineAtMidpoint(routing.drawnPoints), [routing.drawnPoints]);
  const labelX = split?.mid.x ?? routing.stepLabelX;
  const labelY = split?.mid.y ?? routing.stepLabelY;

  const isHighlighted = Boolean(data?.highlightLinks || data?.connectedHighlight || selected || isHovered);
  const strokeColor = isHighlighted ? (data?.color ?? style.stroke) : DIMMED_STROKE;
  // Path coordinates live in flow space, which React Flow scales down via a
  // CSS transform as the user zooms out — so a fixed stroke-width/dasharray
  // shrinks to sub-pixel and disappears at low zoom. Dividing by zoom here
  // pre-compensates in flow units so the *rendered* (post-transform) size on
  // screen stays constant regardless of zoom level.
  //
  // Scoped to just the (step-quantized) zoom factor, not `useViewport()`'s
  // full `{x, y, zoom}` — x/y change on every single pan frame and this
  // component never reads them, so subscribing to the whole viewport used to
  // re-render every edge on every pan tick too, not just every zoom tick.
  // With a few hundred edges on screen, that's the difference between a
  // handful of re-renders across a whole zoom gesture and one per edge per
  // frame for the entire pan.
  const zoom = useStore(zoomSelector);
  const zoomCompensation = 1 / Math.max(zoom, 0.01);
  const strokeWidth = (selected ? 2.5 : isHighlighted ? 2 : 1.5) * zoomCompensation;
  const strokeOpacity = selected ? 1 : isHighlighted ? 0.95 : 0.45;

  // Rectangular dashes (dbdiagram style) with clean, well-spaced flow:
  // 8px dash, 10px gap in screen pixels (compensated for zoom)
  const dash = 8 * zoomCompensation;
  const gap = 10 * zoomCompensation;
  const period = -(dash + gap);
  const flowAnimation = isHighlighted ? `ref-edge-flow ${selected ? 0.6 : 0.9}s linear infinite` : "none";
  const strokeDasharray = `${dash} ${gap}`;

  const baseStrokeStyle = {
    stroke: strokeColor,
    strokeWidth: (isHighlighted ? 1.5 : 1.5) * zoomCompensation,
    opacity: isHighlighted ? 0.3 : strokeOpacity,
    strokeLinecap: "round" as const,
  };

  const animatedStrokeStyle = {
    stroke: strokeColor,
    strokeWidth,
    opacity: strokeOpacity,
    strokeDasharray,
    strokeLinecap: "butt" as const,
    animation: flowAnimation,
    ["--dash-period" as string]: `${period}px`,
  };

  // Show editing controls when the edge is selected, or when hovering the edge
  const showEditingControls = Boolean(selected || isHovered);
  const [sourceCardinality, targetCardinality] = ENDPOINT_CARDINALITY[data?.cardinality ?? "one-to-many"];

  return (
    <>
      {isManyToMany && split ? (
        // Split in two so each half animates on its own; both halves still run
        // source → target, which is what keeps the dash flow and the arrowhead
        // pointing the same way as every other cardinality.
        <>
          <path
            d={polylinePath(split.first)}
            fill="none"
            style={baseStrokeStyle}
            onMouseEnter={() => setIsHovered(true)}
          />
          <path
            d={polylinePath(split.second)}
            fill="none"
            style={baseStrokeStyle}
            onMouseEnter={() => setIsHovered(true)}
          />
          {isHighlighted && (
            <>
              <path
                d={polylinePath(split.first)}
                fill="none"
                className="ref-edge-flow-path"
                style={animatedStrokeStyle}
                onMouseEnter={() => setIsHovered(true)}
              />
              <path
                d={polylinePath(split.second)}
                fill="none"
                className="ref-edge-flow-path"
                style={animatedStrokeStyle}
                onMouseEnter={() => setIsHovered(true)}
              />
            </>
          )}
        </>
      ) : (
        <>
          <path d={routing.fullPath} fill="none" style={baseStrokeStyle} onMouseEnter={() => setIsHovered(true)} />
          {isHighlighted && (
            <path
              d={routing.fullPath}
              fill="none"
              className="ref-edge-flow-path"
              style={animatedStrokeStyle}
              onMouseEnter={() => setIsHovered(true)}
            />
          )}
        </>
      )}
      <EdgeArrowhead
        points={routing.drawnPoints}
        color={strokeColor}
        opacity={strokeOpacity}
        scale={zoomCompensation}
      />
      {/* Generous invisible fat stroke (24px) carrying all pointer & hover interactions.
          No `cursor: pointer` here on purpose: at 24px wide, this hit area crosses large
          swaths of empty-looking canvas on any schema with more than a handful of refs —
          the cursor would flip to "clickable" constantly while just moving the mouse
          around, with nothing to click there most of the time (a waypoint insert is an
          edit-mode edge case, not the default expectation). Hover/select still work
          exactly as before; only the misleading cursor swap is gone. */}
      <path
        d={routing.fullPath}
        fill="none"
        stroke="rgba(0, 0, 0, 0.001)"
        strokeWidth={24 * zoomCompensation}
        strokeLinecap="round"
        className="react-flow__edge-interaction"
        style={{ pointerEvents: "stroke" }}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => {
          setIsHovered(false);
          routing.handlePathMouseLeave();
        }}
        onMouseMove={routing.handlePathMouseMove}
        onClick={(e) => {
          if (routing.candidatePoint) {
            e.stopPropagation();
            routing.insertPointAt(routing.candidatePoint);
          } else {
            data?.onSelectEdge?.(id);
          }
        }}
        onDoubleClick={routing.handlePathDoubleClick}
        onContextMenu={(event) => routing.openContextMenu(event)}
      />
      <EdgeLabelRenderer>
        {isHighlighted && (
          <EdgeCardinalityLabels
            points={routing.drawnPoints}
            sourceLabel={sourceCardinality}
            targetLabel={targetCardinality}
            sourceSlot={data?.sourceSlot ?? 0}
            targetSlot={data?.targetSlot ?? 0}
            color={strokeColor}
            opacity={selected ? 1 : 0.95}
            zoom={zoom}
          />
        )}
        {showEditingControls && (
          <EdgeWaypoints
            points={routing.points}
            source={{ x: sourceX, y: sourceY }}
            target={{ x: targetX, y: targetY }}
            selectedIndex={routing.selectedPointIndex}
            candidatePoint={routing.candidatePoint}
            strokeColor={strokeColor}
            zoom={zoom}
            onStartDrag={routing.startDrag}
            onSelect={routing.setSelectedPointIndex}
            onContextMenu={routing.openContextMenu}
            onInsertCandidate={routing.insertPointAt}
          />
        )}
        {showEditingControls && data && (
          <CardinalityBadge
            x={labelX}
            y={labelY}
            label={style.label}
            cardinality={data.cardinality}
            onCardinalityChange={data.onCardinalityChange}
            color={strokeColor}
            zoom={zoom}
            palette={data.palette}
            onPaletteChange={data.onPaletteChange}
            onColorChange={data.onColorChange}
            showReset={routing.hasCustomRouting || routing.points.length !== routing.defaultCorners.length}
            onReset={routing.resetRouting}
            onDeleteRef={data.onDeleteRef}
            onContextMenu={(event) => routing.openContextMenu(event)}
          />
        )}
        {routing.contextMenu && (
          <EdgeContextMenu
            menu={routing.contextMenu}
            onClose={routing.closeContextMenu}
            onInsertPoint={routing.insertPointAt}
            onDeletePoint={routing.deletePointAt}
            onResetRouting={routing.resetRouting}
            onResetColor={data?.color ? () => data.onColorChange(undefined) : undefined}
            onDeleteRef={data?.onDeleteRef}
          />
        )}
      </EdgeLabelRenderer>
    </>
  );
}

/**
 * A schema can have a few hundred of these on screen — without `memo`,
 * `useCanvasEdges` rebuilding its array (any hover, any selection change,
 * any drag frame) re-rendered every edge, not just the ones whose own props
 * actually changed.
 */
export const RefEdge = memo(RefEdgeImpl);

// apps/web/src/features/editor/edges/RefEdge.svelte
<script lang="ts" module>
  /** Colour of a relation nobody is looking at — deliberately low-contrast so a dense schema reads as structure rather than spaghetti. */
  const DIMMED_STROKE = "#475569";
  /** A ref with a validation issue draws in this colour at all times (not just on hover/selection) — it's the one thing on the canvas that should stay visible even in a dense, otherwise-dimmed schema. */
  const ISSUE_STROKE = "#f59e0b";
  /** Arrowhead size in screen pixels, before the zoom counter-scale. */
  const ARROW_LENGTH = 9;
  const ARROW_HALF_WIDTH = 5;
</script>

<script lang="ts">
  import type { EdgeProps } from "@xyflow/svelte";
  import { polylinePath, splitPolylineAtMidpoint } from "@/features/editor/edges/pathMath";
  import { useEdgeRouting } from "@/features/editor/edges/edgeRouting.svelte";
  import { CARDINALITY_STYLE, type RefEdgeType } from "@/features/editor/edges/refEdgeTypes";
  import { getCanvasContext } from "@/features/editor/canvas/canvasContext";
  import { ENDPOINT_CARDINALITY } from "./EdgeCardinalityLabels.svelte";
  import RefEdgeOverlay from "./RefEdgeOverlay.svelte";

  /**
   * One relation on the canvas: a dimmed baseline stroke, an animated dashed
   * overlay while highlighted, a hand-drawn arrowhead, a fat invisible hit
   * stroke, and — only while it has something to show — the cardinality
   * chips, waypoint dots, midpoint toolbar and context menu in the flow's
   * edge-label layer.
   *
   * A schema can have a few hundred (or few thousand) of these. No memo
   * comparator is needed: the edge overlay in `canvasEdges` hands back the
   * same `data` object for every ref whose highlight didn't change, and a
   * Svelte component only re-evaluates the expressions reading what did.
   */
  let {
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    data,
    selected = false,
  }: EdgeProps<RefEdgeType> = $props();

  const canvas = getCanvasContext();
  let isHovered = $state(false);

  const cardinality = $derived(data?.cardinality ?? "one-to-many");
  const style = $derived(CARDINALITY_STYLE[cardinality]);
  const isManyToMany = $derived(cardinality === "many-to-many");

  const routing = useEdgeRouting({
    edgeId: () => id,
    sourceX: () => sourceX,
    sourceY: () => sourceY,
    targetX: () => targetX,
    targetY: () => targetY,
    sourcePosition: () => sourcePosition,
    targetPosition: () => targetPosition,
    routingPoints: () => data?.routingPoints,
    onRoutingPointsChange: (points) => data?.onRoutingPointsChange(points),
  });

  // Pure geometry, so it costs nothing for the edges that never use it and
  // never lands a frame behind the line the way measuring the rendered
  // `<path>` did.
  const split = $derived(splitPolylineAtMidpoint(routing.drawnPoints));
  const labelX = $derived(split?.mid.x ?? routing.stepLabelX);
  const labelY = $derived(split?.mid.y ?? routing.stepLabelY);

  const isHighlighted = $derived(Boolean(data?.highlightLinks || data?.connectedHighlight || selected || isHovered));
  const hasIssue = $derived(Boolean(data?.hasIssue));
  const strokeColor = $derived(hasIssue ? ISSUE_STROKE : isHighlighted ? (data?.color ?? style.stroke) : DIMMED_STROKE);
  // Path coordinates live in flow space, which the viewport scales down via a
  // CSS transform as the user zooms out — so a fixed stroke-width/dasharray
  // shrinks to sub-pixel and disappears at low zoom. Dividing by zoom here
  // pre-compensates in flow units so the *rendered* size on screen stays
  // constant regardless of zoom level.
  const zoom = $derived(canvas.zoom);
  const zoomCompensation = $derived(1 / Math.max(zoom, 0.01));
  const strokeWidth = $derived((selected ? 2.5 : isHighlighted ? 2 : 1.5) * zoomCompensation);
  const strokeOpacity = $derived(selected ? 1 : isHighlighted ? 0.95 : hasIssue ? 0.85 : 0.45);

  // Rectangular dashes (dbdiagram style) with clean, well-spaced flow:
  // 8px dash, 10px gap in screen pixels (compensated for zoom)
  const dash = $derived(8 * zoomCompensation);
  const gap = $derived(10 * zoomCompensation);
  const period = $derived(-(dash + gap));
  const flowAnimation = $derived(isHighlighted ? `ref-edge-flow ${selected ? 0.6 : 0.9}s linear infinite` : "none");

  const baseStrokeStyle = $derived(
    `stroke: ${strokeColor}; stroke-width: ${1.5 * zoomCompensation}; opacity: ${isHighlighted ? 0.3 : strokeOpacity}; stroke-linecap: round;`,
  );
  const animatedStrokeStyle = $derived(
    `stroke: ${strokeColor}; stroke-width: ${strokeWidth}; opacity: ${strokeOpacity}; stroke-dasharray: ${dash} ${gap}; stroke-linecap: butt; animation: ${flowAnimation}; --dash-period: ${period}px;`,
  );

  /**
   * Arrowhead drawn as part of the edge instead of an SVG `marker-end`.
   *
   * A marker is defined once, up front, with a fixed colour, and the flow
   * sizes it in `strokeWidth` units — so it stayed the relation's bright
   * colour on a dimmed line and doubled in size the moment the edge was
   * selected. Drawing it here keeps colour, opacity and size in step with the
   * stroke it belongs to.
   */
  const arrow = $derived.by(() => {
    const points = routing.drawnPoints;
    if (points.length < 2) return null;
    const tip = points[points.length - 1];
    const previous = points[points.length - 2];
    if (tip.x === previous.x && tip.y === previous.y) return null;
    const angle = (Math.atan2(tip.y - previous.y, tip.x - previous.x) * 180) / Math.PI;
    const length = ARROW_LENGTH * zoomCompensation;
    const halfWidth = ARROW_HALF_WIDTH * zoomCompensation;
    return {
      points: `0,0 ${-length},${-halfWidth} ${-length},${halfWidth}`,
      transform: `translate(${tip.x} ${tip.y}) rotate(${angle})`,
    };
  });

  // Editing controls show while the edge is selected or hovered.
  // `routing.isDraggingPoint` keeps this true even if hover flickers off
  // mid-drag — the waypoint dot is portaled elsewhere in the DOM (not a
  // descendant of the edge's own hit-stroke), so the moment the cursor
  // crosses onto the dot itself the browser fires `mouseleave` on the stroke
  // underneath.
  const showEditingControls = $derived(Boolean(selected || isHovered || routing.isDraggingPoint));
  const endpointLabels = $derived(ENDPOINT_CARDINALITY[cardinality]);

  const hover = () => (isHovered = true);
</script>

{#if isManyToMany && split}
  <!-- Split in two so each half animates on its own; both halves still run
       source → target, which is what keeps the dash flow and the arrowhead
       pointing the same way as every other cardinality. -->
  <path d={polylinePath(split.first)} fill="none" style={baseStrokeStyle} role="presentation" onmouseenter={hover} />
  <path d={polylinePath(split.second)} fill="none" style={baseStrokeStyle} role="presentation" onmouseenter={hover} />
  {#if isHighlighted}
    <path
      d={polylinePath(split.first)}
      fill="none"
      class="ref-edge-flow-path"
      style={animatedStrokeStyle}
      role="presentation"
      onmouseenter={hover}
    />
    <path
      d={polylinePath(split.second)}
      fill="none"
      class="ref-edge-flow-path"
      style={animatedStrokeStyle}
      role="presentation"
      onmouseenter={hover}
    />
  {/if}
{:else}
  <path d={routing.fullPath} fill="none" style={baseStrokeStyle} role="presentation" onmouseenter={hover} />
  {#if isHighlighted}
    <path
      d={routing.fullPath}
      fill="none"
      class="ref-edge-flow-path"
      style={animatedStrokeStyle}
      role="presentation"
      onmouseenter={hover}
    />
  {/if}
{/if}
{#if arrow}
  <polygon
    points={arrow.points}
    fill={strokeColor}
    opacity={strokeOpacity}
    transform={arrow.transform}
    style="pointer-events: none"
  />
{/if}
<!-- Generous invisible fat stroke (24px) carrying all pointer & hover
     interactions. No `cursor: pointer` here on purpose: at 24px wide, this hit
     area crosses large swaths of empty-looking canvas on any schema with more
     than a handful of refs — the cursor would flip to "clickable" constantly
     while just moving the mouse around, with nothing to click there most of
     the time. -->
<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
<path
  d={routing.fullPath}
  fill="none"
  stroke="rgba(0, 0, 0, 0.001)"
  stroke-width={24 * zoomCompensation}
  stroke-linecap="round"
  class="svelte-flow__edge-interaction"
  style="pointer-events: stroke"
  onmouseenter={hover}
  onmouseleave={() => {
    isHovered = false;
    routing.handlePathMouseLeave();
  }}
  onmousemove={routing.handlePathMouseMove}
  onclick={(e) => {
    // Selection is ours alone (`selectedEdgeId` in `ProjectEditor`, fed back
    // in through the one-way `edges` prop) — never Svelte Flow's own
    // click-to-select. Left to bubble, this click also reaches the flow's
    // own `<g>` wrapper (which runs its own, entirely redundant
    // `handleEdgeSelection`) and then the pane's own click handler, which
    // unconditionally deselects everything (`store.unselectNodesAndEdges()`,
    // with no `event.target` check) — racing our reactive update and
    // sometimes winning, which is what let a relation stay highlighted (or
    // fail to re-highlight) after this same click should have settled it.
    e.stopPropagation();
    const candidate = routing.candidatePoint;
    if (candidate) {
      routing.insertPointAt(candidate);
    } else {
      data?.onSelectEdge?.(id);
    }
  }}
  ondblclick={routing.handlePathDoubleClick}
  oncontextmenu={(event) => routing.openContextMenu(event)}
>
  {#if hasIssue && data?.issueMessages}<title>{data.issueMessages.join("\n")}</title>{/if}
</path>
<!-- Mounted only when it would hold something: an idle relation keeps no
     portal (and no subscription) alive for an empty subtree, several hundred
     times over on a large schema.

     A separate component rather than an inline `<div use:portal>` here — see
     `RefEdgeOverlay.svelte`'s own header comment for why: a literal HTML tag
     at this level pushed the whole shared template (including the SVG
     `<path>`s above) into the HTML namespace. -->
{#if isHighlighted || showEditingControls || routing.contextMenu}
  <RefEdgeOverlay
    {sourceX}
    {sourceY}
    {targetX}
    {targetY}
    {labelX}
    {labelY}
    {selected}
    {zoom}
    {strokeColor}
    {style}
    {data}
    {routing}
    {isHighlighted}
    {showEditingControls}
    {endpointLabels}
  />
{/if}
