// apps/web/src/features/projects/components/DeleteProjectModal.svelte
<script lang="ts">
  import Modal from "@/components/overlays/Modal.svelte";
  import Button from "@/components/ui/Button.svelte";
  import ErrorText from "@/components/ui/ErrorText.svelte";
  import Hint from "@/components/ui/Hint.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import type { ProjectSummary } from "@/types";

  /** Confirms permanently deleting one trashed project (and its revision history). */
  let {
    target,
    busy,
    error,
    onConfirm,
    onClose,
  }: {
    target: ProjectSummary;
    busy: boolean;
    error: string | null;
    onConfirm: () => void;
    onClose: () => void;
  } = $props();

  const { t } = useTranslation();
</script>

<Modal title={t("projects.deleteForever.title")} {onClose}>
  <Hint>{t("projects.deleteForever.confirmation", { name: target.name })}</Hint>
  <div class="flex justify-end gap-2">
    <Button onclick={onClose} disabled={busy}>{t("common.cancel")}</Button>
    <Button variant="danger" onclick={onConfirm} disabled={busy}>
      {busy ? t("common.deleting") : t("projects.deleteForever.action")}
    </Button>
  </div>
  {#if error}<ErrorText>{error}</ErrorText>{/if}
</Modal>

// apps/web/src/projectList/DeleteProjectModal.tsx
import { Modal } from "../Modal.js";
import { Button } from "../ui/Button.js";
import { ErrorText, Hint } from "../ui/Alert.js";
import type { ProjectSummary } from "../types.js";

/** Confirms permanently deleting one trashed project (and its revision history). */
export function DeleteProjectModal(props: {
  target: ProjectSummary;
  busy: boolean;
  error: string | null;
  onConfirm: () => void;
  onClose: () => void;
}) {
  return (
    <Modal title="Delete project forever" onClose={props.onClose}>
      <Hint>
        Permanently delete <strong>{props.target.name}</strong>? This removes its whole revision history too, and
        can't be undone.
      </Hint>
      <div className="flex justify-end gap-2">
        <Button onClick={props.onClose} disabled={props.busy}>
          Cancel
        </Button>
        <Button variant="danger" onClick={props.onConfirm} disabled={props.busy}>
          {props.busy ? "Deleting…" : "Delete forever"}
        </Button>
      </div>
      {props.error && <ErrorText>{props.error}</ErrorText>}
    </Modal>
  );
}
