// apps/web/src/features/projects/components/ProjectCard.svelte
<script lang="ts" module>
  const ACCENTS = ["#6366f1", "#a855f7", "#06b6d4", "#10b981", "#f59e0b", "#ec4899"];
</script>

<script lang="ts">
  import { MAX_NAME_LENGTH } from "@athanordb/shared";
  import { autofocus } from "@/actions/autofocus";
  import Icon from "@/components/icons/Icon.svelte";
  import { ArchiveIcon, PencilIcon, RestoreIcon, TrashIcon, UsersIcon } from "@/components/icons/Icons";
  import Button from "@/components/ui/Button.svelte";
  import Badge from "@/components/ui/Badge.svelte";
  import { INPUT_SM_CLASS } from "@/components/ui/inputStyles";
  import { formatDate } from "@/i18n/formatters";
  import { i18n, useTranslation } from "@/i18n/i18n.svelte";
  import type { ProjectStatus, ProjectSummary } from "@/types";
  import ProjectThumbnail, { hashOfId } from "./ProjectThumbnail.svelte";

  /** One project tile: open-on-click, plus the per-section actions admins get. */
  let {
    project,
    section,
    openable,
    isRenaming,
    nameDraft,
    onNameDraftChange,
    onOpen,
    onStartRename,
    onCommitRename,
    onCancelRename,
    onSetStatus,
    onDeleteForever,
    onManageTeams,
  }: {
    project: ProjectSummary;
    section: ProjectStatus;
    openable: boolean;
    isRenaming: boolean;
    nameDraft: string;
    onNameDraftChange: (value: string) => void;
    onOpen: () => void;
    onStartRename: () => void;
    onCommitRename: () => void;
    onCancelRename: () => void;
    onSetStatus: (status: ProjectStatus) => void;
    onDeleteForever: () => void;
    onManageTeams: () => void;
  } = $props();

  const { t } = useTranslation();
  const accent = $derived(ACCENTS[hashOfId(project.id) % ACCENTS.length]);

  /** Every action button sits inside the clickable card, so none of them may also open the project. */
  function action(run: () => void) {
    return (event: MouseEvent) => {
      event.stopPropagation();
      run();
    };
  }
</script>

<!-- `role` is "button" whenever `tabindex` is set; the checker cannot see that through the conditional. -->
<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
  class={`group block w-full overflow-hidden rounded-xl border border-border bg-surface text-left shadow-xs transition-[box-shadow,transform,border-color] duration-150 ${
    openable ? "cursor-pointer hover:-translate-y-0.5 hover:border-border-strong hover:shadow-md" : "cursor-default"
  }`}
  role={openable ? "button" : undefined}
  tabindex={openable ? 0 : undefined}
  onclick={() => openable && !isRenaming && onOpen()}
  onkeydown={(event) => {
    if (!openable || isRenaming) return;
    // The card holds buttons and a rename field inside it. Without this
    // guard, Enter or Space on any of them bubbled up here and opened the
    // project as well — so archiving a project from the keyboard also
    // navigated into it. The check has to come before `preventDefault`,
    // or Space on a nested button gets swallowed instead.
    if (event.target !== event.currentTarget) return;
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      onOpen();
    }
  }}
>
  <ProjectThumbnail id={project.id} {accent} />

  <div class="p-3">
    <div class="flex items-start justify-between gap-2">
      {#if isRenaming}
        <input
          use:autofocus
          class={`${INPUT_SM_CLASS} mb-0.5 w-full font-semibold`}
          value={nameDraft}
          maxlength={MAX_NAME_LENGTH}
          onclick={(event) => event.stopPropagation()}
          oninput={(event) => onNameDraftChange(event.currentTarget.value)}
          onblur={onCommitRename}
          onkeydown={(event) => {
            if (event.key === "Enter") onCommitRename();
            if (event.key === "Escape") {
              event.stopPropagation();
              onCancelRename();
            }
          }}
        />
      {:else}
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="mb-0.5 overflow-hidden text-ellipsis whitespace-nowrap text-sm font-semibold text-text"
          data-tooltip={openable ? t("projects.card.doubleClickToRename") : undefined}
          ondblclick={(event) => {
            if (!openable) return;
            event.stopPropagation();
            onStartRename();
          }}
        >
          {project.name}
        </div>
      {/if}

      <!-- Server re-checks every mutating call regardless — this is UX only, never the security boundary. -->
      {#if project.permission === "administrator"}
        <div
          class="flex shrink-0 gap-0.5 opacity-0 transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100"
        >
          {#if section === "trashed"}
            <Button
              variant="ghost"
              size="icon-sm"
              data-tooltip={t("projects.card.restore")}
              onclick={action(() => onSetStatus("active"))}
            >
              <Icon icon={RestoreIcon} size={13} />
            </Button>
            <Button
              variant="ghost"
              size="icon-sm"
              data-tooltip={t("projects.deleteForever.action")}
              onclick={action(onDeleteForever)}
            >
              <Icon icon={TrashIcon} size={13} />
            </Button>
          {:else}
            <Button variant="ghost" size="icon-sm" data-tooltip={t("common.rename")} onclick={action(onStartRename)}>
              <Icon icon={PencilIcon} size={13} />
            </Button>
            <Button
              variant="ghost"
              size="icon-sm"
              data-tooltip={t("projects.card.manageTeams")}
              onclick={action(onManageTeams)}
            >
              <Icon icon={UsersIcon} size={13} />
            </Button>
            {#if section === "archived"}
              <Button
                variant="ghost"
                size="icon-sm"
                data-tooltip={t("projects.card.restore")}
                onclick={action(() => onSetStatus("active"))}
              >
                <Icon icon={RestoreIcon} size={13} />
              </Button>
            {:else}
              <Button
                variant="ghost"
                size="icon-sm"
                data-tooltip={t("projects.card.archive")}
                onclick={action(() => onSetStatus("archived"))}
              >
                <Icon icon={ArchiveIcon} size={13} />
              </Button>
            {/if}
            <Button
              variant="ghost"
              size="icon-sm"
              data-tooltip={t("projects.card.moveToTrash")}
              onclick={action(() => onSetStatus("trashed"))}
            >
              <Icon icon={TrashIcon} size={13} />
            </Button>
          {/if}
        </div>
      {/if}
    </div>

    <div class="flex items-center gap-1.5 text-[11px] text-text-muted">
      <span class="h-1.5 w-1.5 shrink-0 rounded-full" style:background={accent}></span>
      {t("projects.card.createdOn", { date: formatDate(project.created_at, i18n.locale) })}
      {#if project.permission === "view"}
        <Badge tone="muted" class="ml-1">{t("projects.card.readOnly")}</Badge>
      {/if}
    </div>
  </div>
</div>

// apps/web/src/projectList/ProjectCard.tsx
import { MAX_NAME_LENGTH } from "@athanordb/shared";
import { ArchiveIcon, FolderIcon, PencilIcon, RestoreIcon, TrashIcon, UsersIcon } from "../Icons.js";
import { Button } from "../ui/Button.js";
import { Badge } from "../ui/Badge.js";
import { INPUT_SM_CLASS } from "../ui/inputStyles.js";
import type { ProjectStatus, ProjectSummary } from "../types.js";

/** One project tile: open-on-click, plus the per-section action buttons (rename/teams/archive/restore/trash/delete) admins get. */
export function ProjectCard(props: {
  project: ProjectSummary;
  section: ProjectStatus;
  openable: boolean;
  isRenaming: boolean;
  nameDraft: string;
  onNameDraftChange: (v: string) => void;
  onOpen: () => void;
  onStartRename: () => void;
  onCommitRename: () => void;
  onCancelRename: () => void;
  onSetStatus: (status: ProjectStatus) => void;
  onDeleteForever: () => void;
  onManageTeams: () => void;
}) {
  const { project: p, section, openable, isRenaming } = props;

  return (
    <div
      className={`group block w-full rounded-md border border-border bg-surface p-4 text-left shadow-xs transition-[box-shadow,transform,border-color] duration-150 ${
        openable ? "cursor-pointer hover:-translate-y-px hover:border-border-strong hover:shadow-md" : "cursor-default"
      }`}
      role={openable ? "button" : undefined}
      tabIndex={openable ? 0 : undefined}
      onClick={() => openable && !isRenaming && props.onOpen()}
      onKeyDown={(e) => {
        if (!openable || isRenaming) return;
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          props.onOpen();
        }
      }}
    >
      <div className="flex items-start justify-between">
        <span className="mb-2.5 flex h-[34px] w-[34px] items-center justify-center rounded-sm bg-primary-light text-primary">
          <FolderIcon size={17} />
        </span>
        {/* Server re-checks every mutating call regardless — this is UX only, never the security boundary. */}
        {p.permission === "administrator" && (
          <div className="flex gap-0.5 opacity-0 transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100">
            {section === "trashed" ? (
              <>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  data-tooltip="Restore to projects"
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onSetStatus("active");
                  }}
                >
                  <RestoreIcon size={13} />
                </Button>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  data-tooltip="Delete forever"
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onDeleteForever();
                  }}
                >
                  <TrashIcon size={13} />
                </Button>
              </>
            ) : (
              <>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  data-tooltip="Rename project"
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onStartRename();
                  }}
                >
                  <PencilIcon size={13} />
                </Button>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  data-tooltip="Manage teams"
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onManageTeams();
                  }}
                >
                  <UsersIcon size={13} />
                </Button>
                {section === "archived" ? (
                  <Button
                    variant="ghost"
                  size="icon-sm"
                    data-tooltip="Restore to projects"
                    onClick={(e) => {
                      e.stopPropagation();
                      props.onSetStatus("active");
                    }}
                  >
                    <RestoreIcon size={13} />
                  </Button>
                ) : (
                  <Button
                    variant="ghost"
                  size="icon-sm"
                    data-tooltip="Archive project"
                    onClick={(e) => {
                      e.stopPropagation();
                      props.onSetStatus("archived");
                    }}
                  >
                    <ArchiveIcon size={13} />
                  </Button>
                )}
                <Button
                  variant="ghost"
                  size="icon-sm"
                  data-tooltip="Move to trash"
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onSetStatus("trashed");
                  }}
                >
                  <TrashIcon size={13} />
                </Button>
              </>
            )}
          </div>
        )}
      </div>
      {isRenaming ? (
        <input
          autoFocus
          className={`${INPUT_SM_CLASS} mb-0.5 w-full font-semibold`}
          value={props.nameDraft}
          maxLength={MAX_NAME_LENGTH}
          onClick={(e) => e.stopPropagation()}
          onChange={(e) => props.onNameDraftChange(e.target.value)}
          onBlur={props.onCommitRename}
          onKeyDown={(e) => {
            if (e.key === "Enter") props.onCommitRename();
            if (e.key === "Escape") {
              e.stopPropagation();
              props.onCancelRename();
            }
          }}
        />
      ) : (
        <div
          className="mb-0.5 overflow-hidden text-ellipsis whitespace-nowrap text-sm font-semibold text-text"
          data-tooltip={openable ? "Double-click to rename" : undefined}
          onDoubleClick={(e) => {
            if (!openable) return;
            e.stopPropagation();
            props.onStartRename();
          }}
        >
          {p.name}
        </div>
      )}
      <div className="text-xs text-text-muted">
        {p.created_at}
        {p.permission === "view" && <Badge tone="muted" className="ml-2">View only</Badge>}
      </div>
    </div>
  );
}
