// apps/web/src/features/editor/nodes/EnumNode.tsx
import { memo, useState } from "react";
import type { Node, NodeProps } from "@xyflow/react";
import { MAX_NAME_LENGTH, type EnumDef, type EnumValue } from "@athanordb/shared";
import { TagIcon, PlusIcon, TrashIcon } from "@/components/icons/Icons";
import { INPUT_XS_CLASS } from "@/components/ui/inputStyles";
import { useDraftValue } from "@/hooks/useDraftValue";
import { useTranslation } from "@/i18n/useTranslation";

export interface EnumNodeData {
  enumDef: EnumDef;
  onRename: (name: string) => void;
  onAddValue: () => void;
  onRenameValue: (valueId: string, name: string) => void;
  onDeleteValue: (valueId: string) => void;
  onReorderValue: (valueId: string, direction: "up" | "down") => void;
  [key: string]: unknown;
}

export type EnumNodeType = Node<EnumNodeData, "enum">;

const ACCENT = "#06b6d4"; // accent-cyan — distinct from tables (primary) and zones (amber)

function EnumValueRow(props: {
  value: EnumValue;
  isFirst: boolean;
  isLast: boolean;
  onRename: (name: string) => void;
  onDelete: () => void;
  onMove: (direction: "up" | "down") => void;
}) {
  const { t } = useTranslation();
  const [editing, setEditing] = useState(false);
  const draft = useDraftValue(props.value.name, (next) => props.onRename(next ?? ""));

  return (
    <div className="group/row flex items-center gap-1 px-2.5 py-1 hover:bg-surface-hover/60">
      <div className="flex shrink-0 flex-col opacity-0 group-hover/row:opacity-100">
        <button
          type="button"
          className="nodrag h-2.5 w-3.5 text-[9px] leading-none text-text-muted hover:text-text disabled:opacity-20"
          disabled={props.isFirst}
          onClick={() => props.onMove("up")}
          data-tooltip={t("enum.moveUp")}
        >
          ▲
        </button>
        <button
          type="button"
          className="nodrag h-2.5 w-3.5 text-[9px] leading-none text-text-muted hover:text-text disabled:opacity-20"
          disabled={props.isLast}
          onClick={() => props.onMove("down")}
          data-tooltip={t("enum.moveDown")}
        >
          ▼
        </button>
      </div>

      {editing ? (
        <input
          autoFocus
          className={`nodrag ${INPUT_XS_CLASS} flex-1 font-mono text-[calc(11.5px_*_var(--canvas-font-scale))]`}
          value={draft.value}
          maxLength={MAX_NAME_LENGTH}
          onChange={(event) => draft.setValue(event.target.value)}
          onBlur={() => {
            draft.commit();
            setEditing(false);
          }}
          onKeyDown={(event) => {
            draft.handleKeyDown(event);
            if (event.key === "Enter") setEditing(false);
            if (event.key === "Escape") {
              draft.setValue(props.value.name);
              setEditing(false);
            }
          }}
        />
      ) : (
        <span
          className="flex-1 truncate font-mono text-[calc(11.5px_*_var(--canvas-font-scale))] text-text-secondary"
          onDoubleClick={() => setEditing(true)}
          data-tooltip={t("node.doubleClickToRename")}
        >
          {props.value.name}
        </span>
      )}

      <button
        type="button"
        className="nodrag shrink-0 text-text-muted opacity-0 hover:text-danger group-hover/row:opacity-100"
        onClick={props.onDelete}
        data-tooltip={t("enum.deleteValue")}
      >
        <TrashIcon size={11} />
      </button>
    </div>
  );
}

function EnumNodeImpl({ data, selected }: NodeProps<EnumNodeType>) {
  const { t } = useTranslation();
  const { enumDef } = data;
  const [editingName, setEditingName] = useState(false);
  const nameDraft = useDraftValue(enumDef.name, (next) => data.onRename(next ?? ""));

  return (
    <div
      className={`w-[200px] overflow-hidden rounded-lg border bg-surface shadow-md transition-shadow ${
        selected ? "shadow-lg" : ""
      }`}
      style={{ borderColor: selected ? ACCENT : "var(--color-border)" }}
    >
      <div
        className="flex items-center gap-1.5 px-2.5 py-1.5"
        style={{ background: `${ACCENT}22`, borderBottom: `1px solid ${ACCENT}55` }}
        onDoubleClick={() => setEditingName(true)}
      >
        <TagIcon size={12} style={{ color: ACCENT }} />
        {editingName ? (
          <input
            autoFocus
            className={`nodrag ${INPUT_XS_CLASS} flex-1 font-bold text-[calc(12px_*_var(--canvas-font-scale))]`}
            value={nameDraft.value}
            maxLength={MAX_NAME_LENGTH}
            onChange={(event) => nameDraft.setValue(event.target.value)}
            onBlur={() => {
              nameDraft.commit();
              setEditingName(false);
            }}
            onKeyDown={(event) => {
              nameDraft.handleKeyDown(event);
              if (event.key === "Enter") setEditingName(false);
              if (event.key === "Escape") {
                nameDraft.setValue(enumDef.name);
                setEditingName(false);
              }
            }}
          />
        ) : (
          <span
            className="flex-1 truncate font-bold text-[calc(12px_*_var(--canvas-font-scale))]"
            style={{ color: ACCENT }}
            data-tooltip={t("node.doubleClickToRename")}
          >
            {enumDef.name}
          </span>
        )}
      </div>

      <div className="divide-y divide-border/60 py-0.5">
        {enumDef.values.length === 0 && (
          <div className="px-2.5 py-1.5 text-[calc(11px_*_var(--canvas-font-scale))] italic text-text-muted">{t("enum.empty")}</div>
        )}
        {enumDef.values.map((v, i) => (
          <EnumValueRow
            key={v.id}
            value={v}
            isFirst={i === 0}
            isLast={i === enumDef.values.length - 1}
            onRename={(name) => data.onRenameValue(v.id, name)}
            onDelete={() => data.onDeleteValue(v.id)}
            onMove={(direction) => data.onReorderValue(v.id, direction)}
          />
        ))}
      </div>

      <button
        type="button"
        className="nodrag flex w-full items-center gap-1.5 border-t border-border/60 px-2.5 py-1.5 text-[calc(11px_*_var(--canvas-font-scale))] text-text-muted hover:bg-surface-hover hover:text-text"
        onClick={data.onAddValue}
      >
        <PlusIcon size={11} /> {t("enum.addValue")}
      </button>
    </div>
  );
}

export const EnumNode = memo(EnumNodeImpl);

// apps/web/src/features/editor/nodes/EnumNode.svelte
<script lang="ts" module>
  const ACCENT = "#06b6d4"; // accent-cyan — distinct from tables (primary) and zones (amber)
</script>

<script lang="ts">
  import type { NodeProps } from "@xyflow/svelte";
  import { MAX_NAME_LENGTH } from "@athanordb/shared";
  import { autofocus } from "@/actions/autofocus";
  import Icon from "@/components/icons/Icon.svelte";
  import { PlusIcon, TagIcon } from "@/components/icons/Icons";
  import { INPUT_XS_CLASS } from "@/components/ui/inputStyles";
  import type { EnumNodeType } from "@/features/editor/nodes/nodeTypes";
  import { useDraftValue } from "@/hooks/draftValue.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import EnumValueRow from "./EnumValueRow.svelte";

  let { data, selected = false }: NodeProps<EnumNodeType> = $props();

  const { t } = useTranslation();
  const enumDef = $derived(data.enumDef);
  const readOnly = $derived(Boolean(data.readOnly));
  let editingName = $state(false);
  const nameDraft = useDraftValue(
    () => data.enumDef.name,
    (next) => data.onRename(next ?? ""),
  );
</script>

<div
  class={`w-[200px] overflow-hidden rounded-lg border bg-surface shadow-md transition-shadow ${selected ? "shadow-lg" : ""}`}
  style:border-color={selected ? ACCENT : "var(--color-border)"}
>
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="flex items-center gap-1.5 px-2.5 py-1.5"
    style:background="{ACCENT}22"
    style:border-bottom="1px solid {ACCENT}55"
    ondblclick={() => {
      if (!readOnly) editingName = true;
    }}
  >
    <Icon icon={TagIcon} size={12} style="color: {ACCENT}" />
    {#if editingName}
      <input
        use:autofocus
        class={`nodrag ${INPUT_XS_CLASS} flex-1 font-bold text-[calc(12px_*_var(--canvas-font-scale))]`}
        bind:value={nameDraft.value}
        maxlength={MAX_NAME_LENGTH}
        onblur={() => {
          nameDraft.commit();
          editingName = false;
        }}
        onkeydown={(event) => {
          nameDraft.handleKeyDown(event);
          if (event.key === "Enter") editingName = false;
          if (event.key === "Escape") {
            nameDraft.setValue(enumDef.name);
            editingName = false;
          }
        }}
      />
    {:else}
      <span
        class="flex-1 truncate font-bold text-[calc(12px_*_var(--canvas-font-scale))]"
        style:color={ACCENT}
        data-tooltip={readOnly ? undefined : t("node.doubleClickToRename")}
      >
        {enumDef.name}
      </span>
    {/if}
  </div>

  <div class="divide-y divide-border/60 py-0.5">
    {#if enumDef.values.length === 0}
      <div class="px-2.5 py-1.5 text-[calc(11px_*_var(--canvas-font-scale))] italic text-text-muted">
        {t("enum.empty")}
      </div>
    {/if}
    {#each enumDef.values as v, i (v.id)}
      <EnumValueRow
        value={v}
        isFirst={i === 0}
        isLast={i === enumDef.values.length - 1}
        {readOnly}
        onRename={(name) => data.onRenameValue(v.id, name)}
        onDelete={() => data.onDeleteValue(v.id)}
        onMove={(direction) => data.onReorderValue(v.id, direction)}
      />
    {/each}
  </div>

  {#if !readOnly}
    <button
      type="button"
      class="nodrag flex w-full items-center gap-1.5 border-t border-border/60 px-2.5 py-1.5 text-[calc(11px_*_var(--canvas-font-scale))] text-text-muted transition-colors hover:bg-surface-hover hover:text-text"
      onclick={data.onAddValue}
    >
      <Icon icon={PlusIcon} size={11} />
      {t("enum.addValue")}
    </button>
  {/if}
</div>
