// apps/web/src/features/admin/TeamDetailView.svelte
<script lang="ts">
  import Modal from "@/components/overlays/Modal.svelte";
  import Icon from "@/components/icons/Icon.svelte";
  import { PlusIcon, TrashIcon } from "@/components/icons/Icons";
  import Button from "@/components/ui/Button.svelte";
  import ErrorText from "@/components/ui/ErrorText.svelte";
  import List from "@/components/ui/List.svelte";
  import ListMain from "@/components/ui/ListMain.svelte";
  import ListRow from "@/components/ui/ListRow.svelte";
  import EmptyState from "@/components/ui/EmptyState.svelte";
  import { SELECT_CLASS } from "@/components/ui/inputStyles";
  import { useAsyncAction } from "@/hooks/asyncAction.svelte";
  import { useAsyncResource } from "@/hooks/asyncResource.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { addTeamMember, fetchTeam, removeTeamMember } from "@/services/teamsApi";
  import { fetchUsers } from "@/services/usersApi";

  let { teamId, onClose, onChanged }: { teamId: string; onClose: () => void; onChanged: () => void } = $props();

  const { t } = useTranslation();
  const team = useAsyncResource(() => fetchTeam(teamId));
  const users = useAsyncResource(fetchUsers);
  let selectedUserId = $state("");

  function applyMembershipChange() {
    team.reload();
    onChanged();
  }

  const addMember = useAsyncAction(async () => {
    await addTeamMember(teamId, selectedUserId);
    selectedUserId = "";
    applyMembershipChange();
  });

  const removeMember = useAsyncAction(async (userId: string) => {
    await removeTeamMember(teamId, userId);
    applyMembershipChange();
  });

  const members = $derived(team.data?.members ?? []);
  const assignableUsers = $derived(
    (users.data ?? []).filter((user) => !members.some((member) => member.id === user.id)),
  );
  const error = $derived(team.error ?? addMember.error ?? removeMember.error);
</script>

<Modal title={team.data ? t("admin.teams.detailTitle", { name: team.data.name }) : t("admin.teams.one")} {onClose}>
  {#if error}<ErrorText>{error}</ErrorText>{/if}
  {#if team.data}
    <div class="mb-7 flex max-w-[420px] gap-2">
      <select class={`${SELECT_CLASS} flex-1`} bind:value={selectedUserId}>
        <option value="">{t("admin.teams.addMemberPlaceholder")}</option>
        {#each assignableUsers as user (user.id)}
          <option value={user.id}>{user.displayName} ({user.email})</option>
        {/each}
      </select>
      <Button variant="primary" onclick={() => void addMember.run()} disabled={!selectedUserId}>
        <Icon icon={PlusIcon} size={14} />
        {t("common.add")}
      </Button>
    </div>
    {#if members.length === 0}
      <EmptyState>{t("admin.teams.noMembers")}</EmptyState>
    {:else}
      <List>
        {#each members as member (member.id)}
          <ListRow>
            <ListMain>
              <span>{member.displayName}</span>
              <span class="text-text-muted">{member.email}</span>
            </ListMain>
            <Button
              variant="ghost"
              size="icon"
              data-tooltip={t("admin.teams.removeMember")}
              onclick={() => void removeMember.run(member.id)}
            >
              <Icon icon={TrashIcon} size={13} />
            </Button>
          </ListRow>
        {/each}
      </List>
    {/if}
  {/if}
</Modal>

// apps/web/src/admin/TeamDetailView.tsx
import { useEffect, useState } from "react";
import { Modal } from "../Modal.js";
import { PlusIcon, TrashIcon } from "../Icons.js";
import { Button } from "../ui/Button.js";
import { ErrorText } from "../ui/Alert.js";
import { List, ListMain, ListRow, EmptyState } from "../ui/List.js";
import { SELECT_CLASS } from "../ui/inputStyles.js";
import type { TeamDetail, UserSummary } from "../types.js";

export function TeamDetailView(props: { teamId: string; onClose: () => void; onChanged: () => void }) {
  const [team, setTeam] = useState<TeamDetail | null>(null);
  const [users, setUsers] = useState<UserSummary[]>([]);
  const [pickUserId, setPickUserId] = useState("");
  const [error, setError] = useState<string | null>(null);

  const refresh = () => {
    fetch(`/api/teams/${props.teamId}`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`load failed (${r.status})`))))
      .then(setTeam)
      .catch((err) => setError((err as Error).message));
  };

  useEffect(refresh, [props.teamId]);
  useEffect(() => {
    fetch("/api/users")
      .then((r) => (r.ok ? r.json() : []))
      .then(setUsers)
      .catch(() => {});
  }, []);

  const addMember = async () => {
    if (!pickUserId) return;
    await fetch(`/api/teams/${props.teamId}/members`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ userId: pickUserId }),
    });
    setPickUserId("");
    refresh();
    props.onChanged();
  };

  const removeMember = async (userId: string) => {
    await fetch(`/api/teams/${props.teamId}/members/${userId}`, { method: "DELETE" });
    refresh();
    props.onChanged();
  };

  const availableUsers = users.filter((u) => !team?.members.some((m) => m.id === u.id));

  return (
    <Modal title={team ? `Team: ${team.name}` : "Team"} onClose={props.onClose}>
      {error && <ErrorText>{error}</ErrorText>}
      {team && (
        <>
          <div className="mb-7 flex max-w-[420px] gap-2">
            <select className={`${SELECT_CLASS} flex-1`} value={pickUserId} onChange={(e) => setPickUserId(e.target.value)}>
              <option value="">Add a member…</option>
              {availableUsers.map((u) => (
                <option key={u.id} value={u.id}>
                  {u.displayName} ({u.email})
                </option>
              ))}
            </select>
            <Button variant="primary" onClick={addMember} disabled={!pickUserId}>
              <PlusIcon size={14} /> Add
            </Button>
          </div>
          {team.members.length === 0 ? (
            <EmptyState>No members yet.</EmptyState>
          ) : (
            <List>
              {team.members.map((m) => (
                <ListRow key={m.id}>
                  <ListMain>
                    <span>{m.displayName}</span>
                    <span className="text-text-muted">{m.email}</span>
                  </ListMain>
                  <Button variant="ghost" size="icon" data-tooltip="Remove from team" onClick={() => removeMember(m.id)}>
                    <TrashIcon size={13} />
                  </Button>
                </ListRow>
              ))}
            </List>
          )}
        </>
      )}
    </Modal>
  );
}
