// apps/web/src/features/admin/TeamsTab.svelte
<script lang="ts">
  import Icon from "@/components/icons/Icon.svelte";
  import { PlusIcon, TrashIcon, UsersIcon } from "@/components/icons/Icons";
  import Button from "@/components/ui/Button.svelte";
  import ErrorText from "@/components/ui/ErrorText.svelte";
  import List from "@/components/ui/List.svelte";
  import ListMain from "@/components/ui/ListMain.svelte";
  import ListRow from "@/components/ui/ListRow.svelte";
  import EmptyState from "@/components/ui/EmptyState.svelte";
  import { INPUT_CLASS } from "@/components/ui/inputStyles";
  import { useAsyncAction } from "@/hooks/asyncAction.svelte";
  import { useAsyncResource } from "@/hooks/asyncResource.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { createTeam, deleteTeam, fetchTeams } from "@/services/teamsApi";
  import TeamDetailView from "@/features/admin/TeamDetailView.svelte";

  const { t } = useTranslation();
  const teams = useAsyncResource(fetchTeams);
  let newTeamName = $state("");
  let selectedTeamId = $state<string | null>(null);

  const addTeam = useAsyncAction(async () => {
    await createTeam(newTeamName.trim());
    newTeamName = "";
    teams.reload();
  });

  const removeTeam = useAsyncAction(async (teamId: string) => {
    await deleteTeam(teamId);
    teams.reload();
  });

  function handleCreate() {
    if (newTeamName.trim()) void addTeam.run();
  }

  const rows = $derived(teams.data ?? []);
  const error = $derived(teams.error ?? addTeam.error ?? removeTeam.error);
</script>

<div>
  <div class="mb-7 flex max-w-[420px] gap-2">
    <input
      class={`${INPUT_CLASS} flex-1`}
      placeholder={t("admin.teams.namePlaceholder")}
      bind:value={newTeamName}
      onkeydown={(event) => event.key === "Enter" && handleCreate()}
    />
    <Button variant="primary" onclick={handleCreate} disabled={addTeam.pending || !newTeamName.trim()}>
      <Icon icon={PlusIcon} size={14} />
      {t("admin.teams.create")}
    </Button>
  </div>
  {#if error}<ErrorText>{error}</ErrorText>{/if}
  {#if rows.length === 0}
    <EmptyState>{teams.loading ? t("common.loading") : t("admin.teams.empty")}</EmptyState>
  {:else}
    <List>
      {#each rows as team (team.id)}
        <ListRow>
          <ListMain as="button" onclick={() => (selectedTeamId = team.id)}>
            <Icon icon={UsersIcon} size={13} class="text-text-muted" />
            <span>{team.name}</span>
            <span class="text-text-muted">{t("admin.teams.memberCount", { count: team.memberCount })}</span>
          </ListMain>
          <Button
            variant="ghost"
            size="icon"
            data-tooltip={t("admin.teams.delete")}
            onclick={() => void removeTeam.run(team.id)}
          >
            <Icon icon={TrashIcon} size={13} />
          </Button>
        </ListRow>
      {/each}
    </List>
  {/if}
  {#if selectedTeamId}
    <TeamDetailView teamId={selectedTeamId} onClose={() => (selectedTeamId = null)} onChanged={teams.reload} />
  {/if}
</div>

// apps/web/src/admin/TeamsTab.tsx
import { useEffect, useState } from "react";
import { PlusIcon, TrashIcon, UsersIcon } from "../Icons.js";
import { Button } from "../ui/Button.js";
import { ErrorText } from "../ui/Alert.js";
import { List, ListMain, ListRow, EmptyState } from "../ui/List.js";
import { INPUT_CLASS } from "../ui/inputStyles.js";
import type { TeamSummary } from "../types.js";
import { TeamDetailView } from "./TeamDetailView.js";

export function TeamsTab() {
  const [teams, setTeams] = useState<TeamSummary[]>([]);
  const [newName, setNewName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedTeamId, setSelectedTeamId] = useState<string | null>(null);

  const refresh = () => {
    fetch("/api/teams")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`list failed (${r.status})`))))
      .then(setTeams)
      .catch((err) => setError((err as Error).message));
  };

  useEffect(refresh, []);

  const create = async () => {
    const trimmed = newName.trim();
    if (!trimmed) return;
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/teams", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name: trimmed }),
      });
      if (res.ok) {
        setNewName("");
        refresh();
      } else {
        const data = await res.json().catch(() => ({}));
        setError(data.error ?? `Create failed (${res.status})`);
      }
    } finally {
      setBusy(false);
    }
  };

  const remove = async (id: string) => {
    await fetch(`/api/teams/${id}`, { method: "DELETE" });
    refresh();
  };

  return (
    <div>
      <div className="mb-7 flex max-w-[420px] gap-2">
        <input
          className={`${INPUT_CLASS} flex-1`}
          placeholder="New team name"
          value={newName}
          onChange={(e) => setNewName(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && create()}
        />
        <Button variant="primary" onClick={create} disabled={busy || !newName.trim()}>
          <PlusIcon size={14} /> Create team
        </Button>
      </div>
      {error && <ErrorText>{error}</ErrorText>}
      {teams.length === 0 ? (
        <EmptyState>No teams yet.</EmptyState>
      ) : (
        <List>
          {teams.map((t) => (
            <ListRow key={t.id}>
              <ListMain as="button" onClick={() => setSelectedTeamId(t.id)}>
                <UsersIcon size={13} className="text-text-muted" />
                <span>{t.name}</span>
                <span className="text-text-muted">
                  {t.memberCount} member{t.memberCount === 1 ? "" : "s"}
                </span>
              </ListMain>
              <Button variant="ghost" size="icon" data-tooltip="Delete team" onClick={() => remove(t.id)}>
                <TrashIcon size={13} />
              </Button>
            </ListRow>
          ))}
        </List>
      )}
      {selectedTeamId && (
        <TeamDetailView teamId={selectedTeamId} onClose={() => setSelectedTeamId(null)} onChanged={refresh} />
      )}
    </div>
  );
}
