// apps/web/src/features/editor/dbml/DbmlEditor/DbmlEditor.svelte
<script lang="ts" module>
  const MIN_FONT = 10;
  const MAX_FONT = 24;
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import { EditorState } from "@codemirror/state";
  import { EditorView } from "@codemirror/view";
  import { foldAll as cmFoldAll, unfoldAll as cmUnfoldAll } from "@codemirror/language";
  import { openSearchPanel } from "@codemirror/search";
  import { openLintPanel } from "@codemirror/lint";
  import { formatDocument } from "@/features/editor/dbml/format";
  import { applyRename, type RenameRequest } from "@/features/editor/dbml/rename";
  import { applyServerProblem } from "@/features/editor/dbml/lint";
  import { createDbmlExtensions, documentSync, fontCompartment, fontTheme, wrapCompartment } from "@/features/editor/dbml/setup";
  import { getSymbols } from "@/features/editor/dbml/symbols";
  import { jumpTo } from "@/features/editor/dbml/navigation";
  import { matchShortcut } from "@/features/plugins/shortcuts";
  import CommandPalette from "@/features/editor/dbml/CommandPalette.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { EMPTY_CURSOR, readCursorInfo } from "./cursorInfo";
  import { readStoredFontSize, readStoredWrap, writeStoredFontSize, writeStoredWrap } from "./prefs";
  import { buildPaletteItems } from "./paletteItems";
  import { runPluginEditorCommand } from "./pluginCommands";
  import RenamePopover from "./RenamePopover.svelte";
  import StatusBar from "./StatusBar.svelte";
  import type { CursorInfo, DbmlEditorProps, PaletteItem, PluginEditorCommand, ViewRef } from "./types";

  let props: DbmlEditorProps = $props();

  const { t } = useTranslation();
  let container: HTMLDivElement;
  const viewRef: ViewRef = { current: null };

  // The open palette carries the entries it was built with. Snapshotting at
  // open time is what keeps the symbol list in step with the document: it is
  // read straight out of CodeMirror's live state, which no reactive derivation
  // can be invalidated against.
  let palette = $state.raw<{ mode: "symbols" | "commands"; items: PaletteItem[] } | null>(null);
  let rename = $state.raw<RenameRequest | null>(null);
  let renameValue = $state("");
  let cursor = $state.raw<CursorInfo>(EMPTY_CURSOR);
  let wrap = $state(readStoredWrap());
  let fontSize = $state(readStoredFontSize());

  function openRename(request: RenameRequest) {
    rename = request;
    renameValue = request.name;
  }

  function run(fn: (view: EditorView) => unknown) {
    const view = viewRef.current;
    if (!view) return;
    fn(view);
    view.focus();
  }

  /** For commands that open their own panel (search, go-to-line, problems) — refocusing the view would steal their input. */
  function runInPanel(fn: (view: EditorView) => unknown) {
    const view = viewRef.current;
    if (view) fn(view);
  }

  const increaseFont = () => (fontSize = Math.min(MAX_FONT, fontSize + 1));
  const decreaseFont = () => (fontSize = Math.max(MIN_FONT, fontSize - 1));

  const runPluginCommand = (command: PluginEditorCommand) =>
    runPluginEditorCommand(viewRef, command, (message, isError) => props.onPluginMessage?.(message, isError));

  function setPalette(mode: "symbols" | "commands" | null) {
    const view = viewRef.current;
    if (!mode || !view) {
      palette = null;
      return;
    }
    palette = {
      mode,
      items: buildPaletteItems(view, mode, {
        run,
        runInPanel,
        wrap,
        toggleWrap: () => (wrap = !wrap),
        increaseFont,
        decreaseFont,
        pluginCommands: props.pluginCommands,
        runPluginCommand,
        t,
      }),
    };
  }

  // Imperative handle for the panel header's buttons.
  export function format() {
    run(formatDocument);
  }
  export function openPalette(mode: "symbols" | "commands") {
    setPalette(mode);
  }
  export function search() {
    runInPanel(openSearchPanel);
  }
  export function foldAll() {
    run(cmFoldAll);
  }
  export function unfoldAll() {
    run(cmUnfoldAll);
  }
  export function focus() {
    viewRef.current?.focus();
  }

  // Owns the CodeMirror instance itself: created on mount, torn down on
  // destroy. Every callback it's given reads the *current* props at call time,
  // so the view never needs rebuilding when a handler changes.
  $effect(() => {
    const readOnly = untrack(() => props.readOnly);
    const state = EditorState.create({
      doc: untrack(() => props.value),
      extensions: createDbmlExtensions({
        lineWrap: readStoredWrap(),
        fontSize: readStoredFontSize(),
        onChange: (value) => props.onChange(value),
        onSave: () => props.onSave(),
        onPalette: (mode) => setPalette(mode),
        onRename: openRename,
        onNavigateToCanvas: (target) => props.onNavigateToCanvas?.(target),
      }).concat(
        // Both are needed: `readOnly` blocks programmatic edits through
        // transactions, `editable` also removes the caret and the "you can type
        // here" affordance.
        readOnly ? [EditorState.readOnly.of(true), EditorView.editable.of(false)] : [],
        EditorView.updateListener.of((update) => {
          if (update.docChanged || update.selectionSet || update.transactions.length > 0) {
            cursor = readCursorInfo(update.view);
          }
        }),
      ),
    });
    const view = new EditorView({ state, parent: container });
    viewRef.current = view;
    cursor = readCursorInfo(view);
    return () => {
      view.destroy();
      viewRef.current = null;
    };
  });

  // External document updates (project -> DBML sync).
  $effect(() => {
    const next = props.value;
    const view = viewRef.current;
    if (!view) return;
    const current = view.state.doc.toString();
    if (next === current) return;

    // A schema resync (e.g. one attribute toggled on one column) used to
    // replace the *whole* buffer even though only a few characters actually
    // differ — CodeMirror then re-tokenizes and re-highlights the entire
    // document on every sync. Trimming to the smallest changed range keeps the
    // edit — and the resulting redraw — proportional to what actually changed.
    let start = 0;
    const maxStart = Math.min(current.length, next.length);
    while (start < maxStart && current.charCodeAt(start) === next.charCodeAt(start)) start++;
    let endCurrent = current.length;
    let endNext = next.length;
    while (endCurrent > start && endNext > start && current.charCodeAt(endCurrent - 1) === next.charCodeAt(endNext - 1)) {
      endCurrent--;
      endNext--;
    }

    view.dispatch({
      changes: { from: start, to: endCurrent, insert: next.slice(start, endNext) },
      selection: { anchor: Math.min(view.state.selection.main.anchor, next.length) },
      // Tagged so the change listener can tell this apart from typing: this is
      // the document being mirrored into the buffer, and echoing it back to
      // the server as an import is what made two connected clients fight over
      // the schema (see `documentSync` in ../setup.ts).
      annotations: documentSync.of(true),
    });
  });

  $effect(() => {
    const problem = props.problem ?? null;
    const view = viewRef.current;
    if (view) applyServerProblem(view, problem);
  });

  let lastScrollRequestId: number | null = null;
  $effect(() => {
    const request = props.scrollToTable;
    void props.value;
    const view = viewRef.current;
    if (!view || !request || lastScrollRequestId === request.requestId) return;
    const table = getSymbols(view.state).tableByName.get(request.tableName.toLowerCase());
    if (table) {
      jumpTo(view, table.nameSpan.from, { select: table.nameSpan });
      lastScrollRequestId = request.requestId;
    }
  });

  // Line-wrap and font-size preferences: persisted, and pushed into
  // CodeMirror's compartments.
  $effect(() => {
    const enabled = wrap;
    viewRef.current?.dispatch({ effects: wrapCompartment.reconfigure(enabled ? EditorView.lineWrapping : []) });
    writeStoredWrap(enabled);
  });
  $effect(() => {
    const size = fontSize;
    viewRef.current?.dispatch({ effects: fontCompartment.reconfigure(fontTheme(size)) });
    writeStoredFontSize(size);
  });

  // Ctrl/Cmd + wheel zooms the editor font. Registered with `{ passive: false }`
  // so `preventDefault()` actually stops the browser from zooming the page.
  $effect(() => {
    const onWheel = (event: WheelEvent) => {
      if (!(event.ctrlKey || event.metaKey)) return;
      event.preventDefault();
      fontSize = Math.max(MIN_FONT, Math.min(MAX_FONT, fontSize + (event.deltaY < 0 ? 1 : -1)));
    };
    container.addEventListener("wheel", onWheel, { passive: false });
    return () => container.removeEventListener("wheel", onWheel);
  });

  // Plugin shortcuts, bound on the editor container in the capture phase so
  // CodeMirror never swallows the combination first — and never on `window`,
  // so a plugin can't shadow a key combination while the user is elsewhere in
  // the app.
  $effect(() => {
    const commands = props.pluginCommands;
    if (!commands || commands.length === 0) return;
    const onKeyDown = (event: KeyboardEvent) => {
      const command = matchShortcut(commands, event);
      if (!command) return;
      event.preventDefault();
      event.stopPropagation();
      void runPluginCommand(command);
    };
    container.addEventListener("keydown", onKeyDown, true);
    return () => container.removeEventListener("keydown", onKeyDown, true);
  });

  function commitRename() {
    const view = viewRef.current;
    if (!view || !rename) return;
    const trimmed = renameValue.trim();
    if (trimmed && trimmed !== rename.name) applyRename(view, rename, trimmed);
    rename = null;
    view.focus();
  }
</script>

<div class="relative flex h-full min-h-0 flex-col">
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div bind:this={container} class="min-h-0 flex-1 overflow-hidden" onkeydown={(event) => event.stopPropagation()}></div>

  {#if rename}
    <RenamePopover
      {rename}
      value={renameValue}
      onChange={(value) => (renameValue = value)}
      onCommit={commitRename}
      onCancel={() => {
        rename = null;
        viewRef.current?.focus();
      }}
      onDismiss={() => (rename = null)}
    />
  {/if}

  {#if palette}
    <CommandPalette
      items={palette.items}
      placeholder={palette.mode === "commands" ? t("dbml.palette.commandsPlaceholder") : t("dbml.palette.symbolsPlaceholder")}
      onClose={() => {
        palette = null;
        viewRef.current?.focus();
      }}
    />
  {/if}

  <StatusBar
    {cursor}
    {wrap}
    onToggleWrap={() => (wrap = !wrap)}
    {fontSize}
    onIncreaseFont={increaseFont}
    onDecreaseFont={decreaseFont}
    onShowProblems={() => runInPanel(openLintPanel)}
  />
</div>

// apps/web/src/dbmlEditor/DbmlEditor.tsx
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from "react";
import { EditorState } from "@codemirror/state";
import { EditorView } from "@codemirror/view";
import { foldAll, unfoldAll } from "@codemirror/language";
import { openSearchPanel, gotoLine, selectNextOccurrence } from "@codemirror/search";
import { forEachDiagnostic, nextDiagnostic, openLintPanel } from "@codemirror/lint";
import { applyServerProblem, type ServerProblem } from "./lint.js";
import { createDbmlExtensions, fontCompartment, fontTheme, wrapCompartment } from "./setup.js";
import { getSymbols } from "./symbols.js";
import { goToDefinition, jumpTo, jumpToLine, navigateBack, navigateForward } from "./navigation.js";
import { formatDocument } from "./format.js";
import { applyRename, startRename, type RenameRequest } from "./rename.js";
import { duplicateSelection, sortTableColumns } from "./commands.js";
import { CommandPalette, type PaletteItem } from "./CommandPalette.js";
import { matchShortcut } from "../plugins/shortcuts.js";

const PREF_WRAP = "athanordb_dbml_wrap";
const PREF_FONT = "athanordb_dbml_font_size";

export interface DbmlEditorHandle {
  format: () => void;
  openPalette: (mode: "symbols" | "commands") => void;
  search: () => void;
  foldAll: () => void;
  unfoldAll: () => void;
  focus: () => void;
}

/**
 * An editor command contributed by a plugin. It never touches CodeMirror: it
 * receives the buffer plus the current selection and returns the replacement
 * buffer, which keeps plugin code independent of the editor implementation.
 */
export interface PluginEditorCommand {
  key: string;
  label: string;
  detail?: string;
  /** e.g. `"Ctrl+Alt+S"` — bound while the editor has focus, never globally. */
  shortcut?: string;
  run: (input: {
    text: string;
    selection: { from: number; to: number };
    selectedText: string;
  }) => Promise<{ text?: string | null; message?: string }>;
}

interface CursorInfo {
  line: number;
  column: number;
  selected: number;
  cursors: number;
  breadcrumb: string | null;
  errors: number;
  warnings: number;
}

const EMPTY_CURSOR: CursorInfo = { line: 1, column: 1, selected: 0, cursors: 1, breadcrumb: null, errors: 0, warnings: 0 };

function readCursorInfo(view: EditorView): CursorInfo {
  const state = view.state;
  const main = state.selection.main;
  const line = state.doc.lineAt(main.head);
  const symbols = getSymbols(state);
  const table = symbols.tables.find((t) => line.number >= t.line && line.number <= t.endLine);
  let errors = 0;
  let warnings = 0;
  forEachDiagnostic(state, (d) => {
    if (d.severity === "error") errors += 1;
    else if (d.severity === "warning") warnings += 1;
  });
  return {
    line: line.number,
    column: main.head - line.from + 1,
    selected: state.selection.ranges.reduce((sum, r) => sum + (r.to - r.from), 0),
    cursors: state.selection.ranges.length,
    breadcrumb: table ? table.name : null,
    errors,
    warnings,
  };
}

export const DbmlEditor = forwardRef<
  DbmlEditorHandle,
  {
    value: string;
    onChange: (value: string) => void;
    onSave: () => void;
    problem?: ServerProblem | null;
    scrollToTable?: { tableName: string; requestId: number } | null;
    pluginCommands?: PluginEditorCommand[];
    onPluginMessage?: (message: string, isError?: boolean) => void;
  }
>(function DbmlEditor(props, ref) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const viewRef = useRef<EditorView | null>(null);
  const onChangeRef = useRef(props.onChange);
  const onSaveRef = useRef(props.onSave);
  onChangeRef.current = props.onChange;
  onSaveRef.current = props.onSave;

  const [palette, setPalette] = useState<"symbols" | "commands" | null>(null);
  const [rename, setRename] = useState<RenameRequest | null>(null);
  const [renameValue, setRenameValue] = useState("");
  const [cursor, setCursor] = useState<CursorInfo>(EMPTY_CURSOR);
  const [wrap, setWrap] = useState(() => localStorage.getItem(PREF_WRAP) !== "off");
  const [fontSize, setFontSize] = useState(() => {
    const saved = Number(localStorage.getItem(PREF_FONT));
    return Number.isFinite(saved) && saved >= 10 && saved <= 24 ? saved : 13;
  });

  const openRename = useCallback((request: RenameRequest) => {
    setRename(request);
    setRenameValue(request.name);
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;
    const state = EditorState.create({
      doc: props.value,
      extensions: createDbmlExtensions({
        lineWrap: localStorage.getItem(PREF_WRAP) !== "off",
        fontSize: Number(localStorage.getItem(PREF_FONT)) || 13,
        onChange: (value) => onChangeRef.current(value),
        onSave: () => onSaveRef.current(),
        onPalette: (mode) => setPalette(mode),
        onRename: openRename,
      }).concat(
        EditorView.updateListener.of((update) => {
          if (update.docChanged || update.selectionSet || update.transactions.length > 0) {
            setCursor(readCursorInfo(update.view));
          }
        }),
      ),
    });
    const view = new EditorView({ state, parent: containerRef.current });
    viewRef.current = view;
    setCursor(readCursorInfo(view));
    return () => {
      view.destroy();
      viewRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // external document updates (project -> DBML sync)
  useEffect(() => {
    const view = viewRef.current;
    if (!view) return;
    const current = view.state.doc.toString();
    if (props.value === current) return;
    view.dispatch({
      changes: { from: 0, to: current.length, insert: props.value },
      selection: { anchor: Math.min(view.state.selection.main.anchor, props.value.length) },
    });
  }, [props.value]);

  useEffect(() => {
    const view = viewRef.current;
    if (view) applyServerProblem(view, props.problem ?? null);
  }, [props.problem]);

  const lastRequestRef = useRef<number | null>(null);
  useEffect(() => {
    const view = viewRef.current;
    const request = props.scrollToTable;
    if (!view || !request || lastRequestRef.current === request.requestId) return;
    const table = getSymbols(view.state).tableByName.get(request.tableName.toLowerCase());
    if (table) {
      jumpTo(view, table.nameSpan.from, { select: table.nameSpan });
      lastRequestRef.current = request.requestId;
    }
  }, [props.scrollToTable, props.value]);

  useEffect(() => {
    const view = viewRef.current;
    if (!view) return;
    view.dispatch({ effects: wrapCompartment.reconfigure(wrap ? EditorView.lineWrapping : []) });
    localStorage.setItem(PREF_WRAP, wrap ? "on" : "off");
  }, [wrap]);

  useEffect(() => {
    const view = viewRef.current;
    if (!view) return;
    view.dispatch({ effects: fontCompartment.reconfigure(fontTheme(fontSize)) });
    localStorage.setItem(PREF_FONT, String(fontSize));
  }, [fontSize]);

  const run = useCallback((fn: (view: EditorView) => unknown) => {
    const view = viewRef.current;
    if (!view) return;
    fn(view);
    view.focus();
  }, []);

  /** For commands that open their own panel (search, go-to-line, problems) — refocusing the view would steal their input. */
  const runInPanel = useCallback((fn: (view: EditorView) => unknown) => {
    const view = viewRef.current;
    if (view) fn(view);
  }, []);

  useImperativeHandle(
    ref,
    () => ({
      format: () => run(formatDocument),
      openPalette: (mode) => setPalette(mode),
      search: () => runInPanel(openSearchPanel),
      foldAll: () => run(foldAll),
      unfoldAll: () => run(unfoldAll),
      focus: () => viewRef.current?.focus(),
    }),
    [run, runInPanel],
  );

  const { pluginCommands, onPluginMessage } = props;

  /** Runs a plugin editor command against the live buffer and adopts what it returns. */
  const runPluginCommand = useCallback(
    async (command: PluginEditorCommand) => {
      const view = viewRef.current;
      if (!view) return;
      const { state } = view;
      const selection = { from: state.selection.main.from, to: state.selection.main.to };
      const text = state.doc.toString();
      try {
        const result = await command.run({ text, selection, selectedText: state.sliceDoc(selection.from, selection.to) });
        const next = result?.text;
        if (typeof next === "string" && next !== view.state.doc.toString()) {
          const current = view.state.doc.length;
          view.dispatch({
            changes: { from: 0, to: current, insert: next },
            selection: { anchor: Math.min(state.selection.main.anchor, next.length) },
          });
        }
        if (result?.message) onPluginMessage?.(result.message);
      } catch (err) {
        onPluginMessage?.(err instanceof Error ? err.message : String(err), true);
      }
      view.focus();
    },
    [onPluginMessage],
  );

  /**
   * Plugin editor shortcuts, bound on the editor container rather than the
   * window: a plugin must not be able to shadow a key combination while the
   * user is somewhere else in the app.
   */
  useEffect(() => {
    const el = containerRef.current;
    if (!el || !pluginCommands || pluginCommands.length === 0) return;
    const onKeyDown = (event: KeyboardEvent) => {
      const command = matchShortcut(pluginCommands, event);
      if (!command) return;
      event.preventDefault();
      event.stopPropagation();
      void runPluginCommand(command);
    };
    // Capture phase, for the same reason as the canvas: CodeMirror handles
    // keydown on the editor itself and would swallow the combination first.
    el.addEventListener("keydown", onKeyDown, true);
    return () => el.removeEventListener("keydown", onKeyDown, true);
  }, [pluginCommands, runPluginCommand]);

  const paletteItems = useMemo((): PaletteItem[] => {
    const view = viewRef.current;
    if (!view || !palette) return [];
    if (palette === "commands") {
      const commands: Array<[string, string, (view: EditorView) => unknown, boolean?]> = [
        ["Format document", "Shift+Alt+F", formatDocument],
        ["Sort columns of current table", "Ctrl+Alt+O", sortTableColumns],
        ["Go to definition", "F12", goToDefinition],
        ["Rename symbol", "F2", startRename],
        ["Select next occurrence", "Ctrl+D", selectNextOccurrence],
        ["Duplicate selection", "Ctrl+Shift+D", duplicateSelection],
        ["Find / replace", "Ctrl+F", openSearchPanel, true],
        ["Go to line", "Ctrl+G", gotoLine, true],
        ["Next problem", "F8", nextDiagnostic],
        ["Show problems panel", "Ctrl+Shift+M", openLintPanel, true],
        ["Fold all", "Ctrl+K Ctrl+0", foldAll],
        ["Unfold all", "Ctrl+K Ctrl+J", unfoldAll],
        ["Navigate back", "Alt+←", navigateBack],
        ["Navigate forward", "Alt+→", navigateForward],
      ];
      return [
        ...commands.map(([label, hint, fn, opensPanel]) => ({
          id: label,
          label,
          hint,
          kind: "cmd",
          run: () => (opensPanel ? runInPanel(fn) : run(fn)),
        })),
        {
          id: "toggle-wrap",
          label: wrap ? "Disable line wrapping" : "Enable line wrapping",
          kind: "cmd",
          run: () => setWrap((w) => !w),
        },
        { id: "font-in", label: "Increase font size", hint: "Ctrl+=", kind: "cmd", run: () => setFontSize((s) => Math.min(24, s + 1)) },
        { id: "font-out", label: "Decrease font size", hint: "Ctrl+-", kind: "cmd", run: () => setFontSize((s) => Math.max(10, s - 1)) },
        ...(pluginCommands ?? []).map((command) => ({
          id: `plugin:${command.key}`,
          label: command.label,
          kind: "plugin",
          detail: command.detail,
          hint: command.shortcut,
          run: () => void runPluginCommand(command),
        })),
      ];
    }

    const symbols = getSymbols(view.state);
    const items: PaletteItem[] = [];
    for (const table of symbols.tables) {
      items.push({
        id: `table:${table.name}`,
        label: table.name,
        kind: "table",
        detail: `${table.fields.length} col`,
        hint: `L${table.line}`,
        run: () => run((v) => jumpTo(v, table.nameSpan.from, { select: table.nameSpan })),
      });
      for (const field of table.fields) {
        items.push({
          id: `field:${table.name}.${field.name}`,
          label: `${table.name}.${field.name}`,
          kind: field.pk ? "pk" : "col",
          detail: field.type,
          hint: `L${field.line}`,
          run: () => run((v) => jumpTo(v, field.nameSpan.from, { select: field.nameSpan })),
        });
      }
    }
    for (const e of symbols.enums) {
      items.push({
        id: `enum:${e.name}`,
        label: e.name,
        kind: "enum",
        detail: `${e.values.length} values`,
        hint: `L${e.line}`,
        run: () => run((v) => jumpTo(v, e.nameSpan.from, { select: e.nameSpan })),
      });
    }
    for (const group of symbols.groups) {
      items.push({
        id: `group:${group.name}`,
        label: group.name,
        kind: "group",
        detail: `${group.members.length} tables`,
        hint: `L${group.line}`,
        run: () => run((v) => jumpToLine(v, group.line)),
      });
    }
    for (const ref of symbols.refs) {
      const label = `${ref.left.table}.${ref.left.fields.join(",")} ${ref.relation} ${ref.right.table}.${ref.right.fields.join(",")}`;
      items.push({
        id: `ref:${label}:${ref.line}`,
        label,
        kind: "ref",
        hint: `L${ref.line}`,
        run: () => run((v) => jumpToLine(v, ref.line)),
      });
    }
    return items;
  }, [palette, run, runInPanel, wrap, pluginCommands, runPluginCommand]);

  const commitRename = () => {
    const view = viewRef.current;
    if (!view || !rename) return;
    const trimmed = renameValue.trim();
    if (trimmed && trimmed !== rename.name) applyRename(view, rename, trimmed);
    setRename(null);
    view.focus();
  };

  return (
    <div className="relative flex h-full min-h-0 flex-col">
      <div
        ref={containerRef}
        className="min-h-0 flex-1 overflow-hidden"
        onKeyDown={(e) => e.stopPropagation()}
        onWheel={(e) => {
          if (!(e.ctrlKey || e.metaKey)) return;
          e.preventDefault();
          setFontSize((s) => Math.max(10, Math.min(24, s + (e.deltaY < 0 ? 1 : -1))));
        }}
      />

      {rename && (
        <div className="absolute left-1/2 top-6 z-40 w-[86%] -translate-x-1/2 rounded-lg border border-border bg-surface p-2 shadow-2xl">
          <div className="mb-1 px-1 text-[11px] text-text-muted">
            Rename {rename.kind}
            {rename.owner ? ` of ${rename.owner}` : ""} — {rename.occurrences} occurrence
            {rename.occurrences === 1 ? "" : "s"}
          </div>
          <input
            autoFocus
            value={renameValue}
            onChange={(e) => setRenameValue(e.target.value)}
            onKeyDown={(e) => {
              e.stopPropagation();
              if (e.key === "Enter") {
                e.preventDefault();
                commitRename();
              } else if (e.key === "Escape") {
                e.preventDefault();
                setRename(null);
                viewRef.current?.focus();
              }
            }}
            onBlur={() => setRename(null)}
            className="w-full rounded border border-border bg-bg px-2 py-1 text-[13px] text-text outline-none focus:border-primary"
          />
        </div>
      )}

      {palette && (
        <CommandPalette
          items={paletteItems}
          placeholder={palette === "commands" ? "Type a command…" : "Go to table, column, enum or relationship…"}
          onClose={() => {
            setPalette(null);
            viewRef.current?.focus();
          }}
        />
      )}

      <div className="flex shrink-0 items-center gap-3 border-t border-border bg-surface px-2.5 py-1 text-[11px] text-text-muted">
        <span title="Line, column">
          Ln {cursor.line}, Col {cursor.column}
        </span>
        {cursor.selected > 0 && <span>{cursor.selected} sel</span>}
        {cursor.cursors > 1 && <span className="text-primary">{cursor.cursors} cursors</span>}
        {cursor.breadcrumb && (
          <span className="truncate" title="Current table">
            › {cursor.breadcrumb}
          </span>
        )}
        <span className="ml-auto flex items-center gap-2">
          {(cursor.errors > 0 || cursor.warnings > 0) && (
            <button
              type="button"
              onClick={() => runInPanel(openLintPanel)}
              className="rounded px-1 hover:bg-surface-hover"
              title="Show problems (Ctrl+Shift+M)"
            >
              <span className={cursor.errors ? "text-danger" : ""}>✕ {cursor.errors}</span>{" "}
              <span className={cursor.warnings ? "text-warning" : ""}>⚠ {cursor.warnings}</span>
            </button>
          )}
          <button
            type="button"
            onClick={() => setWrap((w) => !w)}
            className="rounded px-1 hover:bg-surface-hover"
            title="Toggle line wrapping"
          >
            wrap: {wrap ? "on" : "off"}
          </button>
          <button
            type="button"
            onClick={() => setFontSize((s) => Math.max(10, s - 1))}
            className="rounded px-1 hover:bg-surface-hover"
            title="Decrease font size"
          >
            A−
          </button>
          <span>{fontSize}px</span>
          <button
            type="button"
            onClick={() => setFontSize((s) => Math.min(24, s + 1))}
            className="rounded px-1 hover:bg-surface-hover"
            title="Increase font size"
          >
            A+
          </button>
          <span title="Indentation">2 spaces</span>
        </span>
      </div>
    </div>
  );
});
