// apps/web/src/components/inputs/ColorSwatchPicker.svelte
<script lang="ts">
  import { anchoredPlacement, provisionalPopoverStyle } from "@/actions/placement";
  import { portal } from "@/actions/portal";
  import Icon from "@/components/icons/Icon.svelte";
  import { PlusIcon } from "@/components/icons/Icons";
  import { INPUT_XS_CLASS } from "@/components/ui/inputStyles";
  import { useDismissablePopover } from "@/hooks/dismissablePopover.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { HEX_RE, SWATCH_CELL_ACTIVE_CLASS, SWATCH_CELL_CLASS, SWATCH_GRID_CLASS } from "./colorSwatches";

  /**
   * Small circular swatch button that opens a preset-color popover (+ custom
   * hex) instead of the OS native color picker. Portaled to `document.body`
   * since every caller lives inside a canvas node — nodes clip overflow and
   * get CSS-transformed for pan/zoom, so an absolutely-positioned child
   * popover would either be clipped or scaled/misplaced with the canvas.
   *
   * `palette` is per-project (persisted in the doc's meta map, shared by every
   * table/zone/note picker in that project) rather than a fixed global list —
   * callers fall back to `DEFAULT_PALETTE` when the project hasn't customized
   * one yet. Right-click a swatch to remove it; the "+" cell adds whatever the
   * current value is.
   */
  let {
    value,
    onChange,
    palette,
    onPaletteChange,
    triggerClassName,
    tooltip,
  }: {
    value: string;
    onChange: (color: string) => void;
    palette: string[];
    onPaletteChange: (palette: string[]) => void;
    triggerClassName: string;
    tooltip?: string;
  } = $props();

  const { t } = useTranslation();
  let open = $state(false);
  // Re-seeded from the committed colour whenever it changes (writable derived).
  let hexDraft = $derived(value);
  let triggerRect = $state.raw<DOMRect | null>(null);
  let trigger: HTMLButtonElement | undefined = $state();
  let popover: HTMLDivElement | undefined = $state();

  useDismissablePopover(
    () => open,
    () => (open = false),
    () => [popover, trigger],
  );

  function toggle() {
    if (!open && trigger) triggerRect = trigger.getBoundingClientRect();
    open = !open;
  }

  function commitHex() {
    const next = hexDraft.trim();
    if (HEX_RE.test(next)) onChange(next);
    else hexDraft = value;
  }

  function removeFromPalette(event: MouseEvent, color: string) {
    event.preventDefault();
    onPaletteChange(palette.filter((c) => c !== color));
  }

  function addCurrentToPalette() {
    if (palette.some((c) => c.toLowerCase() === value.toLowerCase())) return;
    onPaletteChange([...palette, value]);
  }
</script>

<button
  bind:this={trigger}
  type="button"
  class={`nodrag ${triggerClassName}`}
  style:background={value}
  onclick={(event) => {
    event.stopPropagation();
    toggle();
  }}
  ondblclick={(event) => event.stopPropagation()}
  data-tooltip={tooltip ?? "Color"}
  aria-label={tooltip ?? "Color"}
></button>
{#if open && triggerRect}
  <div
    use:portal
    use:anchoredPlacement={{ rect: triggerRect }}
    bind:this={popover}
    class="fixed z-[var(--z-popover)] animate-modal-in rounded-md border border-border-strong bg-surface-raised p-2.5 shadow-lg nodrag"
    style={provisionalPopoverStyle(triggerRect)}
  >
    <div class={SWATCH_GRID_CLASS}>
      {#each palette as c (c)}
        <button
          type="button"
          class={`${SWATCH_CELL_CLASS} ${c.toLowerCase() === value.toLowerCase() ? SWATCH_CELL_ACTIVE_CLASS : ""}`}
          style:background={c}
          onclick={() => {
            onChange(c);
            open = false;
          }}
          oncontextmenu={(event) => removeFromPalette(event, c)}
          data-tooltip={`${c} (right-click to remove)`}
          aria-label={c}
        ></button>
      {/each}
      <button
        type="button"
        class={`${SWATCH_CELL_CLASS} flex items-center justify-center border-dashed bg-surface text-text-muted hover:border-text-muted hover:text-text`}
        onclick={addCurrentToPalette}
        data-tooltip={t("palette.addColor")}
      >
        <Icon icon={PlusIcon} size={11} />
      </button>
    </div>
    <input
      class={`${INPUT_XS_CLASS} w-full font-mono`}
      bind:value={hexDraft}
      onblur={commitHex}
      onkeydown={(event) => {
        if (event.key === "Enter") commitHex();
        if (event.key === "Escape") hexDraft = value;
      }}
      spellcheck={false}
    />
  </div>
{/if}

// apps/web/src/ColorSwatchPicker.tsx
import { useEffect, useRef, useState, type MouseEvent as ReactMouseEvent } from "react";
import { createPortal } from "react-dom";
import { PlusIcon } from "./Icons.js";
import { INPUT_XS_CLASS } from "./ui/inputStyles.js";

export const SWATCH_CELL_CLASS =
  "h-[22px] w-[22px] shrink-0 rounded-sm border-[1.5px] border-white/15 p-0 cursor-pointer transition-transform duration-75 ease-out hover:scale-110";
export const SWATCH_CELL_ACTIVE_CLASS = "outline outline-2 outline-primary outline-offset-1";
export const SWATCH_GRID_CLASS = "grid grid-cols-5 gap-1.5 mb-2";

export const DEFAULT_PALETTE = [
  "#6366f1",
  "#ef4444",
  "#22c55e",
  "#f59e0b",
  "#a855f7",
  "#14b8a6",
  "#475569",
  "#f97316",
  "#6b7280",
  "#ec4899",
  "#0ea5e9",
  "#84cc16",
  "#f43f5e",
  "#4f46e5",
  "#06b6d4",
];

const HEX_RE = /^#[0-9a-fA-F]{6}$/;

/**
 * Small circular swatch button that opens a preset-color popover (+ custom
 * hex) instead of the OS native color picker. Portaled to `document.body`
 * since every caller lives inside a React Flow node — nodes clip overflow
 * and get CSS-transformed for pan/zoom, so an absolutely-positioned child
 * popover would either be clipped or scaled/misplaced with the canvas.
 *
 * `palette` is per-project (persisted in the doc's meta map, shared by every
 * table/zone/note picker in that project) rather than a fixed global list —
 * callers fall back to `DEFAULT_PALETTE` when the project hasn't customized
 * one yet. Right-click a swatch to remove it; the "+" cell adds whatever the
 * current value is.
 */
export function ColorSwatchPicker(props: {
  value: string;
  onChange: (color: string) => void;
  palette: string[];
  onPaletteChange: (palette: string[]) => void;
  triggerClassName: string;
  tooltip?: string;
}) {
  const [open, setOpen] = useState(false);
  const [hexDraft, setHexDraft] = useState(props.value);
  const [popoverPos, setPopoverPos] = useState<{ x: number; y: number } | null>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const popoverRef = useRef<HTMLDivElement>(null);

  useEffect(() => setHexDraft(props.value), [props.value]);

  useEffect(() => {
    if (!open) return;
    // "click", not "mousedown": React Flow's pane calls stopPropagation on
    // mousedown for its own pan/drag handling, so a mousedown-based
    // outside-click listener on window never fires for clicks landing on the
    // canvas — only for clicks outside React Flow entirely. Plain "click"
    // isn't intercepted the same way (same reason the canvas context menu's
    // own outside-click handling already uses "click").
    const handleOutsideClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (popoverRef.current?.contains(target) || triggerRef.current?.contains(target)) return;
      setOpen(false);
    };
    const onKeyDown = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false);
    window.addEventListener("click", handleOutsideClick);
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("click", handleOutsideClick);
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  const toggle = () => {
    if (!open && triggerRef.current) {
      const rect = triggerRef.current.getBoundingClientRect();
      setPopoverPos({ x: rect.left, y: rect.bottom + 6 });
    }
    setOpen((v) => !v);
  };

  const commitHex = () => {
    const next = hexDraft.trim();
    if (HEX_RE.test(next)) props.onChange(next);
    else setHexDraft(props.value);
  };

  const removeFromPalette = (e: ReactMouseEvent, color: string) => {
    e.preventDefault();
    props.onPaletteChange(props.palette.filter((c) => c !== color));
  };

  const addCurrentToPalette = () => {
    if (props.palette.some((c) => c.toLowerCase() === props.value.toLowerCase())) return;
    props.onPaletteChange([...props.palette, props.value]);
  };

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        className={`nodrag ${props.triggerClassName}`}
        style={{ background: props.value }}
        onClick={(e) => {
          e.stopPropagation();
          toggle();
        }}
        onDoubleClick={(e) => e.stopPropagation()}
        data-tooltip={props.tooltip ?? "Color"}
      />
      {open &&
        popoverPos &&
        createPortal(
          <div
            ref={popoverRef}
            className="fixed z-[2000] animate-modal-in rounded-md border border-border bg-surface-raised p-2.5 shadow-lg nodrag"
            style={{ left: popoverPos.x, top: popoverPos.y }}
          >
            <div className={SWATCH_GRID_CLASS}>
              {props.palette.map((c) => (
                <button
                  key={c}
                  type="button"
                  className={`${SWATCH_CELL_CLASS} ${c.toLowerCase() === props.value.toLowerCase() ? SWATCH_CELL_ACTIVE_CLASS : ""}`}
                  style={{ background: c }}
                  onClick={() => {
                    props.onChange(c);
                    setOpen(false);
                  }}
                  onContextMenu={(e) => removeFromPalette(e, c)}
                  data-tooltip={`${c} (right-click to remove)`}
                />
              ))}
              <button
                type="button"
                className={`${SWATCH_CELL_CLASS} flex items-center justify-center border-dashed bg-surface text-text-muted hover:border-text-muted hover:text-text`}
                onClick={addCurrentToPalette}
                data-tooltip="Add current color to this project's palette"
              >
                <PlusIcon size={11} />
              </button>
            </div>
            <input
              className={`${INPUT_XS_CLASS} w-full font-mono`}
              value={hexDraft}
              onChange={(e) => setHexDraft(e.target.value)}
              onBlur={commitHex}
              onKeyDown={(e) => {
                if (e.key === "Enter") commitHex();
                if (e.key === "Escape") setHexDraft(props.value);
              }}
              spellCheck={false}
            />
          </div>,
          document.body,
        )}
    </>
  );
}
