// apps/web/src/components/layout/Navbar.svelte
<script lang="ts" module>
  export const APP_NAME = "AthanorDB";
</script>

<script lang="ts">
  import BrandMark from "@/components/ui/BrandMark.svelte";
  import Button from "@/components/ui/Button.svelte";
  import { APP_HEADER } from "@/components/ui/layout";
  import Icon from "@/components/icons/Icon.svelte";
  import { ChevronLeftIcon, LogOutIcon, SettingsIcon, UsersIcon } from "@/components/icons/Icons";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import type { Session } from "@/types";

  /**
   * App header. The account control is a single button — avatar, name and gear —
   * rather than the avatar chip *and* a separate "Settings" button it used to
   * carry side by side, both opening the same panel. The name is what makes it
   * worth the width: on a shared or multi-account install it is the only place
   * that says who you are signed in as.
   */
  let {
    session,
    onOpenSettings,
    onOpenAdmin,
    onLogout,
    title = APP_NAME,
    onBack,
  }: {
    session: Session;
    onOpenSettings?: () => void;
    onOpenAdmin?: () => void;
    onLogout?: () => void;
    title?: string;
    onBack?: () => void;
  } = $props();

  const { t } = useTranslation();
</script>

<header class={`${APP_HEADER} justify-between gap-4`}>
  <div class="flex min-w-0 items-center gap-3">
    {#if onBack}
      <Button variant="ghost" size="sm" onclick={onBack}>
        <Icon icon={ChevronLeftIcon} size={14} />
        {t("common.back")}
      </Button>
    {:else}
      <div class="flex select-none items-center gap-2.5">
        <BrandMark size={24} />
        <span class="truncate text-sm font-extrabold tracking-tight text-text">{title}</span>
      </div>
    {/if}
  </div>

  <div class="flex shrink-0 items-center gap-1.5">
    {#if session.isAdmin && onOpenAdmin}
      <Button
        variant="ghost"
        size="sm"
        onclick={onOpenAdmin}
        data-tooltip={t("admin.title")}
        data-tooltip-pos="bottom"
      >
        <Icon icon={UsersIcon} size={14} />
        <span class="hidden sm:inline">{t("common.admin")}</span>
      </Button>
    {/if}

    {#if onOpenSettings}
      <Button
        variant="default"
        size="sm"
        onclick={onOpenSettings}
        data-tooltip={t("navbar.accountSettings")}
        data-tooltip-pos="bottom"
        class="max-w-[220px] gap-2 pl-1.5"
      >
        <span
          class="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary-light text-[10px] font-bold text-primary"
        >
          {session.displayName.charAt(0).toUpperCase()}
        </span>
        <span class="hidden truncate text-text sm:inline">{session.displayName}</span>
        <Icon icon={SettingsIcon} size={13} class="shrink-0 text-text-muted" />
      </Button>
    {/if}

    {#if onLogout}
      <Button
        variant="ghost"
        size="icon-sm"
        onclick={onLogout}
        data-tooltip={t("common.logout")}
        data-tooltip-pos="bottom"
        aria-label={t("common.logout")}
      >
        <Icon icon={LogOutIcon} size={14} />
      </Button>
    {/if}
  </div>
</header>

// apps/web/src/Navbar.tsx
import { BrandMark } from "./ui/BrandMark.js";
import { Button } from "./ui/Button.js";
import { Badge } from "./ui/Badge.js";
import { StatusPill } from "./ui/StatusPill.js";
import { SettingsIcon, UsersIcon, LogOutIcon } from "./Icons.js";
import type { Session } from "./types.js";

export interface NavbarProps {
  session: Session;
  serverStatus: "checking" | "ok" | "down";
  onOpenSettings?: () => void;
  onOpenAdmin?: () => void;
  onLogout?: () => void;
  onDisplayNameChange?: (name: string) => void;
  title?: string;
  onBack?: () => void;
}


export function Navbar({
  session,
  serverStatus,
  onOpenSettings,
  onOpenAdmin,
  onLogout,
  title = "AthanorDB",
  onBack,
}: NavbarProps) {
  return (
    <header className="h-14 shrink-0 px-6 border-b border-border/80 bg-surface/90 glass-panel flex items-center justify-between z-30 select-none">
      <div className="flex items-center gap-4">
        {onBack ? (
          <Button variant="ghost" size="sm" onClick={onBack} className="text-xs">
            ← Retour
          </Button>
        ) : (
          <div className="flex items-center gap-2.5 select-none">
            <BrandMark size={24} />
            <span className="font-extrabold text-sm tracking-tight text-text">{title}</span>
          </div>
        )}

        <Badge tone="admin" className="hidden sm:inline-flex">v0.0.1 Open-Core</Badge>
        <span className="hidden lg:inline-flex">
          <StatusPill status={serverStatus} />
        </span>
      </div>

      <div className="flex items-center gap-3">
        {session.isAdmin && onOpenAdmin && (
          <Button
            variant="outline"
            size="sm"
            onClick={onOpenAdmin}
            data-tooltip="Console d'administration"
            data-tooltip-pos="bottom"
            className="gap-1.5 text-xs"
          >
            <UsersIcon size={13} /> Admin
          </Button>
        )}

        {/* User Profile Pill */}
        <button
          onClick={onOpenSettings}
          className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-surface-raised border border-border/60 text-xs font-semibold hover:bg-surface-hover transition-colors"
          data-tooltip="Paramètres du compte"
          data-tooltip-pos="bottom"
        >
          <div className="w-5 h-5 rounded-full bg-primary/20 text-primary flex items-center justify-center font-bold text-[10px]">
            {session.displayName.charAt(0).toUpperCase()}
          </div>
          <span className="text-text max-w-[120px] truncate">{session.displayName}</span>
          <SettingsIcon size={13} className="text-text-muted" />
        </button>

        {/* Was a "Cloud Pro" upsell button pointing at settings — an upsell for
            a product that doesn't exist, on a page the user is already using.
            It opens the settings panel, so it now says so. */}
        {onOpenSettings && (
          <Button
            variant="ghost"
            size="sm"
            onClick={onOpenSettings}
            className="hidden md:inline-flex gap-1.5 text-xs"
          >
            <SettingsIcon size={13} /> Paramètres
          </Button>
        )}

        {onLogout && (
          <Button variant="ghost" size="icon" onClick={onLogout} data-tooltip="Se déconnecter" data-tooltip-pos="bottom">
            <LogOutIcon size={14} />
          </Button>
        )}
      </div>
    </header>
  );
}
