// apps/web/src/features/teams/ProjectTeamsModal.svelte
<script lang="ts" module>
  import type { PermissionLevel, TranslationKeyOf } from "@/types";

  const PERMISSION_LEVELS: PermissionLevel[] = ["view", "edit", "administrator"];

  const PERMISSION_LABEL_KEY = {
    view: "permission.view",
    edit: "permission.edit",
    administrator: "permission.administrator",
  } as const satisfies Record<PermissionLevel, TranslationKeyOf>;
</script>

<script lang="ts">
  import Modal from "@/components/overlays/Modal.svelte";
  import Icon from "@/components/icons/Icon.svelte";
  import { PlusIcon, TrashIcon } from "@/components/icons/Icons";
  import Button from "@/components/ui/Button.svelte";
  import Hint from "@/components/ui/Hint.svelte";
  import ErrorText from "@/components/ui/ErrorText.svelte";
  import List from "@/components/ui/List.svelte";
  import ListMain from "@/components/ui/ListMain.svelte";
  import ListRow from "@/components/ui/ListRow.svelte";
  import EmptyState from "@/components/ui/EmptyState.svelte";
  import { SELECT_CLASS, SELECT_SM_CLASS } from "@/components/ui/inputStyles";
  import { useAsyncAction } from "@/hooks/asyncAction.svelte";
  import { useAsyncResource } from "@/hooks/asyncResource.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { fetchProjectTeams, grantProjectTeam, revokeProjectTeam } from "@/services/projectsApi";
  import { fetchTeams } from "@/services/teamsApi";
  import type { ProjectSummary } from "@/types";

  /**
   * Assigns teams (and a permission level each) to a project — reachable by
   * anyone who can manage that project, not just global admins.
   */
  let { project, onClose }: { project: ProjectSummary; onClose: () => void } = $props();

  const { t } = useTranslation();
  const grants = useAsyncResource(() => fetchProjectTeams(project.id));
  const teams = useAsyncResource(fetchTeams);
  let selectedTeamId = $state("");
  let selectedPermission = $state<PermissionLevel>("view");

  const assignTeam = useAsyncAction(async (teamId: string, permission: PermissionLevel) => {
    await grantProjectTeam(project.id, teamId, permission);
    grants.reload();
  });

  const unassignTeam = useAsyncAction(async (teamId: string) => {
    await revokeProjectTeam(project.id, teamId);
    grants.reload();
  });

  async function handleAssign() {
    if (!selectedTeamId) return;
    if (await assignTeam.run(selectedTeamId, selectedPermission)) selectedTeamId = "";
  }

  const rows = $derived(grants.data ?? []);
  const assignableTeams = $derived((teams.data ?? []).filter((team) => !rows.some((grant) => grant.teamId === team.id)));
  const error = $derived(grants.error ?? assignTeam.error ?? unassignTeam.error);
</script>

{#snippet permissionOptions()}
  {#each PERMISSION_LEVELS as level (level)}
    <option value={level}>{t(PERMISSION_LABEL_KEY[level])}</option>
  {/each}
{/snippet}

<Modal title={t("teams.modalTitle", { name: project.name })} {onClose}>
  <Hint>{t("teams.visibilityNote")}</Hint>
  <div class="mb-7 flex max-w-[420px] gap-2">
    <select class={SELECT_CLASS} bind:value={selectedTeamId}>
      <option value="">{t("teams.assignPlaceholder")}</option>
      {#each assignableTeams as team (team.id)}
        <option value={team.id}>{team.name}</option>
      {/each}
    </select>
    <select class={SELECT_CLASS} bind:value={selectedPermission}>
      {@render permissionOptions()}
    </select>
    <Button variant="primary" onclick={() => void handleAssign()} disabled={!selectedTeamId}>
      <Icon icon={PlusIcon} size={14} />
      {t("teams.assign")}
    </Button>
  </div>
  {#if error}<ErrorText>{error}</ErrorText>{/if}
  {#if rows.length === 0}
    <EmptyState>{t("teams.noneAssigned")}</EmptyState>
  {:else}
    <List>
      {#each rows as grant (grant.teamId)}
        <ListRow>
          <ListMain>
            <span>{grant.teamName}</span>
          </ListMain>
          <select
            class={SELECT_SM_CLASS}
            value={grant.permission}
            onchange={(event) => void assignTeam.run(grant.teamId, event.currentTarget.value as PermissionLevel)}
          >
            {@render permissionOptions()}
          </select>
          <Button
            variant="ghost"
            size="icon"
            data-tooltip={t("teams.unassign")}
            onclick={() => void unassignTeam.run(grant.teamId)}
          >
            <Icon icon={TrashIcon} size={13} />
          </Button>
        </ListRow>
      {/each}
    </List>
  {/if}
</Modal>

// apps/web/src/ProjectTeamsModal.tsx
import { useEffect, useState } from "react";
import { Modal } from "./Modal.js";
import { PlusIcon, TrashIcon } from "./Icons.js";
import { Button } from "./ui/Button.js";
import { Hint, ErrorText } from "./ui/Alert.js";
import { List, ListMain, ListRow, EmptyState } from "./ui/List.js";
import { SELECT_CLASS, SELECT_SM_CLASS } from "./ui/inputStyles.js";
import type { PermissionLevel, ProjectSummary, ProjectTeamGrant, TeamSummary } from "./types.js";

const PERMISSION_LEVELS: PermissionLevel[] = ["view", "edit", "administrator"];

/** Assigns teams (+ a permission level each) to a project — reachable by anyone who can manage that project, not just global admins. */
function ProjectTeamsModal(props: { project: ProjectSummary; onClose: () => void }) {
  const [grants, setGrants] = useState<ProjectTeamGrant[]>([]);
  const [teams, setTeams] = useState<TeamSummary[]>([]);
  const [pickTeamId, setPickTeamId] = useState("");
  const [pickPermission, setPickPermission] = useState<PermissionLevel>("view");
  const [error, setError] = useState<string | null>(null);

  const refresh = () => {
    fetch(`/api/projects/${props.project.id}/teams`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`load failed (${r.status})`))))
      .then(setGrants)
      .catch((err) => setError((err as Error).message));
  };

  useEffect(refresh, [props.project.id]);
  useEffect(() => {
    fetch("/api/teams")
      .then((r) => (r.ok ? r.json() : []))
      .then(setTeams)
      .catch(() => {});
  }, []);

  const assign = async () => {
    if (!pickTeamId) return;
    const res = await fetch(`/api/projects/${props.project.id}/teams/${pickTeamId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ permission: pickPermission }),
    });
    if (res.ok) {
      setPickTeamId("");
      refresh();
    } else {
      const data = await res.json().catch(() => ({}));
      setError(data.error ?? `Assign failed (${res.status})`);
    }
  };

  const unassign = async (teamId: string) => {
    await fetch(`/api/projects/${props.project.id}/teams/${teamId}`, { method: "DELETE" });
    refresh();
  };

  const setPermission = async (teamId: string, permission: PermissionLevel) => {
    await fetch(`/api/projects/${props.project.id}/teams/${teamId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ permission }),
    });
    refresh();
  };

  const availableTeams = teams.filter((t) => !grants.some((g) => g.teamId === t.id));

  return (
    <Modal title={`Teams — ${props.project.name}`} onClose={props.onClose}>
      <Hint>
        A project with no team assigned is visible to everyone. Assigning a team restricts it to that team's members
        (plus the creator and admins).
      </Hint>
      <div className="mb-7 flex max-w-[420px] gap-2">
        <select className={SELECT_CLASS} value={pickTeamId} onChange={(e) => setPickTeamId(e.target.value)}>
          <option value="">Assign a team…</option>
          {availableTeams.map((t) => (
            <option key={t.id} value={t.id}>
              {t.name}
            </option>
          ))}
        </select>
        <select className={SELECT_CLASS} value={pickPermission} onChange={(e) => setPickPermission(e.target.value as PermissionLevel)}>
          {PERMISSION_LEVELS.map((level) => (
            <option key={level} value={level}>
              {level}
            </option>
          ))}
        </select>
        <Button variant="primary" onClick={assign} disabled={!pickTeamId}>
          <PlusIcon size={14} /> Assign
        </Button>
      </div>
      {error && <ErrorText>{error}</ErrorText>}
      {grants.length === 0 ? (
        <EmptyState>No teams assigned — visible to everyone.</EmptyState>
      ) : (
        <List>
          {grants.map((g) => (
            <ListRow key={g.teamId}>
              <ListMain>
                <span>{g.teamName}</span>
              </ListMain>
              <select
                className={SELECT_SM_CLASS}
                value={g.permission}
                onChange={(e) => setPermission(g.teamId, e.target.value as PermissionLevel)}
              >
                {PERMISSION_LEVELS.map((level) => (
                  <option key={level} value={level}>
                    {level}
                  </option>
                ))}
              </select>
              <Button variant="ghost" size="icon" data-tooltip="Unassign" onClick={() => unassign(g.teamId)}>
                <TrashIcon size={13} />
              </Button>
            </ListRow>
          ))}
        </List>
      )}
    </Modal>
  );
}

export { ProjectTeamsModal };
export default ProjectTeamsModal;
