// apps/web/src/features/editor/nodes/ZoneNode.svelte
<script lang="ts" module>
  const DEFAULT_COLOR = "#f59e0b";
</script>

<script lang="ts">
  import { NodeResizer, type NodeProps } from "@xyflow/svelte";
  import { MAX_NAME_LENGTH } from "@athanordb/shared";
  import { autofocus } from "@/actions/autofocus";
  import ColorSwatchPicker from "@/components/inputs/ColorSwatchPicker.svelte";
  import { INPUT_XS_CLASS } from "@/components/ui/inputStyles";
  import type { ZoneNodeType } from "@/features/editor/nodes/nodeTypes";
  import { useDraftValue } from "@/hooks/draftValue.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";

  let { data, selected = false }: NodeProps<ZoneNodeType> = $props();

  const { t } = useTranslation();
  const zone = $derived(data.zone);
  let editing = $state(false);
  const draft = useDraftValue(
    () => data.zone.label,
    (next) => data.onLabelChange(next ?? ""),
  );
  const color = $derived(zone.style?.color ?? DEFAULT_COLOR);
</script>

<NodeResizer
  minWidth={80}
  minHeight={80}
  isVisible={selected && !data.readOnly}
  onResizeEnd={(_, params) => data.onResize({ x: params.x, y: params.y }, { width: params.width, height: params.height })}
/>
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="relative box-border h-full w-full rounded-lg"
  style:background="{color}1f"
  style:border="1.5px dashed {zone.style?.borderColor ?? color}"
  ondblclick={() => {
    if (!data.readOnly) editing = true;
  }}
>
  <div class="absolute left-2.5 top-2 flex items-center gap-1.5">
    {#if editing}
      <input
        use:autofocus
        class={`nodrag ${INPUT_XS_CLASS} text-[calc(12.5px_*_var(--canvas-font-scale))] font-bold`}
        bind:value={draft.value}
        onblur={() => {
          draft.commit();
          editing = false;
        }}
        maxlength={MAX_NAME_LENGTH}
        onkeydown={(event) => {
          draft.handleKeyDown(event);
          if (event.key === "Enter") editing = false;
          if (event.key === "Escape") {
            draft.setValue(zone.label);
            editing = false;
          }
        }}
      />
    {:else}
      <span
        class="text-[calc(12.5px_*_var(--canvas-font-scale))] font-bold tracking-[-0.01em]"
        style:color
        data-tooltip={data.readOnly ? undefined : t("node.doubleClickToRename")}
      >
        {zone.label}
      </span>
    {/if}
    {#if !data.readOnly}
      <ColorSwatchPicker
        value={color}
        onChange={data.onColorChange}
        palette={data.palette}
        onPaletteChange={data.onPaletteChange}
        triggerClassName="h-[15px] w-[15px] cursor-pointer rounded-full border-[1.5px] border-white/80 bg-none p-0 shadow-xs"
        tooltip={t("zone.color")}
      />
    {/if}
  </div>
</div>

// apps/web/src/ZoneNode.tsx
import { memo, useState } from "react";
import { NodeResizer, type Node, type NodeProps } from "@xyflow/react";
import { MAX_NAME_LENGTH, type Zone } from "@athanordb/shared";
import { ColorSwatchPicker } from "./ColorSwatchPicker.js";
import { INPUT_XS_CLASS } from "./ui/inputStyles.js";

export interface ZoneNodeData {
  zone: Zone;
  palette: string[];
  onPaletteChange: (palette: string[]) => void;
  onLabelChange: (label: string) => void;
  onColorChange: (color: string) => void;
  onResize: (position: { x: number; y: number }, size: { width: number; height: number }) => void;
  [key: string]: unknown;
}

export type ZoneNodeType = Node<ZoneNodeData, "zone">;

const DEFAULT_COLOR = "#f59e0b";

function ZoneNodeImpl({ data, selected }: NodeProps<ZoneNodeType>) {
  const { zone } = data;
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(zone.label);
  const color = zone.style?.color ?? DEFAULT_COLOR;

  const commit = () => {
    setEditing(false);
    const trimmed = draft.trim();
    if (trimmed && trimmed !== zone.label) data.onLabelChange(trimmed);
    else setDraft(zone.label);
  };

  return (
    <>
      <NodeResizer
        minWidth={80}
        minHeight={80}
        isVisible={selected}
        onResizeEnd={(_, params) =>
          data.onResize({ x: params.x, y: params.y }, { width: params.width, height: params.height })
        }
      />
      <div
        className="relative box-border h-full w-full rounded-lg"
        style={{
          background: `${color}1f`,
          border: `1.5px dashed ${zone.style?.borderColor ?? color}`,
        }}
        onDoubleClick={() => setEditing(true)}
      >
        <div className="absolute left-2.5 top-2 flex items-center gap-1.5">
          {editing ? (
            <input
              autoFocus
              className={`nodrag ${INPUT_XS_CLASS} text-[calc(12.5px_*_var(--canvas-font-scale))] font-bold`}
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onBlur={commit}
              maxLength={MAX_NAME_LENGTH}
              onKeyDown={(e) => {
                if (e.key === "Enter") commit();
                if (e.key === "Escape") {
                  setDraft(zone.label);
                  setEditing(false);
                }
              }}
            />
          ) : (
            <span
              className="text-[calc(12.5px_*_var(--canvas-font-scale))] font-bold tracking-[-0.01em]"
              style={{ color }}
              data-tooltip="Double-click to rename"
            >
              {zone.label}
            </span>
          )}
          <ColorSwatchPicker
            value={color}
            onChange={data.onColorChange}
            palette={data.palette}
            onPaletteChange={data.onPaletteChange}
            triggerClassName="h-[15px] w-[15px] cursor-pointer rounded-full border-[1.5px] border-white/80 bg-none p-0 shadow-xs"
            tooltip="Zone color"
          />
        </div>
      </div>
    </>
  );
}

export const ZoneNode = memo(ZoneNodeImpl);
