// apps/web/src/CanvasArea.tsx
import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type MouseEvent as ReactMouseEvent,
  type MutableRefObject,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";
import {
  ReactFlow,
  useReactFlow,
  useStore,
  Background,
  MiniMap,
  Panel,
  PanOnScrollMode,
  SelectionMode,
  type Connection,
  type NodeChange,
} from "@xyflow/react";
import type { Awareness } from "y-protocols/awareness.js";
import type { DetailLevel } from "@athanordb/shared";
import { TableNode } from "./TableNode.js";
import { RefEdge, type RefEdgeType } from "./RefEdge.js";
import { ZoneNode } from "./ZoneNode.js";
import { StickyNoteNode } from "./StickyNoteNode.js";
import { CursorNode, type CursorNodeType } from "./CursorNode.js";
import { ChevronRightIcon, FrameIcon, LinkIcon, MinimapIcon, NoteIcon, PuzzleIcon, TableIcon } from "./Icons.js";
import { FONT_SCALE_MAX, FONT_SCALE_MIN, FONT_SCALE_STEP, loadShowMinimap, loadViewport, saveShowMinimap, viewportKey } from "./localPrefs.js";
import { CONTEXT_MENU_CLASS, CONTEXT_MENU_ITEM_CLASS } from "./ui/contextMenuStyles.js";
import {
  CANVAS_TOOLBAR_CLASS,
  CANVAS_TOOLBAR_DIVIDER_CLASS,
  CANVAS_TOOLBAR_ICON_BTN_CLASS,
  CANVAS_TOOLBAR_SEGMENT_ACTIVE_CLASS,
  CANVAS_TOOLBAR_SEGMENT_CLASS,
  CANVAS_TOOLBAR_TOGGLE_ACTIVE_CLASS,
} from "./ui/canvasToolbarStyles.js";
import { SWATCH_CELL_CLASS } from "./ColorSwatchPicker.js";
import type { CanvasCommandContribution, ResolvedContribution } from "./plugins/types.js";
import type { AllNodes, CanvasExportHandle, CanvasNode } from "./types.js";

const nodeTypes = { table: TableNode, zone: ZoneNode, sticky: StickyNoteNode, cursor: CursorNode };
const edgeTypes = { ref: RefEdge };

/**
 * Split out from `ProjectEditor` so it can call `useReactFlow()` — that hook
 * only works inside a `ReactFlowProvider`, and `screenToFlowPosition` is what
 * turns a mouse move into the flow-space coordinate broadcast as this user's
 * cursor, so peers' `CursorNode`s land in the right spot regardless of each
 * viewer's own pan/zoom.
 */
interface CanvasContextMenuState {
  screenX: number;
  screenY: number;
  flowPosition: { x: number; y: number };
}

/** Floating swatch row shown above the canvas once 2+ tables are selected — picking a color applies it to every selected table's header at once. */
function SelectionColorToolbar(props: { count: number; palette: string[]; onPick: (color: string) => void }) {
  return (
    <Panel position="top-center" className="nodrag nopan">
      <div className="flex flex-col items-start gap-1.5 rounded-md border border-border bg-surface-raised px-2.5 py-2 shadow-lg">
        <span className="whitespace-nowrap text-xs text-text-muted">{props.count} tables selected</span>
        <div className="grid grid-cols-10 gap-1.5">
          {props.palette.map((c) => (
            <button
              key={c}
              type="button"
              className={SWATCH_CELL_CLASS}
              style={{ background: c }}
              onClick={() => props.onPick(c)}
              data-tooltip={c}
            />
          ))}
        </div>
      </div>
    </Panel>
  );
}

/** Right-click-on-empty-canvas menu — the only way to add a table/zone/sticky note besides editing DBML directly. */
function CanvasContextMenu(props: {
  menu: CanvasContextMenuState;
  onAddTable: (position: { x: number; y: number }) => void;
  onAddZone: (position: { x: number; y: number }) => void;
  onAddNote: (position: { x: number; y: number }) => void;
  onClose: () => void;
}) {
  const { menu } = props;
  const run = (fn: (position: { x: number; y: number }) => void) => {
    fn(menu.flowPosition);
    props.onClose();
  };
  return (
    <div className={CONTEXT_MENU_CLASS} style={{ left: menu.screenX, top: menu.screenY }} onClick={(e) => e.stopPropagation()}>
      <button className={CONTEXT_MENU_ITEM_CLASS} onClick={() => run(props.onAddTable)}>
        <TableIcon size={14} /> Add table
      </button>
      <button className={CONTEXT_MENU_ITEM_CLASS} onClick={() => run(props.onAddZone)}>
        <FrameIcon size={14} /> Add zone
      </button>
      <button className={CONTEXT_MENU_ITEM_CLASS} onClick={() => run(props.onAddNote)}>
        <NoteIcon size={14} /> Add sticky note
      </button>
    </div>
  );
}

const DETAIL_LEVEL_LABEL: Record<DetailLevel, string> = { compact: "Compact", standard: "Standard", full: "Full" };
const DETAIL_LEVEL_HINT: Record<DetailLevel, string> = {
  compact: "Show only key fields",
  standard: "Show primary/foreign keys",
  full: "Show all fields",
};

/**
 * Popover behaviour shared by every dropdown in the floating toolbar (detail
 * level, zoom, plugins). The menu is portalled to `document.body` and anchored
 * *above* its trigger, since the toolbar sits at the bottom of the canvas.
 */
function ToolbarMenu(props: {
  /** Classes for the trigger button itself — it must be a real box, since the menu is anchored off its rect. */
  triggerClassName: (open: boolean) => string;
  triggerContent: ReactNode;
  tooltip: string;
  minWidth?: number;
  children: (close: () => void) => ReactNode;
}) {
  const [open, setOpen] = useState(false);
  const [menuPos, setMenuPos] = useState<{ x: number; bottom: number } | null>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    // "click", not "mousedown": see ColorSwatchPicker — React Flow's pane
    // stops mousedown propagation for its own pan/drag handling.
    const handleOutsideClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (menuRef.current?.contains(target) || triggerRef.current?.contains(target)) return;
      setOpen(false);
    };
    const onKeyDown = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false);
    window.addEventListener("click", handleOutsideClick);
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("click", handleOutsideClick);
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  const toggle = () => {
    if (!open && triggerRef.current) {
      const rect = triggerRef.current.getBoundingClientRect();
      const width = props.minWidth ?? 180;
      setMenuPos({
        x: Math.min(Math.max(8, rect.left), window.innerWidth - width - 8),
        bottom: window.innerHeight - rect.top + 8,
      });
    }
    setOpen((v) => !v);
  };

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        className={props.triggerClassName(open)}
        onClick={(e) => {
          e.stopPropagation();
          toggle();
        }}
        data-tooltip={props.tooltip}
        data-tooltip-pos="bottom"
      >
        {props.triggerContent}
      </button>
      {open &&
        menuPos &&
        createPortal(
          <div
            ref={menuRef}
            className={CONTEXT_MENU_CLASS}
            style={{ left: menuPos.x, bottom: menuPos.bottom, minWidth: props.minWidth ?? 180 }}
          >
            {props.children(() => setOpen(false))}
          </div>,
          document.body,
        )}
    </>
  );
}

/** Detail-level toolbar control — a single button opening a popover list instead of three always-visible segments, so the floating toolbar stays compact. */
function DetailLevelDropdown(props: { value: DetailLevel | null; onChange: (level: DetailLevel) => void }) {
  return (
    <ToolbarMenu
      tooltip="Detail level"
      triggerClassName={(open) => `${CANVAS_TOOLBAR_SEGMENT_CLASS} gap-1 ${open ? CANVAS_TOOLBAR_SEGMENT_ACTIVE_CLASS : ""}`}
      triggerContent={
        <>
          {props.value ? DETAIL_LEVEL_LABEL[props.value] : "Detail"}
          <ChevronRightIcon size={11} className="-rotate-90" />
        </>
      }
    >
      {(close) =>
        (["compact", "standard", "full"] as const).map((level) => (
          <button
            key={level}
            type="button"
            className={`${CONTEXT_MENU_ITEM_CLASS} justify-between ${level === props.value ? "text-text" : ""}`}
            onClick={() => {
              props.onChange(level);
              close();
            }}
            data-tooltip={DETAIL_LEVEL_HINT[level]}
          >
            {DETAIL_LEVEL_LABEL[level]}
            {level === props.value && <span className="text-primary">✓</span>}
          </button>
        ))
      }
    </ToolbarMenu>
  );
}

const ZOOM_PRESETS = [0.5, 1, 2] as const;

/** Zoom cluster: −, a percentage button opening fit/preset choices, +. Mirrors Figma's bottom-right zoom control. */
function ZoomControls(props: { selectedIds: string[] }) {
  const { zoomIn, zoomOut, zoomTo, fitView } = useReactFlow();
  const zoom = useStore((state) => state.transform[2]);

  return (
    <>
      <button
        type="button"
        className={CANVAS_TOOLBAR_ICON_BTN_CLASS}
        onClick={() => zoomOut({ duration: 120 })}
        data-tooltip="Zoom out"
        data-tooltip-pos="bottom"
        aria-label="Zoom out"
      >
        <span className="text-[15px] leading-none">−</span>
      </button>
      <ToolbarMenu
        tooltip="Zoom"
        minWidth={170}
        triggerClassName={(open) =>
          `${CANVAS_TOOLBAR_SEGMENT_CLASS} min-w-[52px] justify-center ${open ? CANVAS_TOOLBAR_SEGMENT_ACTIVE_CLASS : ""}`
        }
        triggerContent={`${Math.round(zoom * 100)}%`}
      >
        {(close) => (
          <>
            <button
              type="button"
              className={`${CONTEXT_MENU_ITEM_CLASS} justify-between`}
              onClick={() => {
                fitView({ padding: 0.15, duration: 200 });
                close();
              }}
            >
              Zoom to fit <span className="text-text-muted">Shift+1</span>
            </button>
            <button
              type="button"
              className={`${CONTEXT_MENU_ITEM_CLASS} justify-between disabled:opacity-40`}
              disabled={props.selectedIds.length === 0}
              onClick={() => {
                fitView({ padding: 0.3, duration: 200, nodes: props.selectedIds.map((id) => ({ id })) });
                close();
              }}
            >
              Zoom to selection
            </button>
            {ZOOM_PRESETS.map((preset) => (
              <button
                key={preset}
                type="button"
                className={CONTEXT_MENU_ITEM_CLASS}
                onClick={() => {
                  zoomTo(preset, { duration: 200 });
                  close();
                }}
              >
                {preset * 100}%
              </button>
            ))}
          </>
        )}
      </ToolbarMenu>
      <button
        type="button"
        className={CANVAS_TOOLBAR_ICON_BTN_CLASS}
        onClick={() => zoomIn({ duration: 120 })}
        data-tooltip="Zoom in"
        data-tooltip-pos="bottom"
        aria-label="Zoom in"
      >
        <span className="text-[15px] leading-none">+</span>
      </button>
    </>
  );
}

/** Plugin menu — every canvas command contributed by a plugin, plus a way into the manager. */
function PluginMenu(props: {
  commands: ResolvedContribution<CanvasCommandContribution>[];
  onRun: (command: ResolvedContribution<CanvasCommandContribution>) => void;
  onOpenPlugins: () => void;
}) {
  return (
    <ToolbarMenu
      tooltip="Plugin commands"
      minWidth={240}
      triggerClassName={(open) => `${CANVAS_TOOLBAR_ICON_BTN_CLASS} ${open ? CANVAS_TOOLBAR_SEGMENT_ACTIVE_CLASS : ""}`}
      triggerContent={<PuzzleIcon size={14} />}
    >
      {(close) => (
        <>
          {props.commands.length === 0 && (
            <span className="block px-2.5 py-1.5 text-[12px] text-text-muted">No canvas command installed</span>
          )}
          {props.commands.map((command) => (
            <button
              key={command.key}
              type="button"
              className={`${CONTEXT_MENU_ITEM_CLASS} justify-between`}
              onClick={() => {
                props.onRun(command);
                close();
              }}
              data-tooltip={command.contribution.description}
            >
              {command.contribution.label}
              <span className="ml-2 shrink-0 text-[10px] text-text-muted">
                {command.contribution.shortcut ?? (command.source === "user" ? command.plugin.name : "")}
              </span>
            </button>
          ))}
          <span className="my-1 block h-px bg-border" />
          <button
            type="button"
            className={CONTEXT_MENU_ITEM_CLASS}
            onClick={() => {
              props.onOpenPlugins();
              close();
            }}
          >
            Manage plugins…
          </button>
        </>
      )}
    </ToolbarMenu>
  );
}

export function CanvasArea(props: {
  nodes: CanvasNode[];
  cursorNodes: CursorNodeType[];
  edges: RefEdgeType[];
  onNodesChange: (changes: NodeChange<AllNodes>[]) => void;
  onEdgesDelete?: (edges: RefEdgeType[]) => void;
  /** Fires when the user drags a field handle to another field handle — creates a new ref (FK). */
  onConnect?: (connection: Connection) => void;
  awareness: Awareness | null;
  onAddTable: (position: { x: number; y: number }) => void;
  onAddZone: (position: { x: number; y: number }) => void;
  onAddNote: (position: { x: number; y: number }) => void;
  /** Applies a header color to every currently-selected table at once — shown by the selection toolbar once 2+ tables are selected. */
  onSetTablesColor: (tableIds: string[], color: string) => void;
  palette: string[];
  fontScale: number;
  onAdjustFontScale: (delta: number) => void;
  activeDetailLevel: DetailLevel | null;
  onSetDetailLevel: (level: DetailLevel) => void;
  highlightLinks: boolean;
  onHighlightLinksChange: (highlight: boolean) => void;
  /** Fires on table hover start/end (null on leave) — lets the parent highlight that table's refs. */
  onTableHoverChange: (tableId: string | null) => void;
  projectId: string;
  /** Session's stable user id — only used to namespace the saved-viewport localStorage key, not an identity/authorship field. */
  viewportUserId: string;
  exportRef: MutableRefObject<CanvasExportHandle | null>;
  /** Canvas commands contributed by plugins, shown in the toolbar's plugin menu. */
  canvasCommands: ResolvedContribution<CanvasCommandContribution>[];
  onRunCanvasCommand: (command: ResolvedContribution<CanvasCommandContribution>) => void;
  onOpenPlugins: () => void;
  /** Transient feedback from the last plugin command, shown above the toolbar. */
  statusMessage: string | null;
}) {
  const { screenToFlowPosition, fitView, getViewport, setViewport } = useReactFlow();
  const [menu, setMenu] = useState<CanvasContextMenuState | null>(null);
  const [showMinimap, setShowMinimap] = useState(loadShowMinimap);
  // Lazy initializer: read once at mount, not on every render — this decides
  // whether the very first render asks React Flow to `fitView` or restore
  // exactly where this user left the canvas last time.
  const [initialViewport] = useState(() => loadViewport(props.projectId, props.viewportUserId));

  // Exposed imperatively (not via props/state) because the Export dialog
  // that triggers this lives outside the ReactFlowProvider this component is
  // rendered inside — it has no other way to reach `fitView`/`getViewport`.
  // Published from an effect rather than during render: writing to someone
  // else's ref mid-render is exactly the kind of side effect React's rules
  // forbid, and the handle is only ever needed later, on a user action.
  const { exportRef } = props;
  useEffect(() => {
    exportRef.current = {
      capture: async (format) => {
        const paneEl = document.querySelector(".react-flow__pane") as HTMLElement | null;
        if (!paneEl) throw new Error("Canvas is not ready yet");
        const prevViewport = getViewport();
        // Fit the *entire* diagram into the current pane size first — reuses
        // React Flow's own (already correct) fit logic instead of hand-rolling
        // bounds/zoom math, and means the export isn't just whatever happens
        // to be on-screen from the user's last pan/zoom.
        fitView({ padding: 0.15, duration: 0 });
        await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
        const width = paneEl.clientWidth;
        const height = paneEl.clientHeight;
        try {
          // html-to-image is only needed for this one action — dynamic import
          // keeps it out of the bundle everyone loads just to view a diagram.
          const { toPng, toSvg } = await import("html-to-image");
          const options = { backgroundColor: "#17181b", width, height, pixelRatio: format === "png" ? 2 : 1 };
          const dataUrl = format === "png" ? await toPng(paneEl, options) : await toSvg(paneEl, options);
          return { dataUrl, width, height };
        } finally {
          setViewport(prevViewport, { duration: 0 });
        }
      },
    };
    return () => {
      exportRef.current = null;
    };
  }, [exportRef, fitView, getViewport, setViewport]);

  const handleMouseMove = (e: ReactMouseEvent) => {
    props.awareness?.setLocalStateField("cursor", screenToFlowPosition({ x: e.clientX, y: e.clientY }));
  };
  const handleMouseLeave = () => {
    props.awareness?.setLocalStateField("cursor", null);
  };

  const closeMenu = useCallback(() => setMenu(null), []);

  const toggleMinimap = useCallback(() => {
    setShowMinimap((v) => {
      const next = !v;
      saveShowMinimap(next);
      return next;
    });
  }, []);

  const { onTableHoverChange } = props;
  const handleNodeMouseEnter = useCallback(
    (_e: ReactMouseEvent, node: AllNodes) => {
      if (node.type === "table") onTableHoverChange(node.id);
    },
    [onTableHoverChange],
  );
  const handleNodeMouseLeave = useCallback(
    (_e: ReactMouseEvent, node: AllNodes) => {
      if (node.type === "table") onTableHoverChange(null);
    },
    [onTableHoverChange],
  );

  const handlePaneContextMenu = useCallback(
    (e: ReactMouseEvent | MouseEvent) => {
      e.preventDefault();
      setMenu({
        screenX: e.clientX,
        screenY: e.clientY,
        flowPosition: screenToFlowPosition({ x: e.clientX, y: e.clientY }),
      });
    },
    [screenToFlowPosition],
  );

  useEffect(() => {
    if (!menu) return;
    const onKeyDown = (e: KeyboardEvent) => e.key === "Escape" && closeMenu();
    window.addEventListener("click", closeMenu);
    window.addEventListener("wheel", closeMenu);
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("click", closeMenu);
      window.removeEventListener("wheel", closeMenu);
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [menu, closeMenu]);

  /**
   * Where the toolbar's insert buttons drop a new node: the centre of the
   * visible pane, so it lands where the user is looking rather than at a fixed
   * flow coordinate they may have panned away from.
   */
  const paneCenter = useCallback(() => {
    const pane = document.querySelector(".react-flow__pane") as HTMLElement | null;
    const rect = pane?.getBoundingClientRect();
    const x = rect ? rect.left + rect.width / 2 : window.innerWidth / 2;
    const y = rect ? rect.top + rect.height / 2 : window.innerHeight / 2;
    return screenToFlowPosition({ x, y });
  }, [screenToFlowPosition]);

  const nodes: AllNodes[] = [...props.nodes, ...props.cursorNodes];
  const selectedTableIds = props.nodes.filter((n) => n.type === "table" && n.selected).map((n) => n.id);

  return (
    <div
      className="min-w-0 flex-1 bg-bg-canvas"
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      style={{ "--canvas-font-scale": props.fontScale } as CSSProperties}
    >
      <ReactFlow
        nodes={nodes}
        edges={props.edges}
        onNodesChange={props.onNodesChange}
        onEdgesDelete={props.onEdgesDelete}
        onConnect={props.onConnect}
        onPaneContextMenu={handlePaneContextMenu}
        onNodeMouseEnter={handleNodeMouseEnter}
        onNodeMouseLeave={handleNodeMouseLeave}
        onMoveStart={closeMenu}
        onMoveEnd={(_, viewport) =>
          localStorage.setItem(viewportKey(props.projectId, props.viewportUserId), JSON.stringify(viewport))
        }
        nodeTypes={nodeTypes}
        edgeTypes={edgeTypes}
        deleteKeyCode={["Backspace", "Delete"]}
        snapToGrid
        snapGrid={[10, 10]}
        fitView={!initialViewport}
        defaultViewport={initialViewport ?? undefined}
        selectionOnDrag
        selectionMode={SelectionMode.Partial}
        panOnDrag={[1, 2]}
        panOnScroll
        panOnScrollMode={PanOnScrollMode.Free}
        zoomOnScroll={false}
        zoomActivationKeyCode="Control"
        minZoom={0.05}
      >
        <Background color="#33353c" gap={20} />
        <Panel position="bottom-center" className="nodrag nopan pointer-events-none !bottom-4 flex flex-col items-center gap-2">
          {props.statusMessage && (
            <span className="pointer-events-auto rounded-full border border-border bg-surface-raised/95 px-3 py-1 text-[11.5px] text-text-secondary shadow-lg backdrop-blur-md">
              {props.statusMessage}
            </span>
          )}
          <div className={CANVAS_TOOLBAR_CLASS}>
            <button
              type="button"
              className={CANVAS_TOOLBAR_ICON_BTN_CLASS}
              onClick={() => props.onAddTable(paneCenter())}
              data-tooltip="Add table"
              data-tooltip-pos="bottom"
              aria-label="Add table"
            >
              <TableIcon size={15} />
            </button>
            <button
              type="button"
              className={CANVAS_TOOLBAR_ICON_BTN_CLASS}
              onClick={() => props.onAddZone(paneCenter())}
              data-tooltip="Add zone"
              data-tooltip-pos="bottom"
              aria-label="Add zone"
            >
              <FrameIcon size={15} />
            </button>
            <button
              type="button"
              className={CANVAS_TOOLBAR_ICON_BTN_CLASS}
              onClick={() => props.onAddNote(paneCenter())}
              data-tooltip="Add sticky note"
              data-tooltip-pos="bottom"
              aria-label="Add sticky note"
            >
              <NoteIcon size={15} />
            </button>

            <span className={CANVAS_TOOLBAR_DIVIDER_CLASS} />
            <DetailLevelDropdown value={props.activeDetailLevel} onChange={props.onSetDetailLevel} />
            <span className={CANVAS_TOOLBAR_DIVIDER_CLASS} />
            <div className="flex items-center" data-tooltip="Canvas text size" data-tooltip-pos="bottom">
              <button
                type="button"
                className={`${CANVAS_TOOLBAR_SEGMENT_CLASS} !px-1.5 hover:text-text`}
                onClick={() => props.onAdjustFontScale(-FONT_SCALE_STEP)}
                disabled={props.fontScale <= FONT_SCALE_MIN}
                data-tooltip="Réduire la taille du texte"
                data-tooltip-pos="bottom"
              >
                <span className="text-[11px] font-bold leading-none">A⁻</span>
              </button>
              <span className="min-w-[34px] text-center text-[11.5px] font-mono font-medium text-text-muted">{Math.round(props.fontScale * 100)}%</span>
              <button
                type="button"
                className={`${CANVAS_TOOLBAR_SEGMENT_CLASS} !px-1.5 hover:text-text`}
                onClick={() => props.onAdjustFontScale(FONT_SCALE_STEP)}
                disabled={props.fontScale >= FONT_SCALE_MAX}
                data-tooltip="Augmenter la taille du texte"
                data-tooltip-pos="bottom"
              >
                <span className="text-[13px] font-bold leading-none">A⁺</span>
              </button>

            </div>

            <span className={CANVAS_TOOLBAR_DIVIDER_CLASS} />
            <button
              type="button"
              className={`${CANVAS_TOOLBAR_ICON_BTN_CLASS} ${props.highlightLinks ? CANVAS_TOOLBAR_TOGGLE_ACTIVE_CLASS : ""}`}
              onClick={() => props.onHighlightLinksChange(!props.highlightLinks)}
              data-tooltip={props.highlightLinks ? "Hide link and cardinality highlighting" : "Highlight links and cardinalities"}
              data-tooltip-pos="bottom"
              aria-label="Toggle link highlight"
            >
              <LinkIcon size={14} />
            </button>
            <button
              type="button"
              className={`${CANVAS_TOOLBAR_ICON_BTN_CLASS} ${showMinimap ? CANVAS_TOOLBAR_TOGGLE_ACTIVE_CLASS : ""}`}
              onClick={toggleMinimap}
              data-tooltip={showMinimap ? "Hide minimap" : "Show minimap"}
              data-tooltip-pos="bottom"
              aria-label="Toggle minimap"
            >
              <MinimapIcon size={14} />
            </button>

            <span className={CANVAS_TOOLBAR_DIVIDER_CLASS} />
            <ZoomControls selectedIds={selectedTableIds} />

            <span className={CANVAS_TOOLBAR_DIVIDER_CLASS} />
            <PluginMenu
              commands={props.canvasCommands}
              onRun={props.onRunCanvasCommand}
              onOpenPlugins={props.onOpenPlugins}
            />
          </div>
        </Panel>
        {showMinimap && (
          <MiniMap pannable zoomable bgColor="#1f2024" nodeColor="#4b4d8a" maskColor="rgba(23,24,27,0.75)" />
        )}
        {selectedTableIds.length > 1 && (
          <SelectionColorToolbar
            count={selectedTableIds.length}
            palette={props.palette}
            onPick={(color) => props.onSetTablesColor(selectedTableIds, color)}
          />
        )}
      </ReactFlow>
      {menu && (
        <CanvasContextMenu
          menu={menu}
          onAddTable={props.onAddTable}
          onAddZone={props.onAddZone}
          onAddNote={props.onAddNote}
          onClose={closeMenu}
        />
      )}
    </div>
  );
}

// apps/web/src/features/editor/canvas/CanvasArea.svelte
<script lang="ts" module>
  import TableNode from "@/features/editor/nodes/TableNode.svelte";
  import ZoneNode from "@/features/editor/nodes/ZoneNode.svelte";
  import StickyNoteNode from "@/features/editor/nodes/StickyNoteNode.svelte";
  import EnumNode from "@/features/editor/nodes/EnumNode.svelte";
  import TableGroupNode from "@/features/editor/nodes/TableGroupNode.svelte";
  import RefEdge from "@/features/editor/edges/RefEdge.svelte";
  import type { NodeTypes, EdgeTypes } from "@xyflow/svelte";

  const nodeTypes = {
    table: TableNode,
    zone: ZoneNode,
    sticky: StickyNoteNode,
    enum: EnumNode,
    tablegroup: TableGroupNode,
  } as unknown as NodeTypes;
  const edgeTypes = { ref: RefEdge } as unknown as EdgeTypes;

  const GRID_SIZE = 10;
  /** Past this many pixels, a right-button press was a pan, not a click asking for the context menu. */
  const CONTEXT_MENU_DRAG_TOLERANCE_PX = 3;
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import {
    Background,
    BackgroundVariant,
    Panel,
    SvelteFlow,
    useStore,
    useSvelteFlow,
    type Connection,
  } from "@xyflow/svelte";
  import type { Awareness } from "y-protocols/awareness.js";
  import type { DetailLevel } from "@athanordb/shared";
  import RemoteCursorsLayer from "@/features/collaboration/RemoteCursorsLayer.svelte";
  import type { RemoteSelector } from "@/features/collaboration/awarenessStates.svelte";
  import { useEscapeKey } from "@/hooks/escapeKey.svelte";
  import { loadGridStyle, loadSnapToGrid } from "@/utils/preferences";
  import type { CanvasCommandContribution, ResolvedContribution } from "@/features/plugins/types";
  import type { CanvasExportHandle, CanvasNavigateHandle, CanvasNode } from "@/types";
  import type { RefEdgeType } from "@/features/editor/edges/refEdgeTypes";
  import type { CanvasNodesState } from "@/features/editor/hooks/useCanvasNodes/canvasNodes.svelte";
  import type { EditorViewMode } from "@/features/editor/mcd/ViewModeToggle.svelte";
  import { recordDuration, time } from "@/utils/perfMonitor";
  import CanvasContextMenu, { type CanvasContextMenuState } from "./CanvasContextMenu.svelte";
  import CanvasSearchPanel from "./CanvasSearchPanel.svelte";
  import CanvasToolbar from "./CanvasToolbar.svelte";
  import CanvasZoomBar from "./CanvasZoomBar.svelte";
  import CanvasMinimap from "./CanvasMinimap.svelte";
  import SelectionColorToolbar from "./SelectionColorToolbar.svelte";
  import { CANVAS_VIEWPORT_PROPS, jumpToTableNode, useSharedMinimapVisible, useSharedViewport } from "./canvasViewport.svelte";
  import { computeHighlightedFields } from "./highlightedFields";
  import { registerNodeInternalsFlush } from "./nodeInternalsBatch";
  import { createLassoSelection } from "./lassoSelection";
  import { publishSelecting } from "./selectionDragState.svelte";
  import { createCanvasImageExport } from "./canvasImageExport";
  import { useCanvasSearch } from "./canvasSearch.svelte";
  import { createCollaboratorCursor } from "./collaboratorCursor";
  import { useCanvasDeleteKey } from "./canvasDeleteKey.svelte";
  import { canvasMinimapNodeColor } from "./canvasMinimapColor";
  import { quantizeZoom, setCanvasContext } from "./canvasContext";
  import type { CanvasInsertTool, CanvasPoint } from "./types";

  /**
   * The diagram surface.
   *
   * Split out from `ProjectEditor` so it can use the flow's helpers
   * (`screenToFlowPosition`, `setCenter`, …) — they need the flow store, which
   * lives under the `SvelteFlowProvider` `ProjectEditor` wraps around this.
   * `screenToFlowPosition` is what turns a mouse move into the flow-space
   * coordinate broadcast as this user's cursor, so peers' `RemoteCursorsLayer`
   * renders it in the right spot regardless of each viewer's own pan/zoom.
   */
  let props: {
    /** The canvas's node state — the flow is bound two-way to its `nodes`. */
    nodesState: CanvasNodesState;
    edges: RefEdgeType[];
    /** Ids of the selected table nodes, derived once in `ProjectEditor`. */
    selectedTableIds: string[];
    /** tableId -> the remote collaborators who currently have that table selected. */
    remoteSelections: Map<string, RemoteSelector[]>;
    /** Deletes refs — the relation half of the Delete key. */
    onDeleteEdges: (edgeIds: string[]) => void;
    /** Fires when the user drags a field handle to another field handle — creates a new ref (FK). */
    onConnect: (connection: Connection) => void;
    awareness: Awareness | null;
    onAddTable: (position: CanvasPoint) => void;
    onAddZone: (position: CanvasPoint) => void;
    onAddNote: (position: CanvasPoint) => void;
    onAddEnum: (position: CanvasPoint) => void;
    /** Applies a header colour to every currently-selected table at once. */
    onSetTablesColor: (tableIds: string[], color: string) => void;
    /** Bundles the currently-selected tables into a named table group. */
    onGroupTables: (tableIds: string[]) => void;
    palette: string[];
    fontScale: number;
    activeDetailLevel: DetailLevel | null;
    onSetDetailLevel: (level: DetailLevel) => void;
    highlightLinks: boolean;
    onHighlightLinksChange: (highlight: boolean) => void;
    showValidationIssues: boolean;
    onShowValidationIssuesChange: (visible: boolean) => void;
    projectId: string;
    /** Session's stable user id — namespaces the saved-viewport key, not an identity field. */
    viewportUserId: string;
    exportRef: { current: CanvasExportHandle | null };
    navigateRef: { current: CanvasNavigateHandle | null };
    canvasCommands: ResolvedContribution<CanvasCommandContribution>[];
    onRunCanvasCommand: (command: ResolvedContribution<CanvasCommandContribution>) => void;
    onOpenPlugins: () => void;
    /** Transient feedback from the last plugin command, shown above the toolbar. */
    statusMessage: string | null;
    /** Currently selected edge ID */
    selectedEdgeId: string | null;
    /** Select or unselect an edge */
    onSelectEdge: (edgeId: string | null) => void;
    /** Clears any active column selection when clicking empty canvas space. */
    onClearFieldSelection: () => void;
    /** False for a `view` grant — drops every editing affordance rather than offering ones whose writes the server discards. */
    canWrite: boolean;
    viewMode: EditorViewMode;
    onSetViewMode: (mode: EditorViewMode) => void;
  } = $props();

  const flow = useSvelteFlow<CanvasNode, RefEdgeType>();
  // `$derived`, not a plain call: under a provider, the real store only exists
  // once `<SvelteFlow>` below has mounted and registered it.
  const flowStore = $derived(useStore<CanvasNode, RefEdgeType>());

  let contextMenu = $state.raw<CanvasContextMenuState | null>(null);
  const minimap = useSharedMinimapVisible();
  /**
   * The Figma-style insert tool: pick one on the toolbar, then click anywhere
   * on the canvas to drop it there — and click again, and again, without
   * re-selecting the tool each time. `null` is the ordinary selection mode.
   */
  let activeInsertTool = $state<CanvasInsertTool | null>(null);
  const { initialViewport, onMoveEnd } = useSharedViewport(
    untrack(() => props.projectId),
    untrack(() => props.viewportUserId),
  );
  // Read once per mount, matching how the settings panel presents them: these
  // are "how the canvas behaves" preferences, not live controls.
  const gridStyle = loadGridStyle();
  const snapToGrid = loadSnapToGrid();

  let lassoRect: HTMLDivElement | undefined = $state();

  // One O(edges) pass for the whole canvas, replacing a per-table walk of the
  // edge array — see `highlightedFields.ts`.
  const highlightedFields = $derived(time("canvas.highlightedFields", () => computeHighlightedFields(props.edges)));
  const zoom = $derived(quantizeZoom(flowStore.viewport.zoom));

  setCanvasContext({
    get highlightedFields() {
      return highlightedFields;
    },
    get remoteSelections() {
      return props.remoteSelections;
    },
    get zoom() {
      return zoom;
    },
    deselectAllNodes: () => props.nodesState.setSelection(() => false),
  });

  // One batched re-measure per tick, replacing the separate call each table
  // used to make on its own — see `nodeInternalsBatch.ts`.
  $effect(() =>
    registerNodeInternalsFlush((ids) => {
      const store = untrack(() => flowStore);
      const updates = new Map<string, { id: string; nodeElement: HTMLDivElement; force: boolean }>();
      for (const id of ids) {
        const nodeElement = store.domNode?.querySelector<HTMLDivElement>(`.svelte-flow__node[data-id="${CSS.escape(id)}"]`);
        if (nodeElement) updates.set(id, { id, nodeElement, force: true });
      }
      if (updates.size > 0) requestAnimationFrame(() => store.updateNodeInternals(updates));
    }),
  );

  // Diagnostic-only: how often the flow hands out a new nodes/edges array —
  // visible in the PerfHud as a frequency, not a duration.
  $effect(() => {
    void flowStore.nodes;
    recordDuration("store.nodesIdentityChanged", 0);
  });
  $effect(() => {
    void flowStore.edges;
    recordDuration("store.edgesIdentityChanged", 0);
  });

  // Nothing should stay "as if mid-drag" if this canvas unmounts while a
  // selection drag is somehow still in flight (switching projects, closing
  // the editor).
  $effect(() => () => publishSelecting(false));

  const jumpToTable = (tableId: string) =>
    jumpToTableNode(props.nodesState.nodes, tableId, flow.setCenter, props.nodesState.setSelection.bind(props.nodesState));

  // Imperative handles for the pieces that live outside this canvas (the
  // export dialog, the DBML panel's double-click navigation).
  $effect(() => {
    const exportRef = props.exportRef;
    exportRef.current = createCanvasImageExport(flow);
    return () => {
      exportRef.current = null;
    };
  });
  $effect(() => {
    const navigateRef = props.navigateRef;
    navigateRef.current = { goToTable: (tableId) => void jumpToTable(tableId) };
    return () => {
      navigateRef.current = null;
    };
  });

  const search = useCanvasSearch(() => props.nodesState.nodes, jumpToTable);

  const closeContextMenu = () => (contextMenu = null);

  // The first fit can run before the pane has its final size: the DBML panel
  // mounts in the same tick as the nodes, and the flow only learns its new
  // width from a ResizeObserver afterwards, so the diagram came out fitted to
  // the full window width and off-centre. Until the user moves the viewport
  // themselves, refit whenever the pane is resized.
  let userMovedViewport = false;
  $effect(() => {
    const width = flowStore.width;
    const height = flowStore.height;
    if (initialViewport || userMovedViewport || width === 0 || height === 0) return;
    untrack(() => {
      if (props.nodesState.nodes.length > 0) void flow.fitView();
    });
  });
  const onMoveStart = (event: MouseEvent | TouchEvent | null) => {
    if (event) userMovedViewport = true;
    closeContextMenu();
  };
  useEscapeKey(
    () => Boolean(contextMenu),
    closeContextMenu,
  );
  useEscapeKey(
    () => Boolean(activeInsertTool),
    () => (activeInsertTool = null),
  );

  $effect(() => {
    if (!contextMenu) return;
    window.addEventListener("click", closeContextMenu);
    window.addEventListener("wheel", closeContextMenu);
    return () => {
      window.removeEventListener("click", closeContextMenu);
      window.removeEventListener("wheel", closeContextMenu);
    };
  });

  const cursor = createCollaboratorCursor(() => props.awareness, flow.screenToFlowPosition);
  $effect(() => () => cursor.dispose());

  /**
   * Broadcast this user's table selection — the Figma-style outline other
   * participants see on this project. Keyed on the joined id string, so an
   * unrelated update handing out a fresh (but equal) id array doesn't
   * re-broadcast.
   */
  const selectedTableIdsKey = $derived(props.selectedTableIds.join(","));
  $effect(() => {
    const key = selectedTableIdsKey;
    props.awareness?.setLocalStateField("selection", key ? key.split(",") : []);
  });

  function handleSelectInsertTool(tool: CanvasInsertTool) {
    // Clicking the active tool again is how you put the pointer back into
    // ordinary selection mode — the second half of the toggle Figma uses.
    activeInsertTool = activeInsertTool === tool ? null : tool;
  }

  function handlePaneClick(event: MouseEvent) {
    props.onClearFieldSelection();
    props.onSelectEdge(null);
    if (!activeInsertTool) return;
    const position = flow.screenToFlowPosition({ x: event.clientX, y: event.clientY });
    if (activeInsertTool === "table") props.onAddTable(position);
    else if (activeInsertTool === "zone") props.onAddZone(position);
    else if (activeInsertTool === "note") props.onAddNote(position);
    else props.onAddEnum(position);
    // Deliberately left active: placing several tables in a row is the whole
    // point, and Escape (or picking the tool again) is how you stop.
  }

  /**
   * Right-click on empty canvas opens the insert menu — unless the right
   * button was dragged, which is a pan. The flow reserves the right button
   * for panning (`panOnDrag={[1, 2]}`) and so never reports a pane context
   * menu itself; the press position tells the two gestures apart here.
   */
  let rightPressAt: { x: number; y: number } | null = null;
  function handleContextMenu(event: MouseEvent) {
    const target = event.target as Element | null;
    if (!target?.classList.contains("svelte-flow__pane")) return;
    event.preventDefault();
    const press = rightPressAt;
    rightPressAt = null;
    if (press && Math.hypot(event.clientX - press.x, event.clientY - press.y) > CONTEXT_MENU_DRAG_TOLERANCE_PX) return;
    if (!props.canWrite) return;
    contextMenu = {
      screenX: event.clientX,
      screenY: event.clientY,
      flowPosition: flow.screenToFlowPosition({ x: event.clientX, y: event.clientY }),
    };
  }

  useCanvasDeleteKey({
    canWrite: () => props.canWrite,
    selectedNodeIds: () => props.nodesState.nodes.filter((node) => node.selected).map((node) => node.id),
    selectedEdgeIds: () => (props.selectedEdgeId ? [props.selectedEdgeId] : []),
    deleteNodes: (ids) => props.nodesState.deleteNodes(ids),
    deleteEdges: (ids) => {
      props.onDeleteEdges(ids);
      if (props.selectedEdgeId && ids.includes(props.selectedEdgeId)) props.onSelectEdge(null);
    },
  });

  // Replaces the flow's own `selectionOnDrag` — see `lassoSelection.ts`.
  const onLassoPointerDown = createLassoSelection({
    nodes: () => props.nodesState.nodes,
    screenToFlowPosition: flow.screenToFlowPosition,
    select: (isSelected) => props.nodesState.setSelection(isSelected),
    rect: () => lassoRect,
  });

  const suppressNativeMenu = ({ event }: { event: MouseEvent }) => event.preventDefault();
</script>

<!--
  `canvas-links-highlighted` is the whole implementation of the "highlight
  every relation" toggle on the table side: one class here, combined in CSS
  with each row's own `is-fk` marker, instead of a flag threaded into every
  table node's data (which rebuilt and re-rendered the entire canvas on each
  flip).
-->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class={`min-w-0 flex-1 bg-bg-canvas ${activeInsertTool ? "canvas-placing" : ""} ${
    props.highlightLinks ? "canvas-links-highlighted" : ""
  }`}
  onmousemove={cursor.onMouseMove}
  onmouseleave={cursor.onMouseLeave}
  onpointerdown={(event) => {
    if (event.button === 2) rightPressAt = { x: event.clientX, y: event.clientY };
    onLassoPointerDown(event);
  }}
  oncontextmenu={handleContextMenu}
  style:--canvas-font-scale={props.fontScale}
>
  <!-- Painted directly by the lasso (no reactive state per frame) — hidden until a drag starts. -->
  <div bind:this={lassoRect} class="lasso-selection-rect" style="display: none"></div>
  <SvelteFlow
    bind:nodes={props.nodesState.nodes}
    edges={props.edges}
    {nodeTypes}
    {edgeTypes}
    onconnect={props.onConnect}
    onpaneclick={({ event }) => handlePaneClick(event)}
    onedgeclick={({ edge }) => props.onSelectEdge(edge.id)}
    onnodeclick={() => props.onSelectEdge(null)}
    onnodecontextmenu={suppressNativeMenu}
    onselectioncontextmenu={suppressNativeMenu}
    onnodedragstart={({ nodes }) => props.nodesState.onDragStart(nodes)}
    onnodedrag={({ nodes }) => props.nodesState.onDrag(nodes)}
    onnodedragstop={({ nodes }) => props.nodesState.onDragStop(nodes)}
    onmovestart={onMoveStart}
    onmoveend={onMoveEnd}
    deleteKey={null}
    nodesDraggable={props.canWrite}
    nodesConnectable={props.canWrite}
    snapGrid={snapToGrid ? [GRID_SIZE, GRID_SIZE] : undefined}
    fitView={!initialViewport}
    initialViewport={initialViewport ?? undefined}
    panOnDrag={[1, 2]}
    {...CANVAS_VIEWPORT_PROPS}
    onlyRenderVisibleElements={false}
    proOptions={{ hideAttribution: true }}
  >
    <Background
      patternColor="var(--color-canvas-grid)"
      bgColor="var(--color-bg-canvas)"
      gap={20}
      variant={gridStyle as BackgroundVariant}
    />
    <RemoteCursorsLayer awareness={props.awareness} />
    <!-- Viewport control lives in its own corner pill: it is used at different
         moments from the editing tools, and pinning it left means it doesn't
         shift as the toolbar beside it grows. -->
    <Panel position="bottom-left" class="nodrag nopan !bottom-4 !left-4">
      <CanvasZoomBar selectedIds={props.selectedTableIds} />
    </Panel>
    <Panel position="bottom-center" class="nodrag nopan pointer-events-none !bottom-4 flex flex-col items-center gap-2">
      {#if props.statusMessage}
        <span
          class="pointer-events-auto rounded-full border border-border bg-surface-raised/95 px-3 py-1 text-[11.5px] text-text-secondary shadow-lg backdrop-blur-md"
        >
          {props.statusMessage}
        </span>
      {/if}
      <CanvasToolbar
        canWrite={props.canWrite}
        activeTool={activeInsertTool}
        onSelectTool={handleSelectInsertTool}
        activeDetailLevel={props.activeDetailLevel}
        onSetDetailLevel={props.onSetDetailLevel}
        highlightLinks={props.highlightLinks}
        onHighlightLinksChange={props.onHighlightLinksChange}
        showValidationIssues={props.showValidationIssues}
        onShowValidationIssuesChange={props.onShowValidationIssuesChange}
        minimapVisible={minimap.visible}
        onToggleMinimap={minimap.toggle}
        searchOpen={search.open}
        onToggleSearch={() => (search.open ? search.close() : search.setOpen(true))}
        canvasCommands={props.canvasCommands}
        onRunCanvasCommand={props.onRunCanvasCommand}
        onOpenPlugins={props.onOpenPlugins}
        viewMode={props.viewMode}
        onSetViewMode={props.onSetViewMode}
      />
    </Panel>
    {#if minimap.visible}
      <CanvasMinimap nodeColor={canvasMinimapNodeColor} />
    {/if}
    {#if props.selectedTableIds.length > 1 && props.canWrite}
      <SelectionColorToolbar
        count={props.selectedTableIds.length}
        palette={props.palette}
        onPick={(color) => props.onSetTablesColor(props.selectedTableIds, color)}
        onGroup={() => props.onGroupTables(props.selectedTableIds)}
      />
    {/if}
    {#if search.open}
      <CanvasSearchPanel
        query={search.query}
        onQueryChange={search.changeQuery}
        matchCount={search.matchIds.length}
        activeIndex={search.activeIndex}
        onNext={() => search.step(1)}
        onPrevious={() => search.step(-1)}
        onClose={search.close}
      />
    {/if}
  </SvelteFlow>
  {#if contextMenu}
    <CanvasContextMenu
      menu={contextMenu}
      onAddTable={props.onAddTable}
      onAddZone={props.onAddZone}
      onAddNote={props.onAddNote}
      onAddEnum={props.onAddEnum}
      onClose={closeContextMenu}
    />
  {/if}
</div>
