// apps/web/src/AcceptInvite.tsx
import { useState } from "react";
import { LogoMarkIcon } from "./Icons.js";
import { Button } from "./ui/Button.js";
import { Field } from "./ui/Field.js";
import { ErrorText } from "./ui/Alert.js";
import type { Session } from "./types.js";

function AcceptInvite(props: { token: string; onLoggedIn: (session: Session) => void }) {
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (password.length < 8) {
      setError("Password must be at least 8 characters.");
      return;
    }
    if (password !== confirm) {
      setError("Passwords don't match.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`/api/invitations/${props.token}/accept`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ password }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok) {
        props.onLoggedIn(data as Session);
      } else {
        setError(data.error ?? `Could not accept this invitation (${res.status})`);
      }
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="flex h-full items-center justify-center p-6">
      <form
        className="flex w-full max-w-[340px] flex-col rounded-md border border-border bg-surface p-7 shadow-md"
        onSubmit={submit}
      >
        <span className="mx-auto mb-3 flex h-[26px] w-[26px] items-center justify-center rounded-sm bg-gradient-to-br from-primary to-[#7c3aed] text-white">
          <LogoMarkIcon size={16} style={{ color: "white" }} />
        </span>
        <h1 className="mb-1 text-center text-lg font-bold">Set your password</h1>
        <p className="mb-5 text-center text-[13px] text-text-muted">Finish creating your account to accept this invitation.</p>
        <Field
          label="Password"
          type="password"
          autoFocus
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          autoComplete="new-password"
        />
        <Field
          label="Confirm password"
          type="password"
          value={confirm}
          onChange={(e) => setConfirm(e.target.value)}
          autoComplete="new-password"
        />
        <Button variant="primary" type="submit" disabled={busy || !password || !confirm}>
          {busy ? "Creating account…" : "Create account"}
        </Button>
        {error && <ErrorText>{error}</ErrorText>}
      </form>
    </div>
  );
}

export { AcceptInvite };
export default AcceptInvite;

// apps/web/src/features/auth/AcceptInvite.svelte
<script lang="ts" module>
  const MIN_PASSWORD_LENGTH = 8;

  /**
   * Best-effort save into the browser's own password manager via the
   * Credential Management API (Chromium browsers). Not available everywhere
   * (Firefox/Safari lack it), which is fine: those browsers instead pick up
   * the credential from the real login form submission that follows.
   */
  async function tryStoreCredential(email: string, password: string): Promise<void> {
    try {
      const PasswordCredentialCtor = (window as unknown as { PasswordCredential?: new (data: unknown) => Credential })
        .PasswordCredential;
      if (!PasswordCredentialCtor || !navigator.credentials?.store) return;
      const credential = new PasswordCredentialCtor({ id: email, password, name: email });
      await navigator.credentials.store(credential);
    } catch {
      // Best effort only — never block account creation on this.
    }
  }
</script>

<script lang="ts">
  import Icon from "@/components/icons/Icon.svelte";
  import { LogoMarkIcon } from "@/components/icons/Icons";
  import Button from "@/components/ui/Button.svelte";
  import Field from "@/components/ui/Field.svelte";
  import ErrorText from "@/components/ui/ErrorText.svelte";
  import { useAsyncAction } from "@/hooks/asyncAction.svelte";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { acceptInvitation } from "@/services/invitationsApi";

  let {
    token,
    onAccepted,
  }: {
    token: string;
    /** Called once the account exists. The caller is responsible for sending
     * the user on to a real login — this component intentionally never
     * receives a session. */
    onAccepted: (email: string) => void;
  } = $props();

  const { t } = useTranslation();
  let password = $state("");
  let confirmation = $state("");
  let validationError = $state<string | null>(null);

  const createAccount = useAsyncAction(async () => {
    const { email } = await acceptInvitation(token, password);
    await tryStoreCredential(email, password);
    onAccepted(email);
  });

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (password.length < MIN_PASSWORD_LENGTH) {
      validationError = t("acceptInvite.passwordTooShort", { min: MIN_PASSWORD_LENGTH });
      return;
    }
    if (password !== confirmation) {
      validationError = t("acceptInvite.passwordMismatch");
      return;
    }
    validationError = null;
    void createAccount.run();
  }
</script>

<div class="flex h-full items-center justify-center p-6">
  <form
    class="flex w-full max-w-[340px] flex-col rounded-md border border-border bg-surface p-7 shadow-md"
    onsubmit={handleSubmit}
  >
    <span
      class="mx-auto mb-3 flex h-[26px] w-[26px] items-center justify-center rounded-sm bg-gradient-to-br from-primary to-[#7c3aed] text-white"
    >
      <Icon icon={LogoMarkIcon} size={16} style="color: white" />
    </span>
    <h1 class="mb-1 text-center text-lg font-bold">{t("acceptInvite.title")}</h1>
    <p class="mb-5 text-center text-[13px] text-text-muted">{t("acceptInvite.subtitle")}</p>
    <Field
      label={t("login.passwordLabel")}
      type="password"
      autofocus
      bind:value={password}
      autocomplete="new-password"
    />
    <Field
      label={t("acceptInvite.confirmPassword")}
      type="password"
      bind:value={confirmation}
      autocomplete="new-password"
    />
    <Button variant="primary" type="submit" disabled={createAccount.pending || !password || !confirmation}>
      {createAccount.pending ? t("acceptInvite.creating") : t("acceptInvite.createAccount")}
    </Button>
    {#if validationError ?? createAccount.error}
      <ErrorText>{validationError ?? createAccount.error}</ErrorText>
    {/if}
  </form>
</div>
