// apps/web/src/features/editor/nodes/table/FieldEditorPopover.tsx
import { useCallback, useRef, useState } from "react";
import { createPortal } from "react-dom";
import {
  MAX_DEFAULT_LENGTH,
  MAX_NAME_LENGTH,
  MAX_NOTE_LENGTH,
  MAX_TEXT_LENGTH,
  MAX_TYPE_LENGTH,
  type Comment,
  type Field,
} from "@athanordb/shared";
import {
  AsteriskIcon,
  CloseIcon,
  DiamondIcon,
  IncrementIcon,
  KeyIcon,
  PencilIcon,
  TrashIcon,
} from "@/components/icons/Icons";
import { Button } from "@/components/ui/Button";
import { TEXTAREA_SM_CLASS } from "@/components/ui/inputStyles";
import { formatTimestamp } from "@/features/editor/comments/CommentThread";
import { useAnchoredPlacement } from "@/hooks/useMenuPlacement";
import { useCloseOnViewportChange } from "@/hooks/useCloseOnViewportChange";
import { useDismissablePopover } from "@/hooks/useDismissablePopover";
import { useDraftValue } from "@/hooks/useDraftValue";
import { useTranslation } from "@/i18n/useTranslation";
import {
  FIELD_TYPE_CHIP_ACTIVE_CLASS,
  FIELD_TYPE_CHIP_CLASS,
  KW_TOGGLE_ACTIVE_CLASS,
  KW_TOGGLE_BASE_CLASS,
  POPOVER_GROUP_CLASS,
  POPOVER_HEADER_CLASS,
  POPOVER_INPUT_CLASS,
  POPOVER_INPUT_MONO_CLASS,
  POPOVER_LABEL_CLASS,
  POPOVER_TITLE_CLASS,
} from "@/features/editor/nodes/table/tableStyles";

const COMMON_TYPES = ["int", "varchar", "text", "boolean", "timestamp", "uuid", "json", "decimal", "bigint"];

export interface FieldEditorPopoverProps {
  field: Field;
  comments: Comment[];
  currentUser: string;
  onUpdateField?: (fieldId: string, updates: Partial<Field> | ((current: Field) => Partial<Field>)) => void;
  onDeleteField?: (fieldId: string) => void;
  onAddComment: (text: string) => void;
  onDeleteComment: (commentId: string) => void;
  triggerClassName: string;
}

/**
 * Column's pencil button — popover to edit name/type/default/note, toggle
 * pk/unique/notNull/increment, and manage the column's comment thread.
 *
 * Comments live here too (not just behind their own indicator icon) because
 * that icon only appears once a comment already exists — this is the one
 * place a column with no comments yet can still get its first one.
 */
export function FieldEditorPopover({
  field,
  comments,
  currentUser,
  onUpdateField,
  onDeleteField,
  onAddComment,
  onDeleteComment,
  triggerClassName,
}: FieldEditorPopoverProps) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);
  const [triggerRect, setTriggerRect] = useState<DOMRect | null>(null);
  const [commentDraft, setCommentDraft] = useState("");

  const triggerRef = useRef<HTMLButtonElement>(null);
  const popoverRef = useRef<HTMLDivElement>(null);

  const update = (updates: Partial<Field> | ((current: Field) => Partial<Field>)) =>
    onUpdateField?.(field.id, updates);

  const name = useDraftValue(field.name, (next) => update({ name: next }));
  const type = useDraftValue(field.type, (next) => update({ type: next }));
  const defaultValue = useDraftValue(field.default ?? "", (next) => update({ default: next }), { allowEmpty: true });
  const note = useDraftValue(field.note ?? "", (next) => update({ note: next }), { allowEmpty: true });

  const submitComment = () => {
    const text = commentDraft.trim();
    if (!text) return;
    onAddComment(text);
    setCommentDraft("");
  };

  const dismiss = useCallback(() => setOpen(false), []);
  useDismissablePopover(open, dismiss, [popoverRef, triggerRef]);
  useCloseOnViewportChange(open, dismiss);
  // Anchored to the right of the whole table (not just this row's trigger)
  // so the popover sits beside the table instead of dropping down over it —
  // matches TableSettingsPopover.
  const placement = useAnchoredPlacement(open ? triggerRect : null, popoverRef, "right");

  const toggleOpen = () => {
    if (!open && triggerRef.current) {
      const tableRect = triggerRef.current.closest(".table-node")?.getBoundingClientRect();
      setTriggerRect(tableRect ?? triggerRef.current.getBoundingClientRect());
    }
    setOpen((current) => !current);
  };

  const attributeToggles = [
    {
      active: field.pk,
      activeClass: KW_TOGGLE_ACTIVE_CLASS.pk,
      icon: <KeyIcon size={12} />,
      labelKey: "field.primaryKey",
      tooltipKey: "field.primaryKeyTooltip",
      apply: () => update((f) => ({ pk: !f.pk })),
    },
    {
      active: field.unique,
      activeClass: KW_TOGGLE_ACTIVE_CLASS.unique,
      icon: <DiamondIcon size={10} />,
      labelKey: "field.unique",
      tooltipKey: "field.uniqueTooltip",
      apply: () => update((f) => ({ unique: !f.unique })),
    },
    {
      active: field.notNull,
      activeClass: KW_TOGGLE_ACTIVE_CLASS.notNull,
      icon: <AsteriskIcon size={11} />,
      labelKey: "field.notNull",
      tooltipKey: "field.notNullTooltip",
      apply: () => update((f) => ({ notNull: !f.notNull })),
    },
    {
      active: field.increment,
      activeClass: KW_TOGGLE_ACTIVE_CLASS.increment,
      icon: <IncrementIcon size={11} />,
      labelKey: "field.increment",
      tooltipKey: "field.incrementTooltip",
      apply: () => update((f) => ({ increment: !f.increment })),
    },
  ] as const;

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        className={`nodrag ${triggerClassName}${open ? " has-open-popover" : ""}`}
        onClick={(event) => {
          event.stopPropagation();
          toggleOpen();
        }}
        onDoubleClick={(event) => event.stopPropagation()}
        data-tooltip={t("field.editTooltip")}
      >
        <PencilIcon size={11} />
      </button>
      {open &&
        triggerRect &&
        createPortal(
          <div
            ref={popoverRef}
            className="fixed z-[var(--z-popover)] flex w-[296px] flex-col gap-3 rounded-lg border border-border-strong bg-surface-raised p-3.5 shadow-lg nodrag"
            style={placement ?? { left: triggerRect.left, top: triggerRect.bottom + 6, visibility: "hidden" }}
            onClick={(event) => event.stopPropagation()}
            onMouseDown={(event) => event.stopPropagation()}
          >
            <div className={POPOVER_HEADER_CLASS}>
              <span className={POPOVER_TITLE_CLASS}>{t("field.propertiesTitle")}</span>
              <Button
                variant="danger-ghost"
                size="icon"
                onClick={() => {
                  onDeleteField?.(field.id);
                  setOpen(false);
                }}
                data-tooltip={t("field.delete")}
              >
                <TrashIcon size={13} />
              </Button>
            </div>

            <div className={POPOVER_GROUP_CLASS}>
              <label className={POPOVER_LABEL_CLASS}>{t("field.nameLabel")}</label>
              <input
                autoFocus
                className={POPOVER_INPUT_CLASS}
                value={name.value}
                maxLength={MAX_NAME_LENGTH}
                onChange={(event) => name.setValue(event.target.value)}
                onBlur={() => name.commit()}
                onKeyDown={name.handleKeyDown}
                placeholder={t("field.namePlaceholder")}
              />
            </div>

            <div className={POPOVER_GROUP_CLASS}>
              <label className={POPOVER_LABEL_CLASS}>{t("field.typeLabel")}</label>
              <input
                className={POPOVER_INPUT_MONO_CLASS}
                value={type.value}
                maxLength={MAX_TYPE_LENGTH}
                onChange={(event) => type.setValue(event.target.value)}
                onBlur={() => type.commit()}
                onKeyDown={type.handleKeyDown}
                placeholder={t("field.typePlaceholder")}
              />
              <div className="mt-0.5 flex flex-wrap gap-1">
                {COMMON_TYPES.map((commonType) => (
                  <button
                    key={commonType}
                    type="button"
                    className={`${FIELD_TYPE_CHIP_CLASS} ${field.type === commonType ? FIELD_TYPE_CHIP_ACTIVE_CLASS : ""}`}
                    onClick={() => {
                      type.setValue(commonType);
                      type.commit(commonType);
                    }}
                  >
                    {commonType}
                  </button>
                ))}
              </div>
            </div>

            <div className={POPOVER_GROUP_CLASS}>
              <label className={POPOVER_LABEL_CLASS}>{t("field.attributesLabel")}</label>
              <div className="grid grid-cols-2 gap-[5px]">
                {attributeToggles.map((toggle) => (
                  <button
                    key={toggle.labelKey}
                    type="button"
                    className={`${KW_TOGGLE_BASE_CLASS} ${toggle.active ? toggle.activeClass : ""}`}
                    onClick={toggle.apply}
                    data-tooltip={t(toggle.tooltipKey)}
                  >
                    {toggle.icon} {t(toggle.labelKey)}
                  </button>
                ))}
              </div>
            </div>

            <div className={POPOVER_GROUP_CLASS}>
              <label className={POPOVER_LABEL_CLASS}>{t("field.defaultLabel")}</label>
              <input
                className={POPOVER_INPUT_MONO_CLASS}
                value={defaultValue.value}
                maxLength={MAX_DEFAULT_LENGTH}
                onChange={(event) => defaultValue.setValue(event.target.value)}
                onBlur={() => defaultValue.commit()}
                onKeyDown={defaultValue.handleKeyDown}
                placeholder={t("field.defaultPlaceholder")}
              />
            </div>

            <div className={POPOVER_GROUP_CLASS}>
              <label className={POPOVER_LABEL_CLASS}>{t("field.noteLabel")}</label>
              <input
                className={POPOVER_INPUT_CLASS}
                value={note.value}
                maxLength={MAX_NOTE_LENGTH}
                onChange={(event) => note.setValue(event.target.value)}
                onBlur={() => note.commit()}
                onKeyDown={note.handleKeyDown}
                placeholder={t("field.notePlaceholder")}
              />
            </div>

            <div className={`${POPOVER_GROUP_CLASS} border-t border-border pt-3`}>
              <label className={POPOVER_LABEL_CLASS}>{t("comments.title")}</label>
              {comments.length > 0 && (
                <div className="flex max-h-[160px] flex-col gap-1.5 overflow-y-auto">
                  {comments.map((comment) => (
                    <div key={comment.id} className="rounded-sm bg-surface p-1.5">
                      <div className="mb-0.5 flex items-baseline gap-1.5">
                        <span className="text-[11.5px] font-bold text-text">{comment.author}</span>
                        <span className="flex-1 text-[10.5px] text-text-muted">
                          {formatTimestamp(comment.createdAt)}
                        </span>
                        {comment.author === currentUser && (
                          <button
                            type="button"
                            className="flex h-5 w-5 shrink-0 items-center justify-center rounded-sm text-text-muted transition-colors hover:bg-danger-light hover:text-danger"
                            onClick={() => onDeleteComment(comment.id)}
                            data-tooltip={t("comments.delete")}
                          >
                            <CloseIcon size={11} />
                          </button>
                        )}
                      </div>
                      <div className="whitespace-pre-wrap break-words text-[12.5px] leading-[1.4] text-text-secondary">
                        {comment.text}
                      </div>
                    </div>
                  ))}
                </div>
              )}
              <div className="flex gap-1.5">
                <textarea
                  className={`${TEXTAREA_SM_CLASS} flex-1`}
                  value={commentDraft}
                  onChange={(event) => setCommentDraft(event.target.value)}
                  placeholder={t("comments.placeholder")}
                  maxLength={MAX_TEXT_LENGTH}
                  onKeyDown={(event) => {
                    if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) submitComment();
                  }}
                />
                <Button variant="primary" size="sm" onClick={submitComment} disabled={!commentDraft.trim()}>
                  {t("comments.post")}
                </Button>
              </div>
            </div>
          </div>,
          document.body,
        )}
    </>
  );
}

// apps/web/src/features/editor/nodes/table/FieldEditorPopover.svelte
<script lang="ts">
  import type { Comment, Field, RefAction } from "@athanordb/shared";
  import type { FieldRefInfo } from "@/features/editor/nodes/table/fieldRefInfo";
  import Icon from "@/components/icons/Icon.svelte";
  import { PencilIcon } from "@/components/icons/Icons";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import FieldEditorPanel from "./FieldEditorPanel.svelte";

  /**
   * Column's pencil button — opens a popover to edit name/type/default/note,
   * toggle pk/unique/notNull/increment, and manage the column's comment thread.
   *
   * Only the trigger lives here: every column row on the canvas carries one of
   * these, so the panel itself (drafts, dismiss listeners, viewport watch) is
   * only created while it's open.
   */
  let {
    field,
    comments,
    currentUser,
    onUpdateField,
    onDeleteField,
    onAddComment,
    onDeleteComment,
    fieldRefs,
    onUpdateRefAction,
    triggerClassName,
  }: {
    field: Field;
    comments: Comment[];
    currentUser: string;
    onUpdateField?: (fieldId: string, updates: Partial<Field> | ((current: Field) => Partial<Field>)) => void;
    onDeleteField?: (fieldId: string) => void;
    onAddComment: (text: string) => void;
    onDeleteComment: (commentId: string) => void;
    fieldRefs?: FieldRefInfo[];
    onUpdateRefAction?: (refId: string, patch: { onDelete?: RefAction; onUpdate?: RefAction }) => void;
    triggerClassName: string;
  } = $props();

  const { t } = useTranslation();
  let open = $state(false);
  let triggerRect = $state.raw<DOMRect | null>(null);
  let trigger: HTMLButtonElement | undefined = $state();

  function toggleOpen() {
    if (!open && trigger) {
      // Anchored to the right of the whole table (not just this row's
      // trigger) so the popover sits beside the table instead of dropping
      // down over it — matches TableSettingsPopover.
      const tableRect = trigger.closest(".table-node")?.getBoundingClientRect();
      triggerRect = tableRect ?? trigger.getBoundingClientRect();
    }
    open = !open;
  }
</script>

<button
  bind:this={trigger}
  type="button"
  class={`nodrag ${triggerClassName}${open ? " has-open-popover" : ""}`}
  onclick={(event) => {
    event.stopPropagation();
    toggleOpen();
  }}
  ondblclick={(event) => event.stopPropagation()}
  data-tooltip={t("field.editTooltip")}
  aria-label={t("field.editTooltip")}
>
  <Icon icon={PencilIcon} size={11} />
</button>
{#if open && triggerRect}
  <FieldEditorPanel
    {field}
    {comments}
    {currentUser}
    {onUpdateField}
    {onDeleteField}
    {onAddComment}
    {onDeleteComment}
    {fieldRefs}
    {onUpdateRefAction}
    {triggerRect}
    {trigger}
    onClose={() => (open = false)}
  />
{/if}
