// apps/web/src/components/ui/Card.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    children: Snippet;
    variant?: "default" | "glass" | "glow" | "outline";
    interactive?: boolean;
  }

  let { children, variant = "default", interactive = false, class: className = "", ...rest }: Props = $props();

  const baseStyles = "rounded-xl border transition-[transform,border-color,box-shadow] duration-150 ease-out";

  const variantStyles = $derived(
    {
      default: "bg-surface border-border shadow-xs",
      // Explicit border colour: `.glass-card` only owns the fill and the blur
      // now, and preflight is disabled — a bare `border` with no colour utility
      // would paint in `currentColor`.
      glass: "glass-card border-white/[0.06] shadow-sm",
      glow: "bg-surface-raised border-primary-border shadow-lg",
      outline: "bg-transparent border-border hover:border-border-strong",
    }[variant],
  );

  // A half-pixel lift, not a hop: the card should acknowledge the cursor, not
  // jump out from under it.
  const hoverStyles = $derived(
    interactive ? "cursor-pointer hover:-translate-y-0.5 hover:border-border-strong hover:shadow-md" : "",
  );
</script>

<div class={`${baseStyles} ${variantStyles} ${hoverStyles} ${className}`.trim()} {...rest}>
  {@render children()}
</div>

// apps/web/src/ui/Card.tsx
import type { HTMLAttributes, ReactNode } from "react";

export interface CardProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
  variant?: "default" | "glass" | "glow" | "outline";
  interactive?: boolean;
}

export function Card({ children, variant = "default", interactive = false, className = "", ...rest }: CardProps) {
  const baseStyles = "rounded-xl border transition-all duration-200";
  
  const variantStyles = {
    default: "bg-surface border-border shadow-sm",
    glass: "glass-card shadow-md",
    glow: "bg-surface-raised border-primary-border glow-indigo shadow-lg",
    outline: "bg-transparent border-border hover:border-border-strong",
  }[variant];

  const hoverStyles = interactive
    ? "hover:-translate-y-1 hover:border-primary/50 hover:shadow-md cursor-pointer"
    : "";

  return (
    <div className={`${baseStyles} ${variantStyles} ${hoverStyles} ${className}`.trim()} {...rest}>
      {children}
    </div>
  );
}

export function CardHeader({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`px-6 pt-6 pb-3 border-b border-border/50 ${className}`.trim()}>{children}</div>;
}

export function CardBody({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`p-6 ${className}`.trim()}>{children}</div>;
}

export function CardFooter({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`px-6 py-4 bg-surface-raised/40 border-t border-border/50 rounded-b-xl ${className}`.trim()}>{children}</div>;
}
