// apps/web/src/admin/InvitationsTab.tsx
import { useEffect, useState } from "react";
import { LinkIcon, PlusIcon, TrashIcon } from "../Icons.js";
import { Button } from "../ui/Button.js";
import { Badge } from "../ui/Badge.js";
import { ErrorText } from "../ui/Alert.js";
import { List, ListMain, ListRow, EmptyState } from "../ui/List.js";
import { CHECKBOX_CLASS, INPUT_CLASS } from "../ui/inputStyles.js";
import type { InvitationSummary } from "../types.js";

const STATUS_TONE = { pending: "warning", accepted: "success", expired: "danger" } as const;

export function InvitationsTab() {
  const [invitations, setInvitations] = useState<InvitationSummary[]>([]);
  const [email, setEmail] = useState("");
  const [isAdmin, setIsAdmin] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedToken, setCopiedToken] = useState<string | null>(null);

  const refresh = () => {
    fetch("/api/invitations")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`list failed (${r.status})`))))
      .then(setInvitations)
      .catch((err) => setError((err as Error).message));
  };

  useEffect(refresh, []);

  const create = async () => {
    const trimmed = email.trim();
    if (!trimmed) return;
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/invitations", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: trimmed, isAdmin }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok) {
        setEmail("");
        setIsAdmin(false);
        refresh();
      } else {
        setError(data.error ?? `Invite failed (${res.status})`);
      }
    } finally {
      setBusy(false);
    }
  };

  const revoke = async (token: string) => {
    await fetch(`/api/invitations/${token}`, { method: "DELETE" });
    refresh();
  };

  const copyLink = (inv: InvitationSummary) => {
    navigator.clipboard.writeText(`${location.origin}/invite/${inv.token}`).then(() => {
      setCopiedToken(inv.token);
      setTimeout(() => setCopiedToken((t) => (t === inv.token ? null : t)), 1500);
    });
  };

  return (
    <div>
      <div className="mb-7 flex max-w-[420px] items-center gap-2">
        <input
          className={`${INPUT_CLASS} flex-1`}
          placeholder="Email to invite"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && create()}
        />
        <label className="flex items-center gap-1.5 whitespace-nowrap text-[13px] text-text-muted">
          <input
            type="checkbox"
            className={CHECKBOX_CLASS}
            checked={isAdmin}
            onChange={(e) => setIsAdmin(e.target.checked)}
          />
          Admin
        </label>
        <Button variant="primary" onClick={create} disabled={busy || !email.trim()}>
          <PlusIcon size={14} /> Invite
        </Button>
      </div>
      {error && <ErrorText>{error}</ErrorText>}
      {invitations.length === 0 ? (
        <EmptyState>No invitations yet.</EmptyState>
      ) : (
        <List>
          {invitations.map((inv) => (
            <ListRow key={inv.token}>
              <ListMain>
                <span>{inv.email}</span>
                {inv.isAdmin && <Badge tone="admin">Admin</Badge>}
              </ListMain>
              <Badge tone={STATUS_TONE[inv.status]}>{inv.status}</Badge>
              {inv.status === "pending" && (
                <>
                  <Button size="sm" onClick={() => copyLink(inv)}>
                    <LinkIcon size={12} /> {copiedToken === inv.token ? "Copied" : "Copy link"}
                  </Button>
                  <Button variant="ghost" size="icon" data-tooltip="Revoke" onClick={() => revoke(inv.token)}>
                    <TrashIcon size={13} />
                  </Button>
                </>
              )}
            </ListRow>
          ))}
        </List>
      )}
    </div>
  );
}

// apps/web/src/features/admin/InvitationsTab.svelte
<script lang="ts" module>
  import type { InvitationSummary, TranslationKeyOf } from "@/types";

  const STATUS_TONE = { pending: "warning", accepted: "success", expired: "danger" } as const;
  const STATUS_LABEL_KEY = {
    pending: "admin.invitations.status.pending",
    accepted: "admin.invitations.status.accepted",
    expired: "admin.invitations.status.expired",
  } as const satisfies Record<InvitationSummary["status"], TranslationKeyOf>;

  const COPIED_FEEDBACK_MS = 1500;
</script>

<script lang="ts">
  import Icon from "@/components/icons/Icon.svelte";
  import { LinkIcon, PlusIcon, TrashIcon } from "@/components/icons/Icons";
  import Button from "@/components/ui/Button.svelte";
  import Badge from "@/components/ui/Badge.svelte";
  import ErrorText from "@/components/ui/ErrorText.svelte";
  import List from "@/components/ui/List.svelte";
  import ListMain from "@/components/ui/ListMain.svelte";
  import ListRow from "@/components/ui/ListRow.svelte";
  import EmptyState from "@/components/ui/EmptyState.svelte";
  import { CHECKBOX_CLASS, INPUT_CLASS } from "@/components/ui/inputStyles";
  import { useAsyncAction } from "@/hooks/asyncAction.svelte";
  import { useAsyncResource } from "@/hooks/asyncResource.svelte";
  import { copyText } from "@/utils/clipboard";
  import { useTranslation } from "@/i18n/i18n.svelte";
  import { createInvitation, fetchInvitations, revokeInvitation } from "@/services/invitationsApi";

  const { t } = useTranslation();
  const invitations = useAsyncResource(fetchInvitations);
  let email = $state("");
  let invitingAsAdmin = $state(false);
  let copiedToken = $state<string | null>(null);

  const invite = useAsyncAction(async () => {
    await createInvitation(email.trim(), invitingAsAdmin);
    email = "";
    invitingAsAdmin = false;
    invitations.reload();
  });

  const revoke = useAsyncAction(async (token: string) => {
    await revokeInvitation(token);
    invitations.reload();
  });

  function handleInvite() {
    if (email.trim()) void invite.run();
  }

  function copyInviteLink(invitation: InvitationSummary) {
    void copyText(`${location.origin}/invite/${invitation.token}`).then((ok) => {
      if (!ok) return;
      copiedToken = invitation.token;
      // Only clears its own feedback: copying a second link before the first
      // timer fires must not blank the newer confirmation.
      setTimeout(() => {
        if (copiedToken === invitation.token) copiedToken = null;
      }, COPIED_FEEDBACK_MS);
    });
  }

  const rows = $derived(invitations.data ?? []);
  const error = $derived(invitations.error ?? invite.error ?? revoke.error);
</script>

<div>
  <div class="mb-7 flex max-w-[420px] items-center gap-2">
    <input
      class={`${INPUT_CLASS} flex-1`}
      placeholder={t("admin.invitations.emailPlaceholder")}
      bind:value={email}
      onkeydown={(event) => event.key === "Enter" && handleInvite()}
    />
    <label class="flex items-center gap-1.5 whitespace-nowrap text-[13px] text-text-muted">
      <input type="checkbox" class={CHECKBOX_CLASS} bind:checked={invitingAsAdmin} />
      {t("common.admin")}
    </label>
    <Button variant="primary" onclick={handleInvite} disabled={invite.pending || !email.trim()}>
      <Icon icon={PlusIcon} size={14} />
      {t("admin.invitations.invite")}
    </Button>
  </div>
  {#if error}<ErrorText>{error}</ErrorText>{/if}
  {#if rows.length === 0}
    <EmptyState>{invitations.loading ? t("common.loading") : t("admin.invitations.empty")}</EmptyState>
  {:else}
    <List>
      {#each rows as invitation (invitation.token)}
        <ListRow>
          <ListMain>
            <span>{invitation.email}</span>
            {#if invitation.isAdmin}<Badge tone="admin">{t("common.admin")}</Badge>{/if}
          </ListMain>
          <Badge tone={STATUS_TONE[invitation.status]}>{t(STATUS_LABEL_KEY[invitation.status])}</Badge>
          {#if invitation.status === "pending"}
            <Button size="sm" onclick={() => copyInviteLink(invitation)}>
              <Icon icon={LinkIcon} size={12} />
              {copiedToken === invitation.token ? t("common.copied") : t("admin.invitations.copyLink")}
            </Button>
            <Button
              variant="ghost"
              size="icon"
              data-tooltip={t("admin.invitations.revoke")}
              onclick={() => void revoke.run(invitation.token)}
            >
              <Icon icon={TrashIcon} size={13} />
            </Button>
          {/if}
        </ListRow>
      {/each}
    </List>
  {/if}
</div>
